"""Tests for the SrV 2023 departure-time and activity-duration reference builder (issue #123,
Phase 0 Task 2).

The logic tests run on a tiny, hand-built HARMONISED fixture (the schema produced by
``srv_plan_structure.harmonise_srv``, not the raw SrV column names) -- the real SrV 2023
scientific-use microdata is local-only and must never be a test dependency. Every expected value
below is derivable by hand from the docstring of :func:`_fixture`.

Pin test at the bottom reads the COMMITTED CSVs generated by
``scripts/extract_srv_departure_times.py`` against the local-only raw microdata and only checks
structural invariants (never numeric pins from a run) -- it skips (never silently passes) when the
committed files are absent.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from braunschweig.calibration import srv_departure_times as T

REPO = Path(__file__).resolve().parents[1]
SRV_DIR = REPO / "eqasim-data" / "data" / "braunschweig" / "srv"


def _fixture():
    """3 persons, 7 trips (6 with a valid ``dep_min``), in the HARMONISED schema.

    ==== ============================== ====== ============================================
    pid  group                          weight reporting day
    ==== ============================== ====== ============================================
    p1   school_age_6_17_not_employed   3.0    one trip, 7:00 (420 min) to education
    p2   employed                       1.0    work@8:00 (480), home@17:00 (1020), then a
                                                trip with an unrecorded ("keine Angabe")
                                                departure time (dep_min/arr_min NaN)
    p3   employed                       2.0    work@8:30 (510), shop@9:20 (560), then a trip
                                                at 2080 min (34:40 -- past the 28 h window)
    ==== ============================== ====== ============================================

    Derivable expectations:

    * ``p2``'s third trip has ``dep_min`` NaN and is the ONLY invalid leg -> 6/7 legs valid,
      1 excluded (NaN).
    * ``p1``'s single trip is a quarter-hour report (420 % 15 == 0, half-width 7.5 min), so its
      de-rounded value lies in [412.5, 427.5) and its 15-minute bin is 27 (412.5/15 = 27.5) or 28
      (420/15 = 28.0 exactly), never 26 or 29.
    * segment "employed", purpose "work", position "first": ``p2`` trip 1 (weight 1.0, bin 32)
      and ``p3`` trip 1 (weight 2.0, bin 34) -> two bins, shares summing to 1.0 over weight 3.0.
    * segment "employed", purpose "home", position "later": only ``p2`` trip 2 (weight 1.0,
      1020 min, bin 68, no clipping) -> "home" never appears under position "first" (no one's
      first trip is a return home) and "work" never appears under "later" (neither ``p2`` nor
      ``p3`` has a later trip to work) -- this is the "later excludes seq-min legs" check.
    * ``p3``'s third trip departs at 2080 min (138.7 quarter-hours), whose raw AND de-rounded bin
      (138, clipped to 111) both exceed ``N_BINS - 1`` -> exactly 1 of the 6 valid legs is
      clipped in each of ``share_as_reported`` / ``share_derounded``.
    * Activity durations (next ``dep_min`` minus ``arr_min`` within the pid): ``p1`` trip 1 and
      ``p2`` trip 3 and ``p3`` trip 3 have no following trip (excluded, "no next"); ``p2`` trip 2
      has no next EITHER (its only following trip has a NaN ``dep_min``, also "no next"); ``p2``
      trip 1 -> (1020 - 500) / 60 = 8.667 h ("8h+"); ``p3`` trip 1 -> (560 - 530) / 60 = 0.5 h
      ("0-0.5h"); ``p3`` trip 2 -> (2080 - 580) / 60 = 25.0 h, OUTSIDE [0, 20] h -> EXCLUDED and
      counted. So of 7 trips: 4 have no measurable next activity, 1 is measured but out of range,
      2 are included (segment "employed", purpose "work": bands "0-0.5h" share 2/3, "8h+" 1/3).
    """
    persons = pd.DataFrame({
        "pid": ["p1", "p2", "p3"],
        "weight": [3.0, 1.0, 2.0],
        "group": ["school_age_6_17_not_employed", "employed", "employed"],
    })
    trips = pd.DataFrame({
        "pid":          ["p1", "p2", "p2", "p2", "p3", "p3", "p3"],
        "seq":          [1, 1, 2, 3, 1, 2, 3],
        "weight":       [3.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0],
        "purpose":      ["education", "work", "home", "leisure", "work", "shop", "other"],
        "prev_purpose": ["home", "home", "work", "home", "home", "work", "shop"],
        "dep_min":      [420.0, 480.0, 1020.0, np.nan, 510.0, 560.0, 2080.0],
        "arr_min":      [450.0, 500.0, 1040.0, np.nan, 530.0, 580.0, 2100.0],
    })
    return persons, trips


# --------------------------------------------------------------------------- departure_time_table
def test_first_trip_derounded_bin_stays_within_the_reporting_cell():
    # A 7:00 (420 min) quarter-hour report de-rounds to [412.5, 427.5), which can only ever land
    # in 15-minute bin 27 or 28 -- never 26 (< 412.5) or 29 (>= 427.5), for ANY offset drawn.
    persons, trips = _fixture()
    table = T.departure_time_table(persons, trips, np.random.RandomState(0))
    subset = table[(table["segment"] == "school_age_6_17_not_employed")
                   & (table["purpose"] == "education") & (table["position"] == "first")]
    assert len(subset) > 0
    assert set(subset["bin_15min"]) <= {27, 28}
    assert 26 not in set(subset["bin_15min"])
    assert 29 not in set(subset["bin_15min"])
    # p1 is the only contributor, so whichever bin(s) appear must sum in each column to 1.0.
    assert subset["share_derounded"].sum() == pytest.approx(1.0)
    assert subset["share_as_reported"].sum() == pytest.approx(1.0)
    # The as-reported time is exact (420 / 15 = 28.0), so its bin is always 28.
    assert subset.loc[subset["share_as_reported"] > 0, "bin_15min"].tolist() == [28]


def test_shares_sum_to_one_per_segment_purpose_position():
    persons, trips = _fixture()
    table = T.departure_time_table(persons, trips, np.random.RandomState(1))
    subset = table[(table["segment"] == "employed") & (table["purpose"] == "work")
                   & (table["position"] == "first")]
    # p2 trip 1 (480 min) and p3 trip 1 (510 min): two different 15-minute bins.
    assert len(subset) >= 2
    assert subset["share_derounded"].sum() == pytest.approx(1.0)
    assert subset["share_as_reported"].sum() == pytest.approx(1.0)
    assert int(subset["n_unweighted"].iloc[0]) == 2
    # Invariant must hold for every (segment, purpose, position) triple in the table, not only
    # the one checked in detail above.
    grouped = table.groupby(["segment", "purpose", "position"])
    assert np.allclose(grouped["share_derounded"].sum().values, 1.0)
    assert np.allclose(grouped["share_as_reported"].sum().values, 1.0)


def test_later_position_excludes_the_seq_minimum_leg():
    persons, trips = _fixture()
    table = T.departure_time_table(persons, trips, np.random.RandomState(2))
    employed = table[table["segment"] == "employed"]
    # "home" is only ever a LATER trip (p2's second trip) in this fixture.
    assert len(employed[(employed["purpose"] == "home") & (employed["position"] == "first")]) == 0
    assert len(employed[(employed["purpose"] == "home") & (employed["position"] == "later")]) == 1
    # "work" is only ever a FIRST trip (p2's and p3's first trip) in this fixture.
    assert len(employed[(employed["purpose"] == "work") & (employed["position"] == "later")]) == 0
    assert len(employed[(employed["purpose"] == "work") & (employed["position"] == "first")]) > 0


def test_bins_beyond_the_28_hour_window_are_clipped_and_counted():
    persons, trips = _fixture()
    table = T.departure_time_table(persons, trips, np.random.RandomState(3))
    assert table["bin_15min"].min() >= 0
    assert table["bin_15min"].max() <= T.N_BINS - 1
    # p3's third trip (2080 min) is the only leg whose raw AND de-rounded bin exceed N_BINS - 1.
    assert table.attrs["n_bins_clipped_as_reported"] == 1
    assert table.attrs["n_bins_clipped_derounded"] == 1
    clipped_row = table[(table["segment"] == "employed") & (table["purpose"] == "other")]
    assert (clipped_row["bin_15min"] == T.N_BINS - 1).all()


def test_invalid_dep_min_is_excluded_from_bins_and_counted():
    persons, trips = _fixture()
    table = T.departure_time_table(persons, trips, np.random.RandomState(4))
    # p2's third trip (dep_min NaN) must not contribute any row (purpose "leisure" never
    # appears), and the exclusion must be counted on the returned table's attrs.
    assert "leisure" not in set(table["purpose"])
    assert table.attrs["n_legs_total"] == 7
    assert table.attrs["n_legs_excluded_invalid_dep_min"] == 1
    assert table.attrs["n_legs_excluded_nan"] == 1
    assert table.attrs["n_legs_excluded_negative"] == 0
    assert table.attrs["n_legs_excluded_non_integer"] == 0


def test_departure_time_table_columns_and_universe():
    persons, trips = _fixture()
    table = T.departure_time_table(persons, trips, np.random.RandomState(5))
    assert list(table.columns) == T.DEPARTURE_TIME_COLUMNS
    assert set(table["universe"]) == {"at_home_zero"}
    assert set(table["position"]) <= set(T.POSITIONS)


def test_departure_time_table_raises_on_a_trip_with_an_unknown_person():
    persons, trips = _fixture()
    trips = pd.concat([trips, pd.DataFrame({
        "pid": ["ghost"], "seq": [1], "weight": [1.0], "purpose": ["work"],
        "prev_purpose": ["home"], "dep_min": [400.0], "arr_min": [420.0],
    })], ignore_index=True)
    with pytest.raises(ValueError, match="not in the person frame"):
        T.departure_time_table(persons, trips, np.random.RandomState(0))


# --------------------------------------------------------------------------- activity_duration_table
def test_activity_duration_excludes_a_25_hour_gap_and_counts_it():
    persons, trips = _fixture()
    table = T.activity_duration_table(persons, trips)
    # p3's shop activity (25 h) must not appear anywhere in the output.
    subset = table[(table["segment"] == "employed") & (table["purpose"] == "shop")]
    assert len(subset) == 0
    assert table.attrs["n_legs_total"] == 7
    assert table.attrs["n_legs_excluded_out_of_range"] == 1
    assert table.attrs["n_legs_excluded_no_next_or_missing_time"] == 4
    assert table.attrs["n_legs_included"] == 2


def test_activity_duration_bands_are_complete_and_sum_to_one():
    persons, trips = _fixture()
    table = T.activity_duration_table(persons, trips)
    subset = table[(table["segment"] == "employed") & (table["purpose"] == "work")]
    assert sorted(subset["band"]) == sorted(T.DURATION_BAND_LABELS)
    assert subset["share"].sum() == pytest.approx(1.0)
    by_band = subset.set_index("band")["share"]
    # p2 trip 1 (weight 1.0, 8.667 h) -> "8h+"; p3 trip 1 (weight 2.0, 0.5 h) -> "0-0.5h".
    assert by_band["8h+"] == pytest.approx(1.0 / 3.0)
    assert by_band["0-0.5h"] == pytest.approx(2.0 / 3.0)
    assert by_band["1-2h"] == pytest.approx(0.0)
    assert int(subset["n_unweighted"].iloc[0]) == 2


def test_activity_duration_table_columns_and_universe():
    persons, trips = _fixture()
    table = T.activity_duration_table(persons, trips)
    assert list(table.columns) == T.ACTIVITY_DURATION_COLUMNS
    assert set(table["universe"]) == {"at_home_zero"}
    # Every (segment, purpose) group with data carries the complete, disjoint band set.
    grouped = table.groupby(["segment", "purpose"])
    assert np.allclose(grouped["share"].sum().values, 1.0)


def test_activity_duration_table_raises_on_a_trip_with_an_unknown_person():
    persons, trips = _fixture()
    trips = pd.concat([trips, pd.DataFrame({
        "pid": ["ghost"], "seq": [1], "weight": [1.0], "purpose": ["work"],
        "prev_purpose": ["home"], "dep_min": [400.0], "arr_min": [420.0],
    })], ignore_index=True)
    with pytest.raises(ValueError, match="not in the person frame"):
        T.activity_duration_table(persons, trips)


# --------------------------------------------------------------------------- committed-file pins
def test_committed_departure_time_reference_is_internally_consistent():
    path = SRV_DIR / T.DEPARTURE_TIME_TABLE
    if not path.exists():
        pytest.skip("committed SrV departure-time reference not present in this checkout")
    table = pd.read_csv(path, comment="#")
    assert list(table.columns) == T.DEPARTURE_TIME_COLUMNS
    assert set(table["universe"]) == {"at_home_zero"}
    assert set(table["position"]) <= set(T.POSITIONS)
    assert table["bin_15min"].between(0, T.N_BINS - 1).all()
    grouped = table.groupby(["segment", "purpose", "position"])
    assert np.allclose(grouped["share_derounded"].sum().values, 1.0, atol=1e-6)
    assert np.allclose(grouped["share_as_reported"].sum().values, 1.0, atol=1e-6)


def test_committed_activity_duration_reference_is_internally_consistent():
    path = SRV_DIR / T.ACTIVITY_DURATION_TABLE
    if not path.exists():
        pytest.skip("committed SrV activity-duration reference not present in this checkout")
    table = pd.read_csv(path, comment="#")
    assert list(table.columns) == T.ACTIVITY_DURATION_COLUMNS
    assert set(table["universe"]) == {"at_home_zero"}
    assert set(table["band"]) <= set(T.DURATION_BAND_LABELS)
    grouped = table.groupby(["segment", "purpose"])
    assert np.allclose(grouped["share"].sum().values, 1.0, atol=1e-6)
