"""Pin tests for the committed SrV 2023 primary-distance target tables (committed CSVs only).

Values are read from the committed CSVs generated by
``scripts/extract_srv_primary_distance_targets.py`` on 2026-09-03 against the local-only
SrV 2023 raw microdata (4,543 work persons, 2,503 education-purpose persons before the
level-mapping filter). They are pins, not re-derivations: a change here signals that the
committed tables changed, not that the extraction is wrong.
"""
from pathlib import Path

import numpy as np
import pytest

from braunschweig.calibration import srv_distance_targets as T

SRV_DIR = Path(__file__).resolve().parents[1] / "eqasim-data" / "data" / "braunschweig" / "srv"


@pytest.fixture(scope="module")
def commute():
    return T.load_commute_targets(SRV_DIR)


@pytest.fixture(scope="module")
def education():
    return T.load_education_targets(SRV_DIR)


@pytest.fixture(scope="module")
def quantiles():
    return T.load_commute_quantiles(SRV_DIR)


def test_commute_rows_and_sources(commute):
    kreis = commute[commute["level_geo"] == "kreis"].set_index("code")
    assert set(kreis.index) == set(T.ZGB_KREISE)
    assert kreis.loc["03103", "source"] == T.PROXY_SOURCE
    assert (kreis.drop("03103")["source"] == "srv").all()
    assert (commute["level_geo"] == "zgb").sum() == 1


def test_commute_shares_sum_to_one(commute):
    for scope in ("all", "inter", "intra"):
        cols = [f"share_{scope}_{lbl}" for lbl in T.WORK_BAND_LABELS]
        assert np.allclose(commute[cols].sum(axis=1), 1.0, atol=1e-6)
        shr = [f"share_{scope}_shrunk_{lbl}" for lbl in T.WORK_BAND_LABELS]
        assert np.allclose(commute[shr].sum(axis=1), 1.0, atol=1e-6)


def test_commute_sample_sizes_are_plausible(commute):
    kreis = commute[(commute["level_geo"] == "kreis") & (commute["source"] == "srv")]
    assert kreis["n_persons"].min() >= 300      # smallest surveyed Kreis: 03102 (Salzgitter), 387
    assert commute[commute["level_geo"] == "zgb"]["n_persons"].iloc[0] >= 4000
    assert (kreis["emd_noise_95_all"] > 0).all()


def test_commute_pinned_values(commute):
    k = commute[commute["level_geo"] == "kreis"].set_index("code")
    # Braunschweig (03101), the largest and most urban surveyed Kreis.
    assert k.loc["03101", "n_persons"] == 1272
    assert k.loc["03101", "share_all_0_5"] == pytest.approx(0.392, abs=0.01)
    assert k.loc["03101", "share_intra"] > k.loc["03151", "share_intra"]  # city vs rural Kreis
    zgb = commute[commute["level_geo"] == "zgb"]
    assert zgb["n_persons"].iloc[0] == 4543
    assert zgb["median_km"].iloc[0] == pytest.approx(10.62, abs=0.05)
    # Ruling R11: the Wolfsburg proxy row copies the RS7-72 pool verbatim -- raw == shrunk.
    assert k.loc["03103", "share_all_shrunk_0_5"] == pytest.approx(k.loc["03103", "share_all_0_5"], abs=1e-9)


def test_education_levels_and_shares(education):
    comp = education[education["comparable"]]
    assert set(comp["education_level"]) == set(T.COMPARABLE_LEVELS)
    assert set(education[~education["comparable"]]["education_level"]) == set(T.DESCRIPTIVE_ONLY_LEVELS)
    cols = [f"share_{lbl}" for lbl in T.EDUCATION_BAND_LABELS]
    nonempty = education[education["n_persons"] > 0]
    assert len(nonempty) > 0
    assert np.allclose(nonempty[cols].sum(axis=1), 1.0, atol=1e-6)
    for level in T.COMPARABLE_LEVELS:
        rows = comp[(comp["education_level"] == level) & (comp["level_geo"] == "kreis")]
        assert set(rows["code"]) == set(T.ZGB_KREISE)


def test_education_pinned_values(education):
    zgb = education[education["level_geo"] == "zgb"]
    kinder = zgb[zgb["education_level"] == "kindergarten"]
    assert kinder["n_persons"].iloc[0] == 647
    assert kinder["share_0_1"].iloc[0] == pytest.approx(0.363, abs=0.01)
    university = zgb[zgb["education_level"] == "university"]
    assert university["n_persons"].iloc[0] == 142
    assert university["mean_km"].iloc[0] == pytest.approx(14.69, abs=0.1)
    # The 7 REALLY surveyed Kreis rows (excluding the Wolfsburg proxy, which duplicates
    # persons already counted under their real, surveyed home Kreis via the RS7-72 pool)
    # sum exactly to the ZGB total.
    kreis_kinder = education[(education["level_geo"] == "kreis") & (education["education_level"] == "kindergarten")]
    real = kreis_kinder[kreis_kinder["code"] != T.WOLFSBURG_KREIS]
    assert real["n_persons"].sum() == 647


def test_quantiles_long_monotone(quantiles):
    assert set(quantiles["code"]) >= set(T.ZGB_KREISE)
    for code, grp in quantiles.groupby("code"):
        g = grp.sort_values("percentile")
        assert list(g["percentile"]) == list(range(1, 100))
        assert np.all(np.diff(g["distance_km_euclid_raw"]) >= -1e-9)
        assert np.all(np.diff(g["distance_km_euclid_shrunk"]) >= -1e-9)


def test_quantiles_pinned_values(quantiles):
    p50_03101 = quantiles[(quantiles["code"] == "03101") & (quantiles["percentile"] == 50)]
    assert p50_03101["distance_km_euclid_raw"].iloc[0] == pytest.approx(5.08, abs=0.05)
    p50_zgb = quantiles[(quantiles["level_geo"] == "zgb") & (quantiles["percentile"] == 50)]
    assert p50_zgb["distance_km_euclid_raw"].iloc[0] == pytest.approx(8.17, abs=0.05)
    # Ruling R11: the Wolfsburg proxy row's shrunk quantile equals its raw quantile at every
    # percentile (the pool is not shrunk further).
    proxy = quantiles[quantiles["code"] == "03103"]
    assert np.allclose(proxy["distance_km_euclid_raw"], proxy["distance_km_euclid_shrunk"])
