"""Tests for the SrV 2023 plan-structure reference builder (plan-structure fix, issue #369).

The logic tests run on a tiny synthetic SrV-SHAPED fixture (raw column names, raw code values)
built in memory -- the real SrV 2023 scientific-use microdata is local-only and must never be a
test dependency. The fixture is small enough that every expected value below is derivable by
hand from the docstring of :func:`_srv_fixture`, which is the point: the metric definitions are
pinned by arithmetic a reviewer can redo, not by numbers copied out of a run.

Pin tests (bottom of the file) read the COMMITTED CSV generated by
``scripts/extract_srv_plan_structure.py`` against the local-only raw microdata and pin real
values -- a change there signals that the committed table changed, not that the extraction logic
is wrong. They skip (never silently pass) when the committed file is absent.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from braunschweig.calibration import srv_plan_structure as T

BRAUNSCHWEIG_KREIS = "03101"
SALZGITTER_KREIS = "03102"
BRAUNSCHWEIG_AGS = "03101015"
SALZGITTER_AGS = "03102000"


def _srv_fixture():
    """3 households in 2 Kreise, 7 raw persons (6 surviving harmonisation), 11 raw trips (10
    surviving harmonisation).

    Persons (weight = GEWICHT_P_ZENSUS):

    ==========  =====  ======  ===============================================================
    person      kreis  weight  reporting day
    ==========  =====  ======  ===============================================================
    1_1         03101     2.0  closed commuter H->W->H, 2 trips (pattern "HWH")
    1_2         03101     1.0  H->W->W->H, 3 trips, the work->work repeat (V_ZWECK 1 then 2)
    2_1         03102     1.0  away from home (E_ANZ_WEGE == -7), 0 trips
    2_2         03102     1.0  at home all day (E_ANZ_WEGE == 0), 0 trips
    3_1         03102     1.0  open-ended day H->S->L->?, 3 trips, last purpose unknown (-10)
    3_2         03102     1.0  child H->E->H, 2 trips
    3_3         03102    -9.0  DROPPED: negative weight; its single trip is dropped with it
    ==========  =====  ======  ===============================================================

    Derivable expectations (weighted, universe "at_home_zero", segment "all"):

    * total weight 7.0, mobile weight 5.0 (persons 1_1, 1_2, 3_1, 3_2) -> mobility_rate 5/7,
      which differs from the unweighted 4/6 -- so the assertion actually tests the weighting.
    * trips: 2*2 + 3 + 3 + 2 = 12 weighted person-trips over weight 7 -> trips_per_person 12/7.
    * 10 harmonised trips, exactly one of them (person 1_2 trip 1) is followed by a trip with
      the same harmonised purpose -> share_trips_followed_by_same_purpose = 1/10.
    * 9 of the 10 trips carry a known purpose (work 3, home 3, shop 1, leisure 1, education 1)
      -> purpose_share_work = 3/9, share_trips_unknown_purpose = 1/10.
    * universe "at_home_only" drops person 2_1 -> 5 persons, weight 6.0, mobility_rate 5/6.
    """
    persons = pd.DataFrame({
        "HHNR": [1, 1, 2, 2, 3, 3, 3],
        "PNR": [1, 2, 1, 2, 1, 2, 3],
        "V_ALTER": [40, 35, 50, 70, 20, 10, 30],
        "V_ERW": [9, 10, 9, 3, 3, 6, 9],
        "V_GESCHLECHT": [1, 2, 1, 2, 2, 1, 1],
        "E_ANZ_WEGE": [2, 3, -7, 0, 3, 2, 1],
        "E_ANZ_WEGE2": [2, 3, 0, 0, 3, 2, 1],
        "GEWICHT_P_ZENSUS": [2.0, 1.0, 1.0, 1.0, 1.0, 1.0, -9.0],
        "STICHTAG_WTAG": [2, 3, 4, 2, 3, 4, 2],
        "GEWICHT_P_WERKTAG": [-6.0] * 7,
    })
    trips = pd.DataFrame({
        "HHNR": [1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3],
        "PNR": [1, 1, 2, 2, 2, 1, 1, 1, 2, 2, 3],
        "WNR": [1, 2, 1, 2, 3, 1, 2, 3, 1, 2, 1],
        "V_ZWECK": [1, 19, 1, 2, 19, 8, 13, -10, 3, 19, 1],
        "E_START_ZWECK": [19, 1, 19, 1, 2, 19, 8, 13, 19, 3, 19],
        "E_BEGINN": [480, 1020, 450, 600, 960, 540, 600, 700, 420, 780, 500],
        "E_ANKUNFT": [510, 1050, 480, 610, 990, 555, 620, 720, 440, 800, 520],
        "GEWICHT_W_ZENSUS": [1.0] * 11,
    })
    households = pd.DataFrame({
        "HHNR": [1, 2, 3],
        "AGS": [BRAUNSCHWEIG_AGS, SALZGITTER_AGS, SALZGITTER_AGS],
    })
    return persons, trips, households


def _harmonised():
    return T.harmonise_srv(*_srv_fixture())


# --------------------------------------------------------------------------- harmonisation
def test_harmonise_drops_negative_weight_persons_and_their_trips():
    persons, trips = _harmonised()
    assert len(persons) == 6
    assert "3_3" not in set(persons["pid"])
    assert len(trips) == 10
    assert "3_3" not in set(trips["pid"])


def test_harmonise_maps_purposes_and_keeps_unknown_separate():
    _, trips = _harmonised()
    by_seq = trips.set_index(["pid", "seq"])["purpose"]
    assert by_seq[("1_1", 1)] == "work"                # V_ZWECK 1
    assert by_seq[("1_2", 2)] == "work"                # V_ZWECK 2 maps to the same class
    assert by_seq[("1_1", 2)] == "home"                # V_ZWECK 19
    assert by_seq[("3_1", 1)] == "shop"                # V_ZWECK 8
    assert by_seq[("3_1", 2)] == "leisure"             # V_ZWECK 13
    assert by_seq[("3_1", 3)] == T.UNKNOWN_PURPOSE     # V_ZWECK -10
    assert by_seq[("3_2", 1)] == "education"           # V_ZWECK 3
    prev = trips.set_index(["pid", "seq"])["prev_purpose"]
    assert prev[("1_2", 3)] == "work"                  # E_START_ZWECK 2


def test_harmonise_person_attributes():
    persons, _ = _harmonised()
    p = persons.set_index("pid")
    assert bool(p.loc["1_1", "employed"]) and bool(p.loc["1_2", "employed"])
    assert not bool(p.loc["3_2", "employed"])          # V_ERW 6 (in education) is not employed
    assert p.loc["1_1", "kreis"] == BRAUNSCHWEIG_KREIS
    assert p.loc["3_1", "kreis"] == SALZGITTER_KREIS
    assert p.loc["1_1", "age_band"] == "25-44"
    assert p.loc["3_2", "age_band"] == "10-17"
    assert p.loc["1_1", "sex"] == "male" and p.loc["1_2", "sex"] == "female"
    assert bool(p.loc["2_1", "away_from_home"]) and not bool(p.loc["2_2", "away_from_home"])
    assert p.loc["2_1", "n_trips"] == 0                # E_ANZ_WEGE2 counts an away day as 0
    assert p.loc["1_2", "group"] == "employed"
    assert p.loc["3_2", "group"] == "school_age_6_17_not_employed"
    assert p.loc["3_1", "group"] == "adult_18_64_not_employed"
    assert p.loc["2_2", "group"] == "senior_65plus_not_employed"


def test_harmonisation_diagnostics_counts_are_on_their_stated_universes():
    """The three universes the diagnostics keys mix (raw rows, weight-filtered trips, harmonised
    frames) must not be confused: the raw counts include the dropped person 3_3 and its trip,
    n_trips_person_dropped is measured on the trips surviving the trip-weight filter, and the
    quality counts are measured on the harmonised universe."""
    raw_persons, raw_trips, households = _srv_fixture()
    persons, trips = T.harmonise_srv(raw_persons, raw_trips, households)
    diagnostics = T.harmonisation_diagnostics(raw_persons, raw_trips, persons, trips)

    assert diagnostics["n_persons_raw"] == 7
    assert diagnostics["n_persons_negative_weight"] == 1          # person 3_3
    assert diagnostics["n_persons_universe"] == 6
    assert diagnostics["n_persons_away_from_home"] == 1           # person 2_1
    assert diagnostics["n_persons_missing_age"] == 0
    assert diagnostics["n_persons_unmapped_sex"] == 0
    assert diagnostics["n_persons_no_kreis"] == 0
    assert diagnostics["n_trips_raw"] == 11
    assert diagnostics["n_trips_negative_weight"] == 0            # no negative trip weight here
    assert diagnostics["n_trips_person_dropped"] == 1             # the trip of person 3_3
    assert diagnostics["n_trips_universe"] == 10
    assert diagnostics["n_trips_unknown_purpose"] == 1            # V_ZWECK -10 of person 3_1
    assert diagnostics["n_trips_unknown_prev_purpose"] == 0
    assert diagnostics["n_trips_invalid_departure_time"] == 0
    assert diagnostics["n_trips_invalid_arrival_time"] == 0


def test_harmonise_raises_on_foreign_weekday():
    persons, trips, households = _srv_fixture()
    persons.loc[0, "STICHTAG_WTAG"] = 1                # Monday: outside the delivered Tue-Thu
    with pytest.raises(ValueError, match="STICHTAG_WTAG"):
        T.harmonise_srv(persons, trips, households)


def test_harmonise_raises_on_unexpected_weekday_weight():
    persons, trips, households = _srv_fixture()
    persons.loc[0, "GEWICHT_P_WERKTAG"] = 1.5
    with pytest.raises(ValueError, match="GEWICHT_P_WERKTAG"):
        T.harmonise_srv(persons, trips, households)


# --------------------------------------------------------------------------- person level
def test_person_level_pattern_and_structure():
    persons, trips = _harmonised()
    per = T.person_level(persons, trips).set_index("pid")
    assert per.loc["1_1", "pattern"] == "HWH"          # closed commuter
    assert per.loc["1_2", "pattern"] == "HWWH"
    assert per.loc["2_1", "pattern"] == "H"            # no trips reported
    assert bool(per.loc["1_1", "first_from_home"]) and bool(per.loc["1_1", "last_to_home"])
    assert not bool(per.loc["3_1", "last_to_home"])    # open-ended day
    assert per.loc["1_1", "n_work"] == 1 and per.loc["1_2", "n_work"] == 2
    assert per.loc["1_1", "n_home_returns"] == 1
    assert bool(per.loc["1_1", "mobile"]) and not bool(per.loc["2_1", "mobile"])
    assert per.loc["3_1", "n_trips"] == 3


def test_person_level_raises_on_a_trip_without_a_person():
    # a left merge would silently drop such a trip and shrink every trip-level metric
    persons, trips = _harmonised()
    with pytest.raises(ValueError, match="not in the person frame"):
        T.person_level(persons[persons["pid"] != "1_1"], trips)


def test_person_level_raises_when_reported_trip_count_disagrees():
    persons, trips = _harmonised()
    persons = persons.copy()
    persons.loc[persons["pid"] == "1_1", "n_trips"] = 5  # E_ANZ_WEGE2 no longer matches the file
    with pytest.raises(ValueError, match="trip count"):
        T.person_level(persons, trips)


# --------------------------------------------------------------------------- segment metrics
def test_segment_metrics_headline_values_are_weighted():
    persons, trips = _harmonised()
    per = T.person_level(persons, trips)
    m = T.segment_metrics(per, trips, "all")
    assert m["segment"] == "all"
    assert m["n_persons_unweighted"] == 6
    assert m["n_persons_weighted"] == pytest.approx(7.0)
    assert m["mobility_rate"] == pytest.approx(5.0 / 7.0)      # unweighted would be 4/6
    assert m["trips_per_person"] == pytest.approx(12.0 / 7.0)
    assert m["trips_per_mobile_person"] == pytest.approx(12.0 / 5.0)
    assert m["participation_work"] == pytest.approx(3.0 / 7.0)
    assert m["share_trips_0"] == pytest.approx(2.0 / 7.0)
    assert m["share_trips_2"] == pytest.approx(3.0 / 7.0)
    assert m["share_trips_3"] == pytest.approx(2.0 / 7.0)


def test_segment_metrics_trip_structure_values():
    persons, trips = _harmonised()
    per = T.person_level(persons, trips)
    m = T.segment_metrics(per, trips, "all")
    assert m["share_trips_followed_by_same_purpose"] == pytest.approx(1.0 / 10.0)
    assert m["share_trips_unknown_purpose"] == pytest.approx(1.0 / 10.0)
    assert m["purpose_share_work"] == pytest.approx(3.0 / 9.0)
    assert m["purpose_share_home"] == pytest.approx(3.0 / 9.0)
    assert sum(m["purpose_share_%s" % p] for p in T.PURPOSES) == pytest.approx(1.0)
    # mobile persons 1_1 (2 trips) and 3_2 (2 trips) are even, 1_2 and 3_1 (3 trips) are odd
    assert m["share_mobile_odd_trip_count"] == pytest.approx(2.0 / 5.0)
    assert m["share_mobile_last_to_home"] == pytest.approx(4.0 / 5.0)
    # home returns among mobile persons: 1_1 one (weight 2), 1_2 one, 3_2 one, 3_1 none
    assert m["tours_per_mobile"] == pytest.approx(4.0 / 5.0)


def test_segment_metrics_work_activity_and_departure_hours():
    persons, trips = _harmonised()
    per = T.person_level(persons, trips)
    m = T.segment_metrics(per, trips, "all")
    # work activities: 1_1 arr 510 -> next dep 1020 = 8.5 h; 1_2 arr 480 -> 600 = 2.0 h;
    # 1_2 arr 610 -> 960 = 5.8333 h. The 2.0 h activity is NOT below 2 h (strict <).
    assert m["mean_work_activity_h"] == pytest.approx((8.5 + 2.0 + 350.0 / 60.0) / 3.0)
    assert m["share_work_activities_lt_2h"] == pytest.approx(0.0)
    # work departures are at minute 480 (hour 8), 450 (hour 7) and 600 (hour 10)
    assert m["dep_hour_share_work_8"] == pytest.approx(1.0 / 3.0)
    assert m["dep_hour_share_work_7"] == pytest.approx(1.0 / 3.0)
    assert m["dep_hour_share_work_10"] == pytest.approx(1.0 / 3.0)


def test_segment_metrics_empty_segment_is_all_nan_not_an_error():
    persons, trips = _harmonised()
    per = T.person_level(persons, trips)
    m = T.segment_metrics(per.iloc[0:0], trips, "age_75+")
    assert m["n_persons_unweighted"] == 0
    assert np.isnan(m["mobility_rate"])
    assert np.isnan(m["purpose_share_work"])


# --------------------------------------------------------------------------- reference table
def test_build_reference_universes_differ_in_the_away_person():
    persons, trips = _harmonised()
    zero = T.build_reference(persons, trips, universe=T.UNIVERSE_AT_HOME_ZERO)
    only = T.build_reference(persons, trips, universe=T.UNIVERSE_AT_HOME_ONLY)

    def value(df, metric, segment="all"):
        row = df[(df["segment"] == segment) & (df["metric"] == metric)]
        assert len(row) == 1, "%s not unique in segment %s" % (metric, segment)
        return float(row["value"].iloc[0])

    assert set(zero["universe"]) == {T.UNIVERSE_AT_HOME_ZERO}
    assert value(zero, "n_persons_unweighted") == 6
    assert value(only, "n_persons_unweighted") == 5
    assert int(zero[zero["segment"] == "all"]["n_unweighted"].iloc[0]) == 6
    assert int(only[only["segment"] == "all"]["n_unweighted"].iloc[0]) == 5
    assert value(zero, "mobility_rate") == pytest.approx(5.0 / 7.0)
    assert value(only, "mobility_rate") == pytest.approx(5.0 / 6.0)


def test_build_reference_contains_every_expected_segment():
    persons, trips = _harmonised()
    table = T.build_reference(persons, trips, universe=T.UNIVERSE_AT_HOME_ZERO)
    segments = set(table["segment"])
    assert "all" in segments
    assert {"age_%s" % b for b in T.AGE_LABELS} <= segments
    assert {"group_%s" % g for g in T.GROUPS} <= segments
    assert {"sex_male", "sex_female"} <= segments
    assert {"kreis_%s" % BRAUNSCHWEIG_KREIS, "kreis_%s" % SALZGITTER_KREIS} <= segments
    assert list(table.columns) == ["universe", "segment", "metric", "value", "n_unweighted"]
    # every segment carries the same metric set (a long table with holes would break Task 10)
    per_segment = table.groupby("segment")["metric"].apply(set)
    assert all(s == per_segment.iloc[0] for s in per_segment)


def test_build_reference_rejects_an_unknown_universe():
    persons, trips = _harmonised()
    with pytest.raises(ValueError, match="universe"):
        T.build_reference(persons, trips, universe="everybody")


# --------------------------------------------------------------------------------------------
# Pin tests: real values from the committed CSV (generated by
# scripts/extract_srv_plan_structure.py against the local-only SrV 2023 raw microdata).
# Values are pins, not re-derivations: a change here signals that the committed table changed,
# not that the extraction logic is wrong.
# --------------------------------------------------------------------------------------------
SRV_DIR = Path(__file__).resolve().parents[1] / "eqasim-data" / "data" / "braunschweig" / "srv"


@pytest.fixture(scope="module")
def committed_table():
    """The committed reference table, or a SKIP naming the file.

    The path is gitignored-with-an-allowlist, so a checkout without it must skip loudly rather
    than let the pins below pass vacuously on an empty frame.
    """
    path = SRV_DIR / T.PLAN_STRUCTURE_TABLE
    if not path.exists():
        pytest.skip("committed plan-structure reference missing: %s (regenerate with "
                    "scripts/extract_srv_plan_structure.py against the local-only SrV raw)"
                    % path)
    table = T.load_plan_structure_reference(SRV_DIR)
    assert len(table) > 0, "committed plan-structure reference is empty: %s" % path
    return table


def _committed_value(table, universe, metric, segment="all"):
    row = table[(table["universe"] == universe) & (table["segment"] == segment)
                & (table["metric"] == metric)]
    assert len(row) == 1, "%s/%s/%s is not a single row" % (universe, segment, metric)
    return float(row["value"].iloc[0])


def test_committed_table_shape_and_columns(committed_table):
    assert list(committed_table.columns) == T.REFERENCE_COLUMNS
    assert set(committed_table["universe"]) == set(T.UNIVERSES)
    assert committed_table["segment"].nunique() == 23      # all + 8 age + 5 group + 2 sex + 7 kreis
    assert len(committed_table) == 9476


def test_committed_at_home_zero_pinned_values(committed_table):
    assert _committed_value(committed_table, T.UNIVERSE_AT_HOME_ZERO,
                            "n_persons_unweighted") == 18223
    assert _committed_value(committed_table, T.UNIVERSE_AT_HOME_ZERO,
                            "mobility_rate") == pytest.approx(0.8437, abs=0.001)
    assert _committed_value(committed_table, T.UNIVERSE_AT_HOME_ZERO,
                            "trips_per_person") == pytest.approx(3.1865, abs=0.001)
    assert _committed_value(committed_table, T.UNIVERSE_AT_HOME_ZERO,
                            "participation_work") == pytest.approx(0.3316, abs=0.001)
    assert _committed_value(committed_table, T.UNIVERSE_AT_HOME_ZERO,
                            "participation_shop") == pytest.approx(0.2794, abs=0.001)
    assert _committed_value(committed_table, T.UNIVERSE_AT_HOME_ZERO,
                            "participation_leisure") == pytest.approx(0.3832, abs=0.001)


def test_committed_at_home_only_pinned_values(committed_table):
    assert _committed_value(committed_table, T.UNIVERSE_AT_HOME_ONLY,
                            "n_persons_unweighted") == 17269
    assert _committed_value(committed_table, T.UNIVERSE_AT_HOME_ONLY,
                            "mobility_rate") == pytest.approx(0.8879, abs=0.001)


def test_committed_purpose_shares_sum_to_one(committed_table):
    shares = committed_table[committed_table["metric"].isin(
        ["purpose_share_%s" % purpose for purpose in T.PURPOSES])]
    totals = shares.groupby(["universe", "segment"])["value"].sum()
    populated = totals[totals.notna() & (totals != 0.0)]
    assert len(populated) > 0
    assert np.allclose(populated.values, 1.0, atol=1e-6)
