"""Tests for the SrV 2023 departure-time and activity-duration reference builder (issue #123,
Phase 0 Task 2; fix round 1, review ruling A-R9/A-R10).

The logic tests run on tiny, hand-built HARMONISED fixtures (the schema produced by
``srv_plan_structure.harmonise_srv``, not the raw SrV column names) -- the real SrV 2023
scientific-use microdata is local-only and must never be a test dependency. Every expected value
below is derivable by hand from the docstrings of :func:`_fixture` and :func:`_unknown_purpose_fixture`.

Pin test at the bottom reads the COMMITTED CSVs generated by
``scripts/extract_srv_departure_times.py`` against the local-only raw microdata and only checks
structural invariants (never numeric pins from a run) -- it skips (never silently passes) when the
committed files are absent.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from braunschweig.calibration import srv_departure_times as T
from braunschweig.calibration import srv_plan_structure as SRV

REPO = Path(__file__).resolve().parents[1]
SRV_DIR = REPO / "eqasim-data" / "data" / "braunschweig" / "srv"


def _fixture():
    """3 persons, 7 trips (6 with a valid ``dep_min``), in the HARMONISED schema.

    ==== ============================== ====== ============================================
    pid  group                          weight reporting day
    ==== ============================== ====== ============================================
    p1   school_age_6_17_not_employed   3.0    one trip, 7:00 (420 min) to education
    p2   employed                       1.0    work@8:00 (480), home@17:00 (1020), then a
                                                trip with an unrecorded ("keine Angabe")
                                                departure time (dep_min/arr_min NaN)
    p3   employed                       2.0    work@8:30 (510), shop@9:20 (560), then a trip
                                                at 2080 min (34:40 -- past the 28 h window)
    ==== ============================== ====== ============================================

    Derivable expectations:

    * ``p2``'s third trip has ``dep_min`` NaN and is the ONLY invalid leg -> 6/7 legs valid,
      1 excluded (NaN).
    * ``p1``'s single trip is a quarter-hour report (420 % 15 == 0, half-width 7.5 min), so its
      de-rounded value lies in [412.5, 427.5) and its 15-minute bin is 27 (412.5/15 = 27.5) or 28
      (420/15 = 28.0 exactly), never 26 or 29.
    * segment "employed", purpose "work", position "first": ``p2`` trip 1 (weight 1.0, bin 32)
      and ``p3`` trip 1 (weight 2.0, bin 34) -> two bins, shares summing to 1.0 over weight 3.0.
    * segment "employed", purpose "home", position "later": only ``p2`` trip 2 (weight 1.0,
      1020 min, bin 68, no clipping) -> "home" never appears under position "first" (no one's
      first trip is a return home) and "work" never appears under "later" (neither ``p2`` nor
      ``p3`` has a later trip to work) -- this is the "later excludes seq-min legs" check.
    * ``p3``'s third trip departs at 2080 min (138.7 quarter-hours), whose raw AND de-rounded bin
      (138, clipped to 111) both exceed ``N_BINS - 1`` -> exactly 1 of the 6 valid legs is
      clipped in each of ``share_as_reported`` / ``share_derounded``.
    * Activity durations (next ``dep_min`` minus ``arr_min`` within the pid): ``p1`` trip 1 and
      ``p2`` trip 3 and ``p3`` trip 3 have no following trip (excluded, "no next"); ``p2`` trip 2
      has no next EITHER (its only following trip has a NaN ``dep_min``, also "no next"); ``p2``
      trip 1 -> (1020 - 500) / 60 = 8.667 h ("8h+"); ``p3`` trip 1 -> (560 - 530) / 60 = 0.5 h
      ("0-0.5h"); ``p3`` trip 2 -> (2080 - 580) / 60 = 25.0 h, OUTSIDE [0, 20] h -> EXCLUDED and
      counted. So of 7 trips: 4 have no measurable next activity, 1 is measured but out of range,
      2 are included (segment "employed", purpose "work": bands "0-0.5h" share 2/3, "8h+" 1/3).
    * No person in this fixture has an unknown-purpose leg -- see :func:`_unknown_purpose_fixture`
      for that case.
    """
    persons = pd.DataFrame({
        "pid": ["p1", "p2", "p3"],
        "weight": [3.0, 1.0, 2.0],
        "group": ["school_age_6_17_not_employed", "employed", "employed"],
    })
    trips = pd.DataFrame({
        "pid":          ["p1", "p2", "p2", "p2", "p3", "p3", "p3"],
        "seq":          [1, 1, 2, 3, 1, 2, 3],
        "weight":       [3.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0],
        "purpose":      ["education", "work", "home", "leisure", "work", "shop", "other"],
        "prev_purpose": ["home", "home", "work", "home", "home", "work", "shop"],
        "dep_min":      [420.0, 480.0, 1020.0, np.nan, 510.0, 560.0, 2080.0],
        "arr_min":      [450.0, 500.0, 1040.0, np.nan, 530.0, 580.0, 2100.0],
    })
    return persons, trips


def _unknown_purpose_fixture():
    """2 persons, 4 trips, one of them an UNKNOWN-purpose destination (ruling A-R10).

    ==== ============================== ====== ================================================
    pid  group                          weight reporting day
    ==== ============================== ====== ================================================
    u1   employed                       1.0    work@8:00 (480, arr 500, first), UNKNOWN@10:00
                                                (600, arr 620, later), home@10:50 (650, later)
    u2   employed                       1.0    shop@8:20 (500, arr 520, first, no next trip)
    ==== ============================== ====== ================================================

    Derivable expectations:

    * ``u1``'s second trip (unknown destination purpose, valid dep_min=600) must NEVER appear
      under a NAMED purpose (segment "employed" position "later" purpose "home" has exactly 1
      leg -- ``u1`` trip 3 -- summed n_unweighted across every NAMED purpose at position "later"
      is 1, not 2) but MUST appear in the pooled ``purpose == "all"`` cell (segment "employed"
      position "later" purpose "all" has n_unweighted == 2: the unknown trip plus the home trip).
    * Activity duration: ``u1`` trip 1 (work, arr 500) -> next dep 600 -> 1.667 h ("1-2h"),
      NAMED purpose "work". ``u1`` trip 2 (unknown, arr 620) -> next dep 650 -> 0.5 h ("0-0.5h"),
      MEASURABLE and in-range, so it is EXCLUDED from every named-purpose duration cell but
      INCLUDED in the pooled purpose "all" cell for segment "employed" (2 legs: work + unknown,
      weight 1.0 each -> "1-2h" share 0.5, "0-0.5h" share 0.5). ``u1`` trip 3 (home) and ``u2``
      trip 1 (shop) both have no following trip -> excluded, "no next".
    """
    persons = pd.DataFrame({
        "pid": ["u1", "u2"],
        "weight": [1.0, 1.0],
        "group": ["employed", "employed"],
    })
    trips = pd.DataFrame({
        "pid":          ["u1", "u1", "u1", "u2"],
        "seq":          [1, 2, 3, 1],
        "weight":       [1.0, 1.0, 1.0, 1.0],
        "purpose":      ["work", SRV.UNKNOWN_PURPOSE, "home", "shop"],
        "prev_purpose": ["home", "work", SRV.UNKNOWN_PURPOSE, "home"],
        "dep_min":      [480.0, 600.0, 650.0, 500.0],
        "arr_min":      [500.0, 620.0, 670.0, 520.0],
    })
    return persons, trips


def _n_unweighted(table: pd.DataFrame, segment: str, purpose: str, position: str) -> int:
    """The (repeated) n_unweighted value of one departure-time cell (0 if the cell is absent,
    which should never happen now that the table is dense -- callers assert on this too)."""
    row = table[(table["segment"] == segment) & (table["purpose"] == purpose)
               & (table["position"] == position)]
    assert len(row) == T.N_BINS, "departure_time_table must be dense: expected %d rows, found %d" \
        % (T.N_BINS, len(row))
    values = row["n_unweighted"].unique()
    assert len(values) == 1, "n_unweighted must be constant within one cell, found %s" % values
    return int(values[0])


# --------------------------------------------------------------------------- departure_time_table
def test_departure_time_table_is_dense_over_all_bins_and_purposes():
    persons, trips = _fixture()
    table = T.departure_time_table(persons, trips, np.random.RandomState(6))
    assert len(table) == len(T.SEGMENTS) * len(T.PURPOSES_WITH_ALL) * len(T.POSITIONS) * T.N_BINS
    counts = table.groupby(["segment", "purpose", "position"]).size()
    assert (counts == T.N_BINS).all()
    assert set(table["purpose"]) == set(T.PURPOSES_WITH_ALL)


def test_departure_time_table_empty_cell_is_emitted_with_nan_shares_never_dropped():
    persons, trips = _fixture()
    table = T.departure_time_table(persons, trips, np.random.RandomState(7))
    # p1 (segment "school_age_6_17_not_employed") has a single trip, purpose "education" -- the
    # "work" purpose cell for this segment has zero contributing legs.
    empty = table[(table["segment"] == "school_age_6_17_not_employed")
                  & (table["purpose"] == "work") & (table["position"] == "first")]
    assert len(empty) == T.N_BINS
    assert (empty["n_unweighted"] == 0).all()
    assert empty["share_derounded"].isna().all()
    assert empty["share_as_reported"].isna().all()


def test_first_trip_derounded_bin_stays_within_the_reporting_cell():
    # A 7:00 (420 min) quarter-hour report de-rounds to [412.5, 427.5), which can only ever land
    # in 15-minute bin 27 or 28 -- never 26 (< 412.5) or 29 (>= 427.5), for ANY offset drawn.
    persons, trips = _fixture()
    table = T.departure_time_table(persons, trips, np.random.RandomState(0))
    subset = table[(table["segment"] == "school_age_6_17_not_employed")
                   & (table["purpose"] == "education") & (table["position"] == "first")]
    assert len(subset) == T.N_BINS
    nonzero_derounded = subset[subset["share_derounded"] > 0]
    assert set(nonzero_derounded["bin_15min"]) <= {27, 28}
    assert subset.loc[subset["bin_15min"].isin([26, 29]), "share_derounded"].sum() == 0.0
    assert subset["share_derounded"].sum() == pytest.approx(1.0)
    assert subset["share_as_reported"].sum() == pytest.approx(1.0)
    # The as-reported time is exact (420 / 15 = 28.0), so its bin is always 28.
    assert subset.loc[subset["bin_15min"] == 28, "share_as_reported"].iloc[0] == pytest.approx(1.0)


def test_shares_sum_to_one_per_segment_purpose_position():
    persons, trips = _fixture()
    table = T.departure_time_table(persons, trips, np.random.RandomState(1))
    subset = table[(table["segment"] == "employed") & (table["purpose"] == "work")
                   & (table["position"] == "first")]
    assert len(subset) == T.N_BINS
    nonzero = subset[subset["share_as_reported"] > 0]
    assert len(nonzero) == 2   # p2 trip 1 (bin 32) and p3 trip 1 (bin 34)
    assert subset["share_derounded"].sum() == pytest.approx(1.0)
    assert subset["share_as_reported"].sum() == pytest.approx(1.0)
    assert int(subset["n_unweighted"].iloc[0]) == 2

    # Invariant must hold for every NON-EMPTY (segment, purpose, position) triple in the table
    # (an empty cell's shares are NaN by design and must not be forced into this check).
    non_empty = table[table["n_unweighted"] > 0]
    grouped = non_empty.groupby(["segment", "purpose", "position"])
    assert np.allclose(grouped["share_derounded"].sum().values, 1.0)
    assert np.allclose(grouped["share_as_reported"].sum().values, 1.0)


def test_pooled_purpose_all_exists_and_sums_to_one():
    persons, trips = _fixture()
    table = T.departure_time_table(persons, trips, np.random.RandomState(8))
    subset = table[(table["segment"] == "all") & (table["purpose"] == T.PURPOSE_ALL)
                   & (table["position"] == "first")]
    assert len(subset) == T.N_BINS
    # Every person's first trip: p1 (education, w 3.0), p2 trip 1 (work, w 1.0),
    # p3 trip 1 (work, w 2.0) -> 3 legs, total weight 6.0.
    assert int(subset["n_unweighted"].iloc[0]) == 3
    assert subset["share_derounded"].sum() == pytest.approx(1.0)
    assert subset["share_as_reported"].sum() == pytest.approx(1.0)


def test_later_position_excludes_the_seq_minimum_leg():
    persons, trips = _fixture()
    table = T.departure_time_table(persons, trips, np.random.RandomState(2))
    assert _n_unweighted(table, "employed", "home", "first") == 0
    assert _n_unweighted(table, "employed", "home", "later") == 1
    assert _n_unweighted(table, "employed", "work", "later") == 0
    assert _n_unweighted(table, "employed", "work", "first") == 2


def test_bins_beyond_the_28_hour_window_are_clipped_and_counted():
    persons, trips = _fixture()
    table = T.departure_time_table(persons, trips, np.random.RandomState(3))
    assert table["bin_15min"].min() == 0
    assert table["bin_15min"].max() == T.N_BINS - 1
    assert table.attrs["n_bins_clipped_as_reported"] == 1
    assert table.attrs["n_bins_clipped_derounded"] == 1
    clipped = table[(table["segment"] == "employed") & (table["purpose"] == "other")
                    & (table["position"] == "later")]
    nonzero = clipped[clipped["share_as_reported"] > 0]
    assert (nonzero["bin_15min"] == T.N_BINS - 1).all()


def test_invalid_dep_min_is_excluded_from_bins_and_counted():
    persons, trips = _fixture()
    table = T.departure_time_table(persons, trips, np.random.RandomState(4))
    # p2's third trip (dep_min NaN, purpose "leisure") must contribute to no cell -- the
    # "leisure" purpose column still exists (the table is dense over purposes too), but every
    # "leisure" cell must be empty.
    leisure = table[table["purpose"] == "leisure"]
    assert (leisure["n_unweighted"] == 0).all()
    assert leisure["share_derounded"].isna().all()
    assert table.attrs["n_legs_total"] == 7
    assert table.attrs["n_legs_excluded_invalid_dep_min"] == 1
    assert table.attrs["n_legs_excluded_nan"] == 1
    assert table.attrs["n_legs_excluded_negative"] == 0
    assert table.attrs["n_legs_excluded_non_integer"] == 0


def test_unknown_purpose_excluded_from_named_cells_and_pooled_under_all():
    persons, trips = _unknown_purpose_fixture()
    table = T.departure_time_table(persons, trips, np.random.RandomState(9))
    assert SRV.UNKNOWN_PURPOSE not in set(table["purpose"])
    # Only u1's home trip (later) is a NAMED-purpose "later" leg for segment "employed"; summed
    # across every named purpose it must be 1, while the pooled purpose "all" sees BOTH the
    # unknown-purpose leg and the home leg (n_unweighted 2).
    named_later_total = sum(_n_unweighted(table, "employed", purpose, "later")
                            for purpose in SRV.PURPOSES)
    assert named_later_total == 1
    assert _n_unweighted(table, "employed", T.PURPOSE_ALL, "later") == 2
    assert table.attrs["n_legs_unknown_purpose_raw"] == 1
    assert table.attrs["n_legs_unknown_purpose_valid_dep_min"] == 1


def test_departure_time_table_columns_and_universe():
    persons, trips = _fixture()
    table = T.departure_time_table(persons, trips, np.random.RandomState(5))
    assert list(table.columns) == T.DEPARTURE_TIME_COLUMNS
    assert set(table["universe"]) == {"at_home_zero"}
    assert set(table["position"]) <= set(T.POSITIONS)
    assert T.PURPOSE_ALL in set(table["purpose"])


def test_departure_time_table_raises_on_a_trip_with_an_unknown_person():
    persons, trips = _fixture()
    trips = pd.concat([trips, pd.DataFrame({
        "pid": ["ghost"], "seq": [1], "weight": [1.0], "purpose": ["work"],
        "prev_purpose": ["home"], "dep_min": [400.0], "arr_min": [420.0],
    })], ignore_index=True)
    with pytest.raises(ValueError, match="not in the person frame"):
        T.departure_time_table(persons, trips, np.random.RandomState(0))


def test_departure_time_table_raises_on_an_unrecognised_group():
    persons = pd.DataFrame({"pid": ["x1"], "weight": [1.0], "group": ["not_a_real_group"]})
    trips = pd.DataFrame({"pid": ["x1"], "seq": [1], "weight": [1.0], "purpose": ["work"],
                          "prev_purpose": ["home"], "dep_min": [480.0], "arr_min": [500.0]})
    with pytest.raises(ValueError, match="not_a_real_group"):
        T.departure_time_table(persons, trips, np.random.RandomState(0))


# --------------------------------------------------------------------------- activity_duration_table
def test_activity_duration_excludes_a_25_hour_gap_and_counts_it():
    persons, trips = _fixture()
    table = T.activity_duration_table(persons, trips)
    # p3's shop activity (25 h) must not appear anywhere in the output.
    subset = table[(table["segment"] == "employed") & (table["purpose"] == "shop")]
    assert len(subset) == 0
    assert table.attrs["n_legs_total"] == 7
    assert table.attrs["n_legs_excluded_out_of_range"] == 1
    assert table.attrs["n_legs_excluded_no_next_or_missing_time"] == 4
    assert table.attrs["n_legs_included"] == 2


def test_activity_duration_bands_are_complete_and_sum_to_one():
    persons, trips = _fixture()
    table = T.activity_duration_table(persons, trips)
    subset = table[(table["segment"] == "employed") & (table["purpose"] == "work")]
    assert sorted(subset["band"]) == sorted(T.DURATION_BAND_LABELS)
    assert subset["share"].sum() == pytest.approx(1.0)
    by_band = subset.set_index("band")["share"]
    # p2 trip 1 (weight 1.0, 8.667 h) -> "8h+"; p3 trip 1 (weight 2.0, 0.5 h) -> "0-0.5h".
    assert by_band["8h+"] == pytest.approx(1.0 / 3.0)
    assert by_band["0-0.5h"] == pytest.approx(2.0 / 3.0)
    assert by_band["1-2h"] == pytest.approx(0.0)
    assert int(subset["n_unweighted"].iloc[0]) == 2


def test_activity_duration_pooled_purpose_all_sums_to_one():
    persons, trips = _fixture()
    table = T.activity_duration_table(persons, trips)
    subset = table[(table["segment"] == "employed") & (table["purpose"] == T.PURPOSE_ALL)]
    assert sorted(subset["band"]) == sorted(T.DURATION_BAND_LABELS)
    assert subset["share"].sum() == pytest.approx(1.0)
    assert int(subset["n_unweighted"].iloc[0]) == 2   # the same 2 legs as the "work" cell here


def test_activity_duration_unknown_purpose_excluded_from_named_and_pooled_under_all():
    persons, trips = _unknown_purpose_fixture()
    table = T.activity_duration_table(persons, trips)
    assert SRV.UNKNOWN_PURPOSE not in set(table["purpose"])
    work = table[(table["segment"] == "employed") & (table["purpose"] == "work")]
    assert int(work["n_unweighted"].iloc[0]) == 1
    by_band_work = work.set_index("band")["share"]
    assert by_band_work["1-2h"] == pytest.approx(1.0)

    pooled = table[(table["segment"] == "employed") & (table["purpose"] == T.PURPOSE_ALL)]
    assert int(pooled["n_unweighted"].iloc[0]) == 2   # work leg + the unknown-purpose leg
    by_band_pooled = pooled.set_index("band")["share"]
    assert by_band_pooled["1-2h"] == pytest.approx(0.5)
    assert by_band_pooled["0-0.5h"] == pytest.approx(0.5)
    assert table.attrs["n_legs_unknown_purpose_raw"] == 1
    assert table.attrs["n_legs_unknown_purpose_included"] == 1


def test_activity_duration_table_columns_and_universe():
    persons, trips = _fixture()
    table = T.activity_duration_table(persons, trips)
    assert list(table.columns) == T.ACTIVITY_DURATION_COLUMNS
    assert set(table["universe"]) == {"at_home_zero"}
    assert T.PURPOSE_ALL in set(table["purpose"])
    # Every (segment, purpose) group with data carries the complete, disjoint band set.
    grouped = table.groupby(["segment", "purpose"])
    assert np.allclose(grouped["share"].sum().values, 1.0)


def test_activity_duration_table_raises_on_a_trip_with_an_unknown_person():
    persons, trips = _fixture()
    trips = pd.concat([trips, pd.DataFrame({
        "pid": ["ghost"], "seq": [1], "weight": [1.0], "purpose": ["work"],
        "prev_purpose": ["home"], "dep_min": [400.0], "arr_min": [420.0],
    })], ignore_index=True)
    with pytest.raises(ValueError, match="not in the person frame"):
        T.activity_duration_table(persons, trips)


# --------------------------------------------------------------------------- committed-file pins
def test_committed_departure_time_reference_is_internally_consistent():
    path = SRV_DIR / T.DEPARTURE_TIME_TABLE
    if not path.exists():
        pytest.skip("committed SrV departure-time reference not present in this checkout")
    table = pd.read_csv(path, comment="#")
    assert list(table.columns) == T.DEPARTURE_TIME_COLUMNS
    assert set(table["universe"]) == {"at_home_zero"}
    assert set(table["position"]) <= set(T.POSITIONS)
    assert set(table["purpose"]) == set(T.PURPOSES_WITH_ALL)
    assert table["bin_15min"].between(0, T.N_BINS - 1).all()
    counts = table.groupby(["segment", "purpose", "position"]).size()
    assert (counts == T.N_BINS).all()
    non_empty = table[table["n_unweighted"] > 0]
    grouped = non_empty.groupby(["segment", "purpose", "position"])
    assert np.allclose(grouped["share_derounded"].sum().values, 1.0, atol=1e-6)
    assert np.allclose(grouped["share_as_reported"].sum().values, 1.0, atol=1e-6)


def test_committed_activity_duration_reference_is_internally_consistent():
    path = SRV_DIR / T.ACTIVITY_DURATION_TABLE
    if not path.exists():
        pytest.skip("committed SrV activity-duration reference not present in this checkout")
    table = pd.read_csv(path, comment="#")
    assert list(table.columns) == T.ACTIVITY_DURATION_COLUMNS
    assert set(table["universe"]) == {"at_home_zero"}
    assert set(table["band"]) <= set(T.DURATION_BAND_LABELS)
    assert T.PURPOSE_ALL in set(table["purpose"])
    grouped = table.groupby(["segment", "purpose"])
    assert np.allclose(grouped["share"].sum().values, 1.0, atol=1e-6)
