"""Tests for the SrV 2023 work-participation reference per Kreis (spec 2026-09-04, issue #244).

Synthetic-frame tests exercise
``braunschweig.calibration.srv_work_participation.build_srv_work_participation_table`` directly
with small in-memory frames (no raw SrV microdata required). Pin tests (bottom of the file) read
the committed CSV generated by ``scripts/extract_srv_work_participation.py`` against the
local-only SrV 2023 raw microdata and pin real values -- a change there signals that the
committed table changed, not that the extraction logic is wrong.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from braunschweig.calibration import srv_work_participation as T
from braunschweig.calibration.srv_distance_targets import WOLFSBURG_KREIS, ZGB_KREISE

SRV_DIR = Path(__file__).resolve().parents[1] / "eqasim-data" / "data" / "braunschweig" / "srv"

# Kreis codes used by the synthetic fixture below (Braunschweig and Gifhorn; canonical
# code-to-name mapping: braunschweig.analysis.spatial.ZGB8 -- 03101 Braunschweig, 03151 Gifhorn).
BRAUNSCHWEIG_KREIS = "03101"
GIFHORN_KREIS = "03151"
BRAUNSCHWEIG_AGS = "03101015"
GIFHORN_AGS = "03151001"


def _two_kreis_fixture():
    """4 employed persons in Braunschweig (1 home-office day, 2 with a work trip, 1 neither),
    2 employed persons in Gifhorn (1 work trip, 1 neither), plus five persons who must
    each be excluded from the universe for a different reason:

    - HHNR 7: ``V_WOHNUNG_HO == -8`` (not asked / not employed).
    - HHNR 8: ``V_WOHNUNG_HO == -10`` (no answer).
    - HHNR 9: ``MITTL_WERKTAG != 1`` (not an average-weekday person), despite an otherwise
      valid ``V_WOHNUNG_HO == 1`` that would count as a home-office day if the filter were
      missing.
    - HHNR 10: negative ``GEWICHT_P_ZENSUS``.
    - HHNR 11: ``NaN`` ``GEWICHT_P_ZENSUS``.

    All five exclusion cases are placed in the SAME household (Braunschweig AGS) as the four
    genuine Braunschweig persons, so if any exclusion filter were broken, the Braunschweig
    row's ``n_persons`` and shares would silently shift away from the expected 4 / 0.25 / 0.5 /
    0.25 -- the assertions below therefore exercise the filters, not just the happy path.
    """
    persons = pd.DataFrame({
        "HHNR":            [1, 2, 3, 4, 7, 8, 9, 10, 11, 5, 6],
        "PNR":             [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        "V_WOHNUNG_HO":    [1, 2, 2, 2, -8, -10, 1, 2, 2, 2, 2],
        "GEWICHT_P_ZENSUS": [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, np.nan, 1.0, 1.0],
        "MITTL_WERKTAG":   [1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1],
    })
    trips = pd.DataFrame({
        "HHNR":    [2, 3, 4, 1, 5, 6],
        "PNR":     [1, 1, 1, 1, 1, 1],
        "V_ZWECK": [1, 1, 2, 2, 1, 2],  # only V_ZWECK == 1 ("Arbeit") counts as a work trip
    })
    households = pd.DataFrame({
        "HHNR": [1, 2, 3, 4, 7, 8, 9, 10, 11, 5, 6],
        "AGS": [BRAUNSCHWEIG_AGS] * 9 + [GIFHORN_AGS] * 2,
    })
    return persons, trips, households


def test_braunschweig_kreis_shares_and_n_persons():
    persons, trips, households = _two_kreis_fixture()
    table = T.build_srv_work_participation_table(persons, trips, households)

    row = table[(table["level"] == "kreis") & (table["code"] == BRAUNSCHWEIG_KREIS)].iloc[0]
    assert row["n_persons"] == 4
    assert row["share_home_office_day"] == pytest.approx(0.25)
    assert row["share_work_trip"] == pytest.approx(0.5)
    assert row["share_neither"] == pytest.approx(0.25)


def test_gifhorn_kreis_shares_and_n_persons():
    persons, trips, households = _two_kreis_fixture()
    table = T.build_srv_work_participation_table(persons, trips, households)

    row = table[(table["level"] == "kreis") & (table["code"] == GIFHORN_KREIS)].iloc[0]
    assert row["n_persons"] == 2
    assert row["share_home_office_day"] == pytest.approx(0.0)
    assert row["share_work_trip"] == pytest.approx(0.5)
    assert row["share_neither"] == pytest.approx(0.5)


def test_zgb_row_totals_over_universe_persons_only():
    persons, trips, households = _two_kreis_fixture()
    table = T.build_srv_work_participation_table(persons, trips, households)

    zgb_rows = table[table["level"] == "zgb"]
    assert len(zgb_rows) == 1
    row = zgb_rows.iloc[0]
    assert row["code"] == "zgb"
    # Only the 4 + 2 = 6 genuine universe persons; the five exclusion cases (-8, -10, not an
    # average weekday, negative weight, NaN weight) must not leak into the zgb total.
    assert row["n_persons"] == 6
    assert row["share_home_office_day"] + row["share_work_trip"] + row["share_neither"] == pytest.approx(1.0)


def test_all_zgb_kreise_present_including_wolfsburg_with_zero_persons():
    """Exactly one row per code in ZGB_KREISE (8 Kreise) plus one zgb row. Wolfsburg (03103) is
    not surveyed by SrV and has zero persons in the synthetic fixture -- its row must still be
    emitted, with n_persons == 0 and NaN shares (never silently dropped or backfilled)."""
    persons, trips, households = _two_kreis_fixture()
    table = T.build_srv_work_participation_table(persons, trips, households)

    kreis_rows = table[table["level"] == "kreis"]
    assert set(kreis_rows["code"]) == set(ZGB_KREISE)
    assert len(table) == len(ZGB_KREISE) + 1

    wolfsburg = kreis_rows[kreis_rows["code"] == WOLFSBURG_KREIS].iloc[0]
    assert wolfsburg["n_persons"] == 0
    assert np.isnan(wolfsburg["share_home_office_day"])
    assert np.isnan(wolfsburg["share_work_trip"])
    assert np.isnan(wolfsburg["share_neither"])


def test_shares_sum_to_one_for_every_nonempty_row():
    persons, trips, households = _two_kreis_fixture()
    table = T.build_srv_work_participation_table(persons, trips, households)

    nonempty = table[table["n_persons"] > 0]
    totals = nonempty["share_home_office_day"] + nonempty["share_work_trip"] + nonempty["share_neither"]
    assert np.allclose(totals, 1.0, atol=1e-9)


def test_diagnostics_dict_on_two_kreis_fixture():
    """build_srv_work_participation (the tuple-returning function) must report the exact
    exclusion counts of the fixture: 11 input persons, 1 dropped for not being an
    average-weekday person (HHNR 9), 1 for -8 (HHNR 7), 1 for -10 (HHNR 8), 2 for an
    invalid weight (HHNR 10 negative, HHNR 11 NaN), 0 household-resolution or outside-ZGB
    drops (all households in this fixture carry a valid, in-ZGB AGS), leaving n_universe == 6
    -- the same 4 + 2 persons the table-level tests above already pin."""
    persons, trips, households = _two_kreis_fixture()
    table, diagnostics = T.build_srv_work_participation(persons, trips, households)

    assert diagnostics["n_persons_total"] == 11
    assert diagnostics["n_not_average_weekday"] == 1
    assert diagnostics["n_not_asked_minus8"] == 1
    assert diagnostics["n_no_answer_minus10"] == 1
    assert diagnostics["n_invalid_weight"] == 2
    assert diagnostics["n_no_household"] == 0
    assert diagnostics["n_invalid_ags"] == 0
    assert diagnostics["n_outside_zgb"] == 0
    assert diagnostics["n_universe"] == 6
    assert diagnostics["n_both_home_office_and_work_trip"] == 0
    assert len(table) == len(ZGB_KREISE) + 1


def test_table_only_wrapper_matches_tuple_function():
    persons, trips, households = _two_kreis_fixture()
    table_only = T.build_srv_work_participation_table(persons, trips, households)
    table_tuple, _ = T.build_srv_work_participation(persons, trips, households)
    pd.testing.assert_frame_equal(table_only, table_tuple)


def test_household_resolution_exclusions_are_counted_separately():
    """A sentinel/invalid household AGS (n_invalid_ags) and a person whose HHNR has NO
    matching row in the households frame at all (n_no_household) are different exclusion
    reasons (ruling R8 fix round) and must be counted separately, not conflated into one
    dropped count."""
    persons = pd.DataFrame({
        "HHNR": [1, 2, 20, 21],
        "PNR": [1, 1, 1, 1],
        "V_WOHNUNG_HO": [2, 2, 2, 2],
        "GEWICHT_P_ZENSUS": [1.0, 1.0, 1.0, 1.0],
        "MITTL_WERKTAG": [1, 1, 1, 1],
    })
    trips = pd.DataFrame({"HHNR": [999], "PNR": [1], "V_ZWECK": [1]})  # no trips for these persons
    households = pd.DataFrame({
        "HHNR": [1, 2, 20],  # HHNR 21 has NO matching household row at all -> n_no_household
        "AGS": [BRAUNSCHWEIG_AGS, BRAUNSCHWEIG_AGS, "-9"],  # HHNR 20's AGS is a sentinel value
    })

    table, diagnostics = T.build_srv_work_participation(persons, trips, households)
    assert diagnostics["n_no_household"] == 1
    assert diagnostics["n_invalid_ags"] == 1
    assert diagnostics["n_universe"] == 2  # only HHNR 1, 2 survive

    row = table[(table["level"] == "kreis") & (table["code"] == BRAUNSCHWEIG_KREIS)].iloc[0]
    assert row["n_persons"] == 2


def test_home_office_day_with_a_work_trip_is_classed_as_home_office():
    """A person with BOTH a full home-office day (V_WOHNUNG_HO == 1) and a work trip
    (V_ZWECK == 1) is classed home_office, not work_trip -- share_home_office_day counts
    V_WOHNUNG_HO == 1 regardless of trip activity; share_work_trip only applies to persons
    who did NOT report a home-office day. Uses an isolated one-person fixture so this
    combination cannot be confused with the clean 4-person Braunschweig fixture above."""
    persons = pd.DataFrame({
        "HHNR": [100], "PNR": [1], "V_WOHNUNG_HO": [1], "GEWICHT_P_ZENSUS": [2.5], "MITTL_WERKTAG": [1],
    })
    trips = pd.DataFrame({"HHNR": [100], "PNR": [1], "V_ZWECK": [1]})
    households = pd.DataFrame({"HHNR": [100], "AGS": [BRAUNSCHWEIG_AGS]})

    table = T.build_srv_work_participation_table(persons, trips, households)
    row = table[(table["level"] == "kreis") & (table["code"] == BRAUNSCHWEIG_KREIS)].iloc[0]
    assert row["n_persons"] == 1
    assert row["share_home_office_day"] == pytest.approx(1.0)
    assert row["share_work_trip"] == pytest.approx(0.0)
    assert row["share_neither"] == pytest.approx(0.0)


def test_loader_raises_file_not_found_with_regeneration_hint(tmp_path):
    with pytest.raises(FileNotFoundError, match="extract_srv_work_participation.py"):
        T.load_srv_work_participation(tmp_path)


# --------------------------------------------------------------------------------------------
# Pin tests: real values from the committed CSV (generated by
# scripts/extract_srv_work_participation.py against the local-only SrV 2023 raw microdata).
# Values are pins, not re-derivations: a change here signals that the committed table changed,
# not that the extraction is wrong.
# --------------------------------------------------------------------------------------------

@pytest.fixture(scope="module")
def committed_table():
    return T.load_srv_work_participation(SRV_DIR)


def test_committed_table_rows_and_codes(committed_table):
    kreis_rows = committed_table[committed_table["level"] == "kreis"]
    assert set(kreis_rows["code"]) == set(ZGB_KREISE)
    assert (committed_table["level"] == "zgb").sum() == 1


def test_committed_wolfsburg_row_is_zero(committed_table):
    row = committed_table[(committed_table["level"] == "kreis")
                          & (committed_table["code"] == WOLFSBURG_KREIS)].iloc[0]
    assert row["n_persons"] == 0
    assert np.isnan(row["share_home_office_day"])


def test_committed_shares_sum_to_one(committed_table):
    nonempty = committed_table[committed_table["n_persons"] > 0]
    totals = (nonempty["share_home_office_day"] + nonempty["share_work_trip"]
              + nonempty["share_neither"])
    assert np.allclose(totals, 1.0, atol=1e-6)


def test_committed_zgb_pinned_values(committed_table):
    zgb = committed_table[committed_table["level"] == "zgb"].iloc[0]
    assert zgb["n_persons"] == 8016
    assert zgb["share_home_office_day"] == pytest.approx(0.1418, abs=0.001)
    assert zgb["share_work_trip"] == pytest.approx(0.6511, abs=0.001)
    assert zgb["share_neither"] == pytest.approx(0.2071, abs=0.001)


def test_committed_braunschweig_kreis_pinned_values(committed_table):
    row = committed_table[(committed_table["level"] == "kreis")
                          & (committed_table["code"] == BRAUNSCHWEIG_KREIS)].iloc[0]
    assert row["n_persons"] == 2268
    assert row["share_home_office_day"] == pytest.approx(0.1781, abs=0.001)
