"""Compose a launchable config YAML from a template + curated overrides.

Every GUI launch writes a NAMED file next to the templates (never invisible
GUI-only state). Template comments are not preserved (PyYAML round-trip);
instead a provenance header records template, git commit, timestamp and
every override old -> new, which is the information that matters for
traceability."""
from __future__ import annotations

import re
from datetime import datetime

import yaml

from .collectors.config_inspect import diff as config_diff

_LABEL_RE = re.compile(r"[^A-Za-z0-9._-]+")


def compose(template_yaml: str, overrides: dict, *, label: str, template_name: str,
            git_commit: str, now_iso: str) -> tuple[str, str]:
    changes = config_diff(template_yaml, overrides)
    doc = yaml.safe_load(template_yaml)
    for c in changes:
        doc["config"][c["key"]] = c["new"]

    ts = datetime.fromisoformat(now_iso).strftime("%Y%m%d_%H%M%S")
    safe_label = _LABEL_RE.sub("-", label).strip("-")
    fname = f"config_gui_{safe_label}_{ts}.yml"

    header_lines = [
        f"## {fname} -- generated by braunschweig.runcontrol (issue #119).",
        f"## template: {template_name}",
        f"## git commit at compose time: {git_commit}",
        f"## composed at: {now_iso}",
    ]
    if changes:
        header_lines.append("## overrides vs template:")
        header_lines += [f"##   {c['key']}: {c['old']} -> {c['new']}" for c in changes]
    else:
        header_lines.append("## overrides vs template: none")
    header_lines.append("## NOTE: template comments are not carried over; consult the template for rationale.")

    body = yaml.safe_dump(doc, sort_keys=False, default_flow_style=False, allow_unicode=False)
    return fname, "\n".join(header_lines) + "\n\n" + body
