"""Extract the MiD 2023 reporting-day work-location reference tables (run on the run server).

Raw MiD 2023 microdata (SUF, comma-separated) lives ONLY on the run server under
``eqasim-data/data/braunschweig/popsim/mid2023_raw/``. This script reads the person and trip
files and writes two small aggregates with provenance headers:

    mid2023_workday_location_by_commute_distance.csv   (spec 2026-09-04 Section 2.1)
    mid2023_home_office_donor_pool.csv                  (spec Section 2.2)

Usage (felix, conda env eqasim, from the repository/worktree root):
    python scripts/extract_mid_workday_location.py --raw eqasim-data/data/braunschweig/popsim/mid2023_raw \
        --out-dir eqasim-data/data/braunschweig/mid --source-commit <short sha of this checkout>

``--source-commit`` records the eqasim-bs commit whose
``braunschweig/calibration/commute_day_state_reference.py`` produced the committed files (ruling
R7: committed CSVs must be traceable to an exact code state); pass the local ``git rev-parse
--short HEAD`` of the checkout the script is run from.
"""
from __future__ import annotations

import argparse
import datetime as dt
import logging
import sys
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from braunschweig.calibration import commute_day_state_reference as R  # noqa: E402

PERSON_COLUMNS = ["HP_ID", "H_ID", "P_GEW", "arbwo", "M_HOFF", "P_STARB1", "starb2", "P_ARB_ENTF",
                  "HP_ALTER", "HP_SEX"]
TRIP_COLUMNS = ["HP_ID", "W_ZWECK"]

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
logger = logging.getLogger("extract_mid_workday_location")

# Distances (km) at which MiD respondents' self-reported P_ARB_ENTF heaps on round numbers; used
# only for the header disclosure below (ruling R6), never for classification.
_ROUND_KM_HEAPING_POINTS = (10.0, 100.0, 200.0)


def _heaping_disclosure_stats(persons: pd.DataFrame) -> dict:
    """Measure MiD self-report heaping on round-number distances, for the header disclosure.

    Ruling R6: the earlier controller scan used a right-inclusive ``(a, b]`` binning convention;
    ``classify_commute_distance`` (used by both committed tables) is left-inclusive ``[a, b)``.
    Because MiD respondents disproportionately round P_ARB_ENTF to multiples of 5 (and especially
    to the class boundaries 10/25/50/100 km), class-level unweighted COUNTS shift materially
    between the two conventions even though the underlying population is identical; the
    P_GEW-weighted STATE shares barely move, because heaping persons are not a distinctive
    sub-population with respect to reporting-day work location. This helper recomputes the
    relevant counts directly from the current extraction so the header always states measured
    facts about the data it was generated from, not a value carried over from an earlier scan.
    """
    universe = R._mid_universe(persons)
    distance_km = R.clean_mid_commute_distance_km(universe["P_ARB_ENTF"])
    valid = distance_km.dropna()
    n_valid = int(len(valid))
    n_exact = {km: int((valid == km).sum()) for km in _ROUND_KM_HEAPING_POINTS}
    share_multiple_of_5 = float(((valid % 5.0).abs() < 1e-9).mean()) if n_valid else float("nan")
    return {"n_valid": n_valid, "n_exact": n_exact, "share_multiple_of_5": share_multiple_of_5}


def _header(table: str, source_commit: str, extra: list[str]) -> list[str]:
    """Shared provenance header lines, true for BOTH committed tables, plus table-specific ``extra``.

    Ruling R4/R5/R6/R7: every statement here must hold for both
    ``mid2023_workday_location_by_commute_distance.csv`` and ``mid2023_home_office_donor_pool.csv``
    -- a fact true of only one table (e.g. the workday table's ``n_missing_distance`` column, or
    the donor pool's ``missing``/``gt200`` rows) belongs in that table's own ``extra`` lines
    instead (see ``main``).
    """
    return [
        "# Source: MiD 2023 scientific-use microdata (SUF B1, infas/DLR/IVT/infas 360), server-only raw",
        f"#   files MiD2023_Personen.csv / MiD2023_Wege.csv; generated by scripts/extract_mid_workday_location.py on {dt.date.today().isoformat()}.",
        f"# Code state (ruling R7): eqasim-bs {source_commit}, module braunschweig/calibration/commute_day_state_reference.py.",
        f"# Table: {table}",
        "# Universe (ruling R4): arbwo == 1 (reporting day is a weekday) AND M_HOFF == 1 (asked the",
        "#   home-office module) AND P_STARB1 in (1, 2, 9) (worked / did not work / no answer). The",
        "#   module/weekday filter alone still keeps ~100k not-applicable, filter-coded persons",
        "#   (P_STARB1 codes such as 202/206/402/404/407 mean 'not employed'/'not asked'); the",
        "#   P_STARB1 filter removes them -- see _mid_universe in commute_day_state_reference.py.",
        "# States (ruling R4): did_not_work = P_STARB1 == 2; missing = P_STARB1 == 9 (no answer) or",
        "#   an unmapped starb2 code (e.g. 99) among P_STARB1 == 1 workers; at_workplace = P_STARB1",
        "#   == 1 & starb2 == 2; at_home = P_STARB1 == 1 & starb2 == 1; other_place = P_STARB1 == 1",
        "#   & starb2 in (3, 4, 5, 96).",
        "# Weight: P_GEW (person weight). Distance: P_ARB_ENTF (ruling R5) cleaned by",
        "#   clean_mid_commute_distance_km in the module -- codes 996, 999 and every value >= 1000",
        "#   (MiD filter/skip codes, e.g. 2202/2206/4402/4404/4407) become missing; 200.0 is a",
        "#   legitimate top-code, classed 100_200.",
        "# Classes (km): lt10 [0,10), 10_25, 25_50, 50_100, 100_200 (incl. the 200 top-code); gt200",
        "#   cannot occur in MiD (the 200 km top-code always classes as 100_200); the donor-pool",
        "#   table additionally emits a 'missing' distance_class row for invalid/absent P_ARB_ENTF.",
        "# Bin convention & heaping (ruling R6): classes are LEFT-INCLUSIVE [a, b) (e.g. 10_25 is",
        "#   [10, 25)), chosen by convention (spec wording, continuous model distances) and applied",
        "#   IDENTICALLY on the donor (this table) and the model side. MiD self-reported P_ARB_ENTF",
        "#   heaps on round numbers: counts and shares are both convention-sensitive -- class COUNTS",
        "#   strongly (e.g. lt10 moves between 19,100 and 21,259 persons depending on the convention),",
        "#   P_GEW-weighted class SHARES by up to the measured maximum absolute deviation -- see the",
        "#   per-table stats below, measured on THIS extraction.",
        "# Purpose: reference for the commute-day-state model (spec 2026-09-04); NOT a control target.",
    ] + [f"# {line}" for line in extra]


def _write(df: pd.DataFrame, path: Path, header: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as fh:
        for line in header:
            fh.write(line + "\n")
        df.to_csv(fh, index=False, lineterminator="\n", float_format="%.10g")
    logger.info("wrote %s (%d rows)", path, len(df))


def _require_columns(path: Path, required_columns: list[str]) -> None:
    """Fail early (before the full read) if ``path``'s header is missing a required column.

    Reads only the header row (``nrows=0``) so this check is cheap even for the multi-hundred-
    thousand-row MiD files.
    """
    header_only = pd.read_csv(path, nrows=0)
    missing = [column for column in required_columns if column not in header_only.columns]
    if missing:
        raise ValueError(f"Required column(s) missing from {path}: {missing}. Available columns: "
                          f"{list(header_only.columns)}")


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--raw", required=True, help="directory with MiD2023_Personen.csv and MiD2023_Wege.csv")
    parser.add_argument("--out-dir", default=str(REPO / "eqasim-data" / "data" / "braunschweig" / "mid"))
    parser.add_argument("--source-commit", required=True,
                         help="short git SHA of the eqasim-bs commit this run's code state corresponds to "
                              "(e.g. `git rev-parse --short HEAD` of the checkout running this script); "
                              "recorded verbatim in the output headers (ruling R7).")
    args = parser.parse_args(argv)
    raw = Path(args.raw)
    person_file = raw / "MiD2023_Personen.csv"
    trip_file = raw / "MiD2023_Wege.csv"
    for path in (person_file, trip_file):
        if not path.exists():
            raise FileNotFoundError(f"MiD raw file missing: {path}")
    _require_columns(person_file, PERSON_COLUMNS)
    _require_columns(trip_file, TRIP_COLUMNS)
    persons = pd.read_csv(person_file, usecols=PERSON_COLUMNS, low_memory=False)
    trips = pd.read_csv(trip_file, usecols=TRIP_COLUMNS, low_memory=False)
    logger.info("read %d persons, %d trips", len(persons), len(trips))

    heaping = _heaping_disclosure_stats(persons)
    logger.info("%s heaping disclosure: %d valid distances, exact-km counts %s, %.1f%% multiples of 5",
                "[commute day state reference]", heaping["n_valid"], heaping["n_exact"],
                100.0 * heaping["share_multiple_of_5"])

    # Finding 2 (whole-branch review): the earlier "weighted state shares agree within 0.005
    # between the two binning conventions" claim was hand-typed from an ad-hoc scan, not
    # reproducible from any committed file. R.measure_bin_convention_deviation recomputes the
    # workday-location table a SECOND time with right-inclusive bins on THIS extraction and
    # returns the actually measured maximum deviation plus both conventions' class counts, so the
    # header states a number this script itself just derived (CLAUDE.md "No invented reference
    # values").
    bin_deviation = R.measure_bin_convention_deviation(persons)
    logger.info("%s bin-convention deviation: max abs share deviation %.4f", "[commute day state reference]",
                bin_deviation["max_abs_share_deviation"])

    out = Path(args.out_dir)

    table = R.build_mid_workday_location_table(persons)
    n_missing_distance_all = int(table.loc[table["distance_class"] == "all", "n_missing_distance"].iloc[0])
    n_lt10 = int(table.loc[table["distance_class"] == "lt10", "n_unweighted"].iloc[0])
    n_100_200 = int(table.loc[table["distance_class"] == "100_200", "n_unweighted"].iloc[0])
    right_n = bin_deviation["right_inclusive_n_unweighted"]
    right_lt10 = int(right_n.get("lt10", 0))
    right_100_200 = int(right_n.get("100_200", 0))
    workday_extra = [
        "Columns: distance_class, n_unweighted, n_missing_distance (all row only), share_at_workplace,",
        "share_at_home, share_did_not_work, share_other_place, share_missing (weighted row shares, sum 1).",
        "Invalid/absent P_ARB_ENTF distances are counted in n_missing_distance (all row only, "
        f"{n_missing_distance_all} persons in this extraction) and excluded from the per-class rows.",
        f"Heaping (measured on this extraction): {heaping['n_exact'][10.0]} persons report exactly 10 km, "
        f"{heaping['n_exact'][100.0]} report exactly 100 km, {heaping['n_exact'][200.0]} report exactly "
        f"the 200 km top-code (a substantial part of the thin 100_200 class, {n_100_200} persons here); "
        f"{100.0 * heaping['share_multiple_of_5']:.1f}% of valid distances are multiples of 5.",
        f"Bin-convention deviation (measured on this extraction by rebuilding this table a second time "
        f"with right-inclusive (a, b] bins -- see measure_bin_convention_deviation in the module): "
        f"BOTH counts and shares are convention-sensitive. Right-inclusive class counts are lt10 "
        f"{right_lt10} (committed, left-inclusive: {n_lt10}), 100_200 {right_100_200} (committed: "
        f"{n_100_200}) -- a strong, material shift. The weighted state shares move by a smaller but "
        f"non-negligible amount: the maximum absolute deviation of any share column between the two "
        f"conventions on THIS extraction is {bin_deviation['max_abs_share_deviation']:.4f}.",
    ]
    _write(table, out / R.WORKDAY_LOCATION_TABLE, _header(R.WORKDAY_LOCATION_TABLE, args.source_commit, workday_extra))

    pool = R.build_mid_home_office_donor_pool(persons, trips)
    missing_row = pool[(pool["distance_class"] == "missing") & (pool["has_children"] == "all")
                        & (pool["has_active_escort"] == "all")]
    n_missing_distance_pool = int(missing_row["n_donors"].iloc[0]) if len(missing_row) else 0
    pool_extra = [
        "Pool: weekday module persons who worked (P_STARB1 == 1) at home (starb2 == 1).",
        "has_children = any household member aged <= 13; has_active_escort = any trip with W_ZWECK == 6",
        "(Bringen/Holen); 'all' marks totals. n_mobile = donors with >= 1 trip; mean_trips_mobile over them;",
        "share_female weighted by P_GEW. Purpose: cell-size diagnostics for the home-office plan donor matching.",
        f"Invalid/absent P_ARB_ENTF donors form a separate 'missing' distance_class row "
        f"({n_missing_distance_pool} donors in this extraction); gt200 rows are emitted with zero counts "
        "because the MiD 200 km top-code makes gt200 impossible for this pool too.",
    ]
    _write(pool, out / R.HOME_OFFICE_DONOR_POOL_TABLE, _header(R.HOME_OFFICE_DONOR_POOL_TABLE, args.source_commit, pool_extra))
    return 0


if __name__ == "__main__":
    sys.exit(main())
