"""Extract committed SrV 2023 distance-distribution targets for the primary activities.

Reads the LOCAL-ONLY SrV 2023 "Braunschweig und RGB" scientific-use microdata (trips,
persons, households; cp1252, semicolon, decimal comma) and writes three small aggregate
tables to ``--out-dir`` (default ``eqasim-data/data/braunschweig/srv``):

    srv2023_commute_distance_by_kreis.csv
    srv2023_education_distance_by_kreis_level.csv
    srv2023_commute_distance_quantiles_by_kreis.csv

Definitions live in ``braunschweig.calibration.srv_distance_targets`` (person-level
observation, GIS-routed length only, GEWICHT_W_ZENSUS, shrinkage n/(n+k), Wolfsburg =
RS7-72 pool). Every table carries a provenance header.

Usage (eqasim env, from a worktree; point --raw at the main checkout's raw directory):
    python scripts/extract_srv_primary_distance_targets.py \
        --raw C:/Users/bienzeisler/Documents/GitHub/eqasim-bs/eqasim-data/data/braunschweig/srv/srv2023_raw \
        --out-dir eqasim-data/data/braunschweig/srv
"""
from __future__ import annotations

import argparse
import datetime as dt
import logging
import sys
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from braunschweig.calibration import srv_distance_targets as T  # noqa: E402

RAW_DEFAULT = REPO / "eqasim-data" / "data" / "braunschweig" / "srv" / "srv2023_raw"
OUT_DEFAULT = REPO / "eqasim-data" / "data" / "braunschweig" / "srv"
CSV_READ_KWARGS = dict(sep=";", decimal=",", encoding="cp1252", low_memory=False)
TRIP_COLUMNS = ["HHNR", "PNR", "WNR", "V_ZWECK", "E_START_ZWECK", "V_START_LAGE", "V_ZIEL_LAGE",
                "V_START_AGS", "V_ZIEL_AGS", "GIS_LAENGE", "GIS_LAENGE_GUELTIG", "GEWICHT_W_ZENSUS",
                "REGIOSTAR7", "STICHTAG_WTAG"]

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
logger = logging.getLogger("extract_srv_primary_distance_targets")


def _header(table_name: str, universe: str, extra: list[str], logs: dict) -> list[str]:
    lines = [
        "# Source: SrV 2023 Braunschweig + Regionalverband Grossraum Braunschweig scientific-use",
        "#   microdata (local-only, see srv2023_raw/README.md), generated by",
        f"#   scripts/extract_srv_primary_distance_targets.py on {dt.date.today().isoformat()}.",
        f"# Table: {table_name}",
        f"# Universe: {universe}",
        "# Observation unit: PERSON -- first home->purpose trip (V_START_LAGE == 1), else first",
        "#   purpose->home trip (V_ZIEL_LAGE == 1); business trips (V_ZWECK 2) and 'andere",
        "#   Bildungseinrichtung' (V_ZWECK 7) excluded. Reporting days are Tue-Thu only.",
        "# Distance: GIS_LAENGE (routed km) where GIS_LAENGE_GUELTIG > 0; GIS-invalid trips fall",
        "#   back to the other direction (R5); a negative weight or an over-cap distance on the",
        "#   SELECTED trip excludes the person (R6, no fallback -- see the module docstring).",
        "# Weight: GEWICHT_W_ZENSUS >= 0 (expansion to Zensus 2022; the stratum-internal",
        "#   GEWICHT_W must not be used across strata; GEWICHT_W_WERKTAG is undefined here).",
        "# Kreis: first 5 digits of the household AGS. Wolfsburg (03103) is NOT surveyed: its row",
        "#   is the RegioStaR-7 type-72 pool (Braunschweig + Salzgitter), source = proxy_rs7_72",
        "#   -- an ASSUMPTION recorded in the reference ADR. Per R11, the Wolfsburg proxy row",
        "#   carries the RS7-72 pool's RAW shares/quantiles in BOTH the raw and the shrunk",
        "#   columns (a pool is not shrunk further).",
        "# Shrinkage: share_*_shrunk = n/(n+k) * Kreis + k/(n+k) * pool, pool = dominant RS7 type",
        f"#   (itself shrunk toward ZGB), k = {T.DEFAULT_PRIOR_STRENGTH:.0f} persons.",
        "# Coverage caveat: stratified PSU design over ~44 selected municipalities; per-Kreis rows",
        "#   represent the covered municipalities (ASSUMPTION-grade for the full Kreis).",
        "# Noise floor: emd_noise_95_* is the 95th percentile of the bootstrap EMD, normalised to",
        "#   [0, 1] exactly like braunschweig.calibration.metrics.emd_on_bands (same formula,",
        "#   re-implemented locally to avoid a pipeline import).",
    ] + [f"# {line}" for line in extra] + [
        "# Exclusions: " + ", ".join(f"{k}={v}" for k, v in logs.items()),
    ]
    return lines


def _write(df: pd.DataFrame, path: Path, header: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as fh:
        for line in header:
            fh.write(line + "\n")
        df.to_csv(fh, index=False)
    logger.info("wrote %s (%d rows)", path, len(df))


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--raw", default=str(RAW_DEFAULT), help="SrV raw directory (local-only)")
    parser.add_argument("--out-dir", default=str(OUT_DEFAULT))
    parser.add_argument("--prior-strength", type=float, default=T.DEFAULT_PRIOR_STRENGTH)
    parser.add_argument("--max-distance-km", type=float, default=T.DEFAULT_MAX_DISTANCE_KM)
    parser.add_argument("--detour-factor", type=float, default=T.DEFAULT_DETOUR_FACTOR)
    parser.add_argument("--n-bootstrap", type=int, default=500)
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args(argv)

    raw = Path(args.raw)
    for name in ("SrV2023_Wege.csv", "SrV2023_Personen.csv", "SrV2023_Haushalte.csv"):
        if not (raw / name).exists():
            raise FileNotFoundError(f"SrV raw file missing: {raw / name}")
    trips = pd.read_csv(raw / "SrV2023_Wege.csv", usecols=TRIP_COLUMNS, **CSV_READ_KWARGS)
    persons = pd.read_csv(raw / "SrV2023_Personen.csv", usecols=["HHNR", "PNR", "V_ALTER"], **CSV_READ_KWARGS)
    households = pd.read_csv(raw / "SrV2023_Haushalte.csv", usecols=["HHNR", "AGS"], **CSV_READ_KWARGS)
    weekdays = sorted(trips["STICHTAG_WTAG"].dropna().unique().tolist())
    if not set(weekdays) <= {2, 3, 4}:
        raise ValueError(f"Expected Tue-Thu reporting days only, found STICHTAG_WTAG codes {weekdays}")

    obs_work, log_work = T.select_person_observations(trips, persons, households, (T.PURPOSE_WORK,),
                                                      max_distance_km=args.max_distance_km)
    obs_edu, log_edu = T.select_person_observations(trips, persons, households, T.EDUCATION_PURPOSES,
                                                    max_distance_km=args.max_distance_km)
    found = sorted(set(obs_work["kreis"]))
    expected = sorted(k for k in T.ZGB_KREISE if k != T.WOLFSBURG_KREIS)
    if found != expected:
        raise ValueError(f"Expected the 7 surveyed ZGB Kreise {expected}, found {found}")

    out = Path(args.out_dir)
    commute = T.build_commute_table(obs_work, prior_strength=args.prior_strength,
                                    n_bootstrap=args.n_bootstrap, seed=args.seed)
    _write(commute, out / T.COMMUTE_TABLE, _header(
        T.COMMUTE_TABLE, "persons with a home<->own-workplace trip (V_ZWECK 1)",
        [f"Bands (routed km): {list(T.WORK_BAND_EDGES_KM)} -> labels {list(T.WORK_BAND_LABELS)}; scopes all / inter / intra",
         "(intra = start AGS == destination AGS, i.e. same Gemeinde). emd_noise_95_* uses",
         f"n_bootstrap={args.n_bootstrap}, seed={args.seed}."],
        log_work))
    education = T.build_education_table(obs_edu, prior_strength=args.prior_strength,
                                        n_bootstrap=args.n_bootstrap, seed=args.seed)
    _write(education, out / T.EDUCATION_TABLE, _header(
        T.EDUCATION_TABLE, "persons with a home<->education trip (V_ZWECK 3,4,5,6)",
        [f"Bands (routed km): {list(T.EDUCATION_BAND_EDGES_KM)} -> labels {list(T.EDUCATION_BAND_LABELS)}.",
         "Levels follow the MODEL age banding (R4): Kita (V_ZWECK 3) counts only at age 0-6 and",
         "Grundschule (4) only at age 5-10 (model age band +/- 1 year); sekundar_1 = code 5 age",
         "10-15; upper_secondary = code 5 or 6 age 16-19 (oberstufe + bbs pooled); university =",
         "code 6 age 20+. comparable=False rows (oberstufe, bbs) are the SrV-only split of",
         "upper_secondary and are descriptive only; (purpose, age) combinations the model cannot",
         "produce map to no level and are excluded (rate logged, see the script's run log)."],
        log_edu))
    quantiles = T.build_quantile_table(obs_work, detour_factor=args.detour_factor,
                                       prior_strength=args.prior_strength)
    _write(quantiles, out / T.QUANTILE_TABLE, _header(
        T.QUANTILE_TABLE, "persons with a home<->own-workplace trip (V_ZWECK 1)",
        [f"distance_km_euclid_* = GIS routed km / {args.detour_factor} (euclidean-equivalent, the unit of",
         "synthesis.population.spatial.commute_distance targets). Percentiles 1..99, long format.",
         "Shrinkage is quantile-wise toward the dominant RS7 pool (monotone)."],
        log_work))
    return 0


if __name__ == "__main__":
    sys.exit(main())
