"""Extract the committed SrV 2023 work-participation-per-Kreis reference table.

Reads the LOCAL-ONLY SrV 2023 "Braunschweig und RGB" scientific-use microdata (persons, trips,
households; cp1252, semicolon, decimal comma) and writes one small aggregate table to
``--out-dir`` (default ``eqasim-data/data/braunschweig/srv``):

    srv2023_work_participation_by_kreis.csv

Definitions live in ``braunschweig.calibration.srv_work_participation`` (universe =
V_WOHNUNG_HO in (1, 2), weight GEWICHT_P_ZENSUS, Kreis from the household AGS, work trip =
V_ZWECK == 1). This is a REGIONAL VALIDATION REFERENCE for the commute-day-state model (spec
2026-09-04, issue #244) -- NOT a control target -- complementing the national MiD-side
reference (``scripts/extract_mid_workday_location.py``). The table carries a provenance header.

Usage (eqasim env, from a worktree; point --raw at the local raw directory):
    python scripts/extract_srv_work_participation.py \
        --raw C:/Users/bienzeisler/Documents/GitHub/eqasim-bs/eqasim-data/data/braunschweig/srv/srv2023_raw \
        --out-dir eqasim-data/data/braunschweig/srv
"""
from __future__ import annotations

import argparse
import datetime as dt
import logging
import sys
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from braunschweig.calibration import srv_work_participation as T  # noqa: E402
from braunschweig.calibration.srv_distance_targets import WOLFSBURG_KREIS, ZGB_KREISE  # noqa: E402

RAW_DEFAULT = REPO / "eqasim-data" / "data" / "braunschweig" / "srv" / "srv2023_raw"
OUT_DEFAULT = REPO / "eqasim-data" / "data" / "braunschweig" / "srv"
CSV_READ_KWARGS = dict(sep=";", decimal=",", encoding="cp1252", low_memory=False)

PERSON_COLUMNS = ["HHNR", "PNR", "V_WOHNUNG_HO", "GEWICHT_P_ZENSUS", "MITTL_WERKTAG"]
TRIP_COLUMNS = ["HHNR", "PNR", "V_ZWECK"]
HOUSEHOLD_COLUMNS = ["HHNR", "AGS"]

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
logger = logging.getLogger("extract_srv_work_participation")


def _require_columns(path: Path, required: list[str]) -> None:
    """Fail early with the file name and the missing column(s) rather than a bare KeyError."""
    header = pd.read_csv(path, nrows=0, **CSV_READ_KWARGS)
    missing = [c for c in required if c not in header.columns]
    if missing:
        raise ValueError(f"{path}: missing required column(s) {missing}")


def _header(table: pd.DataFrame, source_commit: str) -> list[str]:
    """Provenance header for the committed work-participation table."""
    n_kreis = len(ZGB_KREISE)
    zgb = table[table["level"] == "zgb"].iloc[0]
    both_note = [
        "# Priority rule: a person could in principle satisfy BOTH V_WOHNUNG_HO == 1 and have a",
        "#   work trip; share_home_office_day takes priority in that case (see the module",
        "#   docstring). The exact count of persons hitting both conditions in THIS run is in the",
        "#   run log ('... report BOTH a full home-office day ... AND a work trip'), not hardcoded",
        "#   here to avoid this header going stale on a future re-extraction.",
    ]
    lines = [
        "# Source: SrV 2023 Braunschweig + Regionalverband Grossraum Braunschweig scientific-use",
        "#   microdata (local-only, see srv2023_raw/README.md), generated by",
        f"#   scripts/extract_srv_work_participation.py on {dt.date.today().isoformat()}.",
        f"# Code state: eqasim-bs {source_commit}, module "
        "braunschweig/calibration/srv_work_participation.py.",
        f"# Table: {T.WORK_PARTICIPATION_TABLE}",
        "# Reference for validation of the commute-day-state model (spec 2026-09-04) and issue",
        "#   #244; NOT a control target.",
        "# Universe: persons with V_WOHNUNG_HO in (1, 2) (employed persons asked the home-office",
        "#   question on the reporting day; -8 not asked/not employed and -10 no answer are",
        "#   excluded), MITTL_WERKTAG == 1 (average weekday) and a valid, non-negative",
        "#   GEWICHT_P_ZENSUS weight -- see the run log below for exact exclusion counts.",
        "# Definitions: share_home_office_day = weighted share with V_WOHNUNG_HO == 1 (worked the",
        "#   whole reporting day from home); share_work_trip = weighted share with",
        "#   V_WOHNUNG_HO != 1 AND at least one trip with V_ZWECK == 1 (\"Arbeit\", own workplace);",
        "#   share_neither = the remainder. The three shares sum to 1.0 for n_persons > 0.",
        *both_note,
        "# Weight: GEWICHT_P_ZENSUS (population expansion to Zensus 2022 counts).",
        "# Kreis: first 5 digits of the household AGS.",
        "# Wolfsburg (03103) is NOT surveyed by SrV: its row is emitted with n_persons=0 and NaN",
        "#   shares (never dropped or backfilled) -- the stage comparing this table to the model",
        "#   compares 7 Kreise + zgb, not 8 Kreise + zgb.",
        "# Coverage caveat: stratified PSU design over ~44 selected municipalities; per-Kreis rows",
        "#   represent the covered municipalities (ASSUMPTION-grade for the full Kreis).",
        f"# zgb row (n_persons={int(zgb['n_persons'])}): share_home_office_day="
        f"{zgb['share_home_office_day']:.4f}, share_work_trip={zgb['share_work_trip']:.4f}, "
        f"share_neither={zgb['share_neither']:.4f}.",
        f"# Rows: {n_kreis} kreis rows (one per ZGB Kreis code) + 1 zgb row = {n_kreis + 1} total.",
    ]
    return lines


def _write(df: pd.DataFrame, path: Path, header: list[str]) -> None:
    """Write the provenance-headed CSV. ``lineterminator=\"\\n\"`` keeps the data rows LF-only
    regardless of platform; ``float_format=\"%.10g\"`` keeps floats readable while staying
    lossless at the precision the shares carry."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as fh:
        for line in header:
            fh.write(line + "\n")
        df.to_csv(fh, index=False, lineterminator="\n", float_format="%.10g")
    logger.info("wrote %s (%d rows)", path, len(df))


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--raw", default=str(RAW_DEFAULT),
                        help="SrV raw directory (local-only; must contain SrV2023_Personen.csv, "
                             "SrV2023_Wege.csv, SrV2023_Haushalte.csv)")
    parser.add_argument("--out-dir", default=str(OUT_DEFAULT),
                        help="Directory to write the committed table into")
    parser.add_argument("--source-commit", default="unknown",
                        help="git commit hash of this worktree, recorded in the provenance "
                             "header for reproducibility (CLAUDE.md scientific-reproducibility "
                             "rule)")
    args = parser.parse_args(argv)

    raw = Path(args.raw)
    for name in ("SrV2023_Personen.csv", "SrV2023_Wege.csv", "SrV2023_Haushalte.csv"):
        if not (raw / name).exists():
            raise FileNotFoundError(f"SrV raw file missing: {raw / name}")
    _require_columns(raw / "SrV2023_Personen.csv", PERSON_COLUMNS)
    _require_columns(raw / "SrV2023_Wege.csv", TRIP_COLUMNS)
    _require_columns(raw / "SrV2023_Haushalte.csv", HOUSEHOLD_COLUMNS)

    persons = pd.read_csv(raw / "SrV2023_Personen.csv", usecols=PERSON_COLUMNS, **CSV_READ_KWARGS)
    trips = pd.read_csv(raw / "SrV2023_Wege.csv", usecols=TRIP_COLUMNS, **CSV_READ_KWARGS)
    households = pd.read_csv(raw / "SrV2023_Haushalte.csv", usecols=HOUSEHOLD_COLUMNS, **CSV_READ_KWARGS)
    logger.info("read %d persons, %d trips, %d households", len(persons), len(trips), len(households))

    table = T.build_srv_work_participation_table(persons, trips, households)

    found_kreis = set(table[table["level"] == "kreis"]["code"])
    expected_kreis = set(ZGB_KREISE)
    if found_kreis != expected_kreis:
        raise ValueError(f"Expected the 8 ZGB Kreise {sorted(expected_kreis)}, "
                         f"found {sorted(found_kreis)}")

    out = Path(args.out_dir)
    _write(table, out / T.WORK_PARTICIPATION_TABLE, _header(table, args.source_commit))
    return 0


if __name__ == "__main__":
    sys.exit(main())
