"""Extract the two committed SrV 2023 participation aggregates on the at-home-or-mobile universe.

Reads the LOCAL-ONLY SrV 2023 "Braunschweig und RGB" scientific-use microdata (persons, legs,
households; cp1252, semicolon, decimal comma) and writes two small aggregate tables to
``--out-dir`` (default ``eqasim-data/data/braunschweig/srv``):

    srv2023_work_by_employment_by_kreis.csv    (employed share + P(work | employed / not), 14+)
    srv2023_education_by_age_by_kreis.csv      (P(education) per age band 0-5 / 6-17 / 18+)

Both are CONTROL-TARGET SOURCES for the participation-universe redesign (issue #368): a later
target builder turns them into ``target2026_work_by_employment_by_kreis.csv`` and the three
``target2026_education_*_by_kreis.csv`` tables. All definitions -- the at-home-or-mobile
universe, the employed set, the purpose sets, the age bands, the invariants -- live in
``braunschweig.calibration.srv_participation_universe``; this script owns only the raw I/O, the
CLI and the provenance header. Each written file carries an ``# Exclusions:`` line produced by
the builder, so the exclusion counts live IN the committed file and not only in a run log.

Usage (eqasim env, from a worktree; point --raw at the local raw directory):
    python scripts/extract_srv_participation_universe.py \
        --raw C:/Users/bienzeisler/Documents/GitHub/eqasim-bs/eqasim-data/data/braunschweig/srv/srv2023_raw \
        --out-dir eqasim-data/data/braunschweig/srv --source-commit <sha>
"""
from __future__ import annotations

import argparse
import datetime as dt
import logging
import sys
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from braunschweig.calibration import srv_participation_universe as T  # noqa: E402
from braunschweig.calibration.srv_distance_targets import ZGB_KREISE  # noqa: E402

RAW_DEFAULT = REPO / "eqasim-data" / "data" / "braunschweig" / "srv" / "srv2023_raw"
OUT_DEFAULT = REPO / "eqasim-data" / "data" / "braunschweig" / "srv"
CSV_READ_KWARGS = dict(sep=";", decimal=",", encoding="cp1252", low_memory=False)

PERSONS_FILE = "SrV2023_Personen.csv"
LEGS_FILE = "SrV2023_Wege.csv"
HOUSEHOLDS_FILE = "SrV2023_Haushalte.csv"

# Units of the diagnostics keys, written once into each "Exclusions:" line: the key names alone
# do not say whether a count is measured over the FULL Personen file or over an already-filtered
# subset (same note as scripts/extract_srv_work_participation.py).
_EXCLUSIONS_UNITS_NOTE = (
    "(n_persons_total is the raw Personen-file row count; missing_weight is measured on it, "
    "away_from_home on the persons surviving the weight filter, and missing_kreis on the "
    "persons surviving the away-from-home filter; n_universe is the resulting "
    "at-home-or-mobile person count; n_missing_age, n_missing_employment_code, n_below_min_age "
    "(work table only) and n_band_* (education table only) are measured on n_universe; "
    "n_age_14plus (work table only) is n_universe minus n_below_min_age; n_legs_total and "
    "n_legs_missing_purpose are raw Wege-file row counts)"
)

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
logger = logging.getLogger("extract_srv_participation_universe")


def _require_columns(path: Path, required: list) -> None:
    """Fail early with the file name and the missing column(s) rather than a bare KeyError."""
    header = pd.read_csv(path, nrows=0, **CSV_READ_KWARGS)
    missing = [column for column in required if column not in header.columns]
    if missing:
        raise ValueError("%s: missing required column(s) %s" % (path, missing))


def _common_header(table_name: str, source_commit: str) -> list:
    """The provenance lines both tables share (sources, code state, weight, Kreis, caveats)."""
    return [
        "# Source: SrV 2023 Braunschweig + Regionalverband Grossraum Braunschweig scientific-use",
        "#   microdata (local-only, see srv2023_raw/README.md; files %s," % PERSONS_FILE,
        "#   %s, %s), generated by" % (LEGS_FILE, HOUSEHOLDS_FILE),
        "#   scripts/extract_srv_participation_universe.py on %s." % dt.date.today().isoformat(),
        "# Code state: eqasim-bs %s, module "
        "braunschweig/calibration/srv_participation_universe.py." % source_commit,
        "# Table: %s" % table_name,
        "# Role: CONTROL-TARGET SOURCE for the participation-universe redesign (issue #368). A",
        "#   target builder combines these conditional rates into the committed",
        "#   target2026_* control tables; this file itself is not read by a synthesis stage.",
        "# Universe (at_home_or_mobile): persons with a valid non-negative GEWICHT_P_ZENSUS and",
        "#   E_ANZ_WEGE != %d, i.e. the persons who were at home at some point on the reporting"
        % T.AWAY_FROM_HOME_CODE,
        "#   day, whose household resolves to one of the 8 ZGB Kreise. Persons away from home",
        "#   over the WHOLE reporting day are excluded because a synthetic population cannot",
        "#   represent that state -- every synthetic person exists and starts the day at home,",
        "#   so a target taken from the all-persons universe would be diluted by a state the",
        "#   population cannot reproduce (user decision 2026-09-05). See the Exclusions line",
        "#   below for the exact counts.",
        "# Universe guards (the extraction raises, it never adapts): every MITTL_WERKTAG == %d"
        % T.AVERAGE_WEEKDAY,
        "#   (average-weekday Tuesday-Thursday delivery), every negative E_ANZ_WEGE == %d"
        % T.AWAY_FROM_HOME_CODE,
        "#   (so the universe filter drops exactly the away-from-home persons), and every",
        "#   resolved Kreis inside %s." % list(ZGB_KREISE),
        "# Weight: GEWICHT_P_ZENSUS (person expansion to Zensus 2022 counts; the",
        "#   stratum-internal GEWICHT_P must not be used across strata, ADR-0055).",
        "# Kreis: first 5 digits of the zero-padded 8-digit household AGS, joined via HHNR (NOT",
        "#   the survey design stratum ST_CODE, which does not correspond 1:1 to a Kreis).",
        "#   Canonical code-to-name mapping: braunschweig.analysis.spatial.ZGB8 (03101",
        "#   Braunschweig, 03102 Salzgitter, 03103 Wolfsburg, 03151 Gifhorn, 03153 Goslar,",
        "#   03154 Helmstedt, 03157 Peine, 03158 Wolfenbuettel).",
        "# Wolfsburg (03103) is NOT surveyed by SrV and therefore has NO row here (the",
        "#   convention of srv2023_participation_by_kreis.csv); a target builder must fill it",
        "#   from the %s row as a documented assumption." % T.REGION_CODE,
        "# %s row scope: EXACTLY the union of the kreis rows above, so"
        % T.REGION_CODE,
        "#   sum(kreis n_unweighted) == %s n_unweighted holds by construction." % T.REGION_CODE,
        "# Coverage caveat: stratified PSU design over ~44 selected municipalities; per-Kreis",
        "#   rows represent the covered municipalities (ASSUMPTION-grade for the full Kreis).",
    ]


def _work_header(table: pd.DataFrame, diagnostics: dict, source_commit: str) -> list:
    """Provenance header for the work-by-employment table."""
    total = table[table["level"] == T.LEVEL_TOTAL].iloc[0]
    lines = _common_header(T.WORK_BY_EMPLOYMENT_TABLE, source_commit)
    lines += [
        "# Additional universe filter: age (V_ALTER) >= %d -- the universe of the existing"
        % T.MIN_AGE_WORK,
        "#   employment_status Kreis control and the ages at which SrV asks V_ERW at all.",
        "#   Persons without a valid V_ALTER are excluded here as well (n_missing_age).",
        "# Definitions: employed = V_ERW in %s (in Ausbildung/Lehre, full-time, part-time,"
        % list(T.EMPLOYED_V_ERW),
        "#   marginally employed). Code 8 counts as employed by decision Q5 of issue #368: the",
        "#   MiD-side employment_status classes the control targets include in_ausbildung, and",
        "#   ADR-0060 treats MiD in_ausbildung (1.93 %) and SrV V_ERW 8 (1.87 %) as",
        "#   apples-to-apples. A person whose V_ERW is a missing code (-8 not surveyed, -10",
        "#   implausible) is classed NOT employed; the count is n_missing_employment_code in",
        "#   the Exclusions line below.",
        "#   work = at least one leg with E_ZWECK_9 in %s (Arbeit, dienstlich/geschaeftlich) on"
        % sorted(T.WORK_E_ZWECK_9),
        "#   the reporting day -- the same purpose set as the existing",
        "#   srv2023_participation_by_kreis.csv, so the universe (and the employment",
        "#   conditioning) is the only definitional change between the two tables.",
        "# Known asymmetry to the MiD seed side (documented, not corrected): the seed column",
        "#   counts only DIRECTLY RECORDED work legs (MiD W_RBW == 0). The SrV Wege file has no",
        "#   W_RBW counterpart, so no such filter can be applied on this side.",
        "# Columns: code (5-digit ARS or %s), level (\"kreis\"/\"total\"), n_unweighted,"
        % T.REGION_CODE,
        "#   n_employed_unweighted, n_nonemployed_unweighted (the two partition n_unweighted),",
        "#   employed_share (weighted employed share of the %d+ universe), p_work_employed and"
        % T.MIN_AGE_WORK,
        "#   p_work_nonemployed (weighted share of the employed / not employed persons with at",
        "#   least one work leg). A share is NaN, never 0.0, when its conditioning class is",
        "#   empty in that Kreis.",
        "# %s row (n_unweighted=%d): employed_share=%.4f, p_work_employed=%.4f, "
        "p_work_nonemployed=%.4f."
        % (T.REGION_CODE, int(total["n_unweighted"]), total["employed_share"],
           total["p_work_employed"], total["p_work_nonemployed"]),
        "# Rows: %d kreis rows + 1 %s row = %d total."
        % (len(table) - 1, T.REGION_CODE, len(table)),
        "# Invariants (checked before writing, the extraction raises on a violation): the",
        "#   employed/not-employed counts partition n_unweighted on every row; the kreis rows",
        "#   sum to the %s row's n_unweighted; every share is NaN or inside [0, 1]." % T.REGION_CODE,
        "# Exclusions: " + ", ".join("%s=%s" % (key, value) for key, value in diagnostics.items())
        + " " + _EXCLUSIONS_UNITS_NOTE,
    ]
    return lines


def _education_header(table: pd.DataFrame, diagnostics: dict, source_commit: str) -> list:
    """Provenance header for the education-by-age table."""
    lines = _common_header(T.EDUCATION_BY_AGE_TABLE, source_commit)
    totals = table[table["level"] == T.LEVEL_TOTAL].set_index("band")
    lines += [
        "# Age bands (V_ALTER, bounds INCLUSIVE; the 18plus upper bound 200 is a sentinel far",
        "#   above any plausible age, not a real bound):",
    ]
    lines += ["#   %s = ages %d-%d." % (band, minimum, maximum)
              for band, minimum, maximum in T.EDUCATION_AGE_BANDS]
    lines += [
        "#   A person without a valid V_ALTER falls into NO band (n_missing_age below).",
        "# Definition: p_education = weighted share of the band's persons with at least one leg",
        "#   with E_ZWECK_9 in %s (Kita/Schule, Ausbildung/Studium) on the reporting day -- the"
        % sorted(T.EDUCATION_E_ZWECK_9),
        "#   same purpose set as the existing srv2023_participation_by_kreis.csv, so the",
        "#   universe and the age banding are the only definitional changes.",
        "# Columns: code (5-digit ARS or %s), level (\"kreis\"/\"total\"), band, n_unweighted,"
        % T.REGION_CODE,
        "#   p_education. A band with no person in a Kreis is still emitted, with",
        "#   n_unweighted=0 and a NaN share (never dropped), so a consumer never has to guess",
        "#   whether a band is missing or empty.",
        "# %s rows:" % T.REGION_CODE,
    ]
    lines += ["#   %s: n_unweighted=%d, p_education=%s"
              % (band, int(totals.loc[band, "n_unweighted"]),
                 "NaN" if pd.isna(totals.loc[band, "p_education"])
                 else "%.4f" % totals.loc[band, "p_education"])
              for band, _, _ in T.EDUCATION_AGE_BANDS]
    lines += [
        "# Rows: %d kreis rows + %d %s rows = %d total (one row per code x band)."
        % (len(table) - len(T.EDUCATION_AGE_BANDS), len(T.EDUCATION_AGE_BANDS), T.REGION_CODE,
           len(table)),
        "# Invariants (checked before writing, the extraction raises on a violation): every",
        "#   band is present; per band the kreis rows sum to the %s row's n_unweighted; every"
        % T.REGION_CODE,
        "#   share is NaN or inside [0, 1].",
        "# Exclusions: " + ", ".join("%s=%s" % (key, value) for key, value in diagnostics.items())
        + " " + _EXCLUSIONS_UNITS_NOTE,
    ]
    return lines


def _write(df: pd.DataFrame, path: Path, header: list) -> None:
    """Write the provenance-headed CSV. ``lineterminator="\\n"`` keeps the data rows LF-only
    regardless of platform; ``float_format="%.10g"`` keeps floats readable while staying
    lossless at the precision the shares carry."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as fh:
        for line in header:
            fh.write(line + "\n")
        df.to_csv(fh, index=False, lineterminator="\n", float_format="%.10g")
    logger.info("wrote %s (%d rows)", path, len(df))


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--raw", default=str(RAW_DEFAULT),
                        help="SrV raw directory (local-only; must contain %s, %s, %s)"
                             % (PERSONS_FILE, LEGS_FILE, HOUSEHOLDS_FILE))
    parser.add_argument("--out-dir", default=str(OUT_DEFAULT),
                        help="Directory to write the two committed tables into")
    parser.add_argument("--source-commit", default="unknown",
                        help="git commit hash of this worktree, recorded in the provenance "
                             "header for reproducibility (CLAUDE.md scientific-reproducibility "
                             "rule)")
    args = parser.parse_args(argv)

    raw = Path(args.raw)
    for name in (PERSONS_FILE, LEGS_FILE, HOUSEHOLDS_FILE):
        if not (raw / name).exists():
            raise FileNotFoundError("SrV raw file missing: %s" % (raw / name))
    _require_columns(raw / PERSONS_FILE, T.PERSON_COLUMNS)
    _require_columns(raw / LEGS_FILE, T.LEG_COLUMNS)
    _require_columns(raw / HOUSEHOLDS_FILE, T.HOUSEHOLD_COLUMNS)

    persons = pd.read_csv(raw / PERSONS_FILE, usecols=T.PERSON_COLUMNS, **CSV_READ_KWARGS)
    legs = pd.read_csv(raw / LEGS_FILE, usecols=T.LEG_COLUMNS, **CSV_READ_KWARGS)
    households = pd.read_csv(raw / HOUSEHOLDS_FILE, usecols=T.HOUSEHOLD_COLUMNS,
                             **CSV_READ_KWARGS)
    logger.info("read %d persons, %d legs, %d households", len(persons), len(legs),
                len(households))

    work_table, work_diagnostics = T.build_work_by_employment_aggregate(persons, legs, households)
    education_table, education_diagnostics = T.build_education_by_age_aggregate(
        persons, legs, households)
    T.check_invariants(work_table, education_table)
    logger.info("invariants passed for both tables")
    logger.info("work diagnostics: %s", work_diagnostics)
    logger.info("education diagnostics: %s", education_diagnostics)

    out = Path(args.out_dir)
    _write(work_table, out / T.WORK_BY_EMPLOYMENT_TABLE,
           _work_header(work_table, work_diagnostics, args.source_commit))
    _write(education_table, out / T.EDUCATION_BY_AGE_TABLE,
           _education_header(education_table, education_diagnostics, args.source_commit))
    return 0


if __name__ == "__main__":
    sys.exit(main())
