# scripts/extract_mid_license_by_sex_cohort.py
"""Extract car-licence shares by sex x age cohort from the MiD 2023 person microdata.

STANDALONE (pandas only, no braunschweig imports) so it can run on the server where
the raw microdata lives.

Why this table exists (issue #322): the committed MiD reference tables
``mid2023_P17_1_by_sex.csv`` and ``mid2023_P17_1_by_age.csv`` are MARGINALS taken from
the infas report -- each resolves one dimension only. Judging a synthetic population's
male-female licence difference against the by-sex marginal therefore compares two
different quantities: the licence gap is concentrated in the 65+ cohort and nearly
absent below it, so a marginal comparison largely measures the age composition of the
survey sample. Measured on the microdata below, MiD's own 18+ marginal gap is +3.7pp
while the committed ZGB 14+ marginal reads +8pp. This table resolves both dimensions so
the comparison against a synthetic population is like-for-like.

Regional resolution: the MiD person/household microdata carries NO Kreis or AGS key --
only ``BLAND`` and the ``RegioStaR*`` classes -- so a Braunschweig-region (ZGB) cross
cannot be computed from it at all, and the committed ZGB tables (report PDF) publish
marginals only. This script therefore reports three regional readings whose
interpretation differs and which must not be conflated:

* ``national``   -- the whole MiD sample; largest n, no regional targeting.
* ``bland_3``    -- Niedersachsen, the federal state the study region lies in.
* ``rs7_<code>`` -- one row set per RegioStaR7 class. This is the repo's established
  way of making national MiD regionally comparable (the #240 ownership conditionals
  use P(count | RegioStaR7 x haustyp) for exactly this reason, see ADR-0092).

Universe: persons with P_GEW > 0, HP_ALTER >= 18, P_FSCHEIN in {1 ja, 2 nein} and
HP_SEX in {1 male, 2 female}. The 18+ base matches the universe the synthesis assigns
licences on (no BF17 / minimum-age convention enters). Excluded rates are logged.

Weight: P_GEW (person weight).

Writes (committed): eqasim-data/data/braunschweig/mid/mid2023_license_by_sex_cohort.csv

Usage (on the server, from the repo root):
    python scripts/extract_mid_license_by_sex_cohort.py [--raw-dir <dir>] [--out-dir <dir>]
"""
from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(levelname)s [%(name)s] %(message)s")
logger = logging.getLogger("extract_mid_license_by_sex_cohort")

REPO = Path(__file__).resolve().parents[1]
RAW_DIR_DEFAULT = REPO / "eqasim-data" / "data" / "braunschweig" / "popsim" / "mid2023_raw"
OUT_DIR_DEFAULT = REPO / "eqasim-data" / "data" / "braunschweig" / "mid"
PERSONS_FILE = "MiD2023_Personen.csv"
HOUSEHOLDS_FILE = "MiD2023_Haushalte.csv"

# The raw MiD CSVs are comma-separated and latin-1 encoded (verified 2026-08-19 on the
# ownership extraction, scripts/extract_mid_ownership_by_rs7_haustyp.py).
CSV_READ_KWARGS = dict(sep=",", encoding="latin-1", low_memory=False)

MIN_AGE = 18
COHORT_EDGE_AGE = 65
SEX_LABELS = {1: "male", 2: "female"}
LICENSE_YES = 1
LICENSE_NO = 2
NIEDERSACHSEN_BLAND = 3
RS7_CODES = tuple(range(71, 78))

OUT_NAME = "mid2023_license_by_sex_cohort.csv"

HEADER_TEMPLATE = """\
# Source: MiD 2023 person + household microdata (MiD2023_Personen.csv joined to
#   MiD2023_Haushalte.csv on H_ID; national sample, local-only raw -- never committed).
#   Generated by scripts/extract_mid_license_by_sex_cohort.py.
# Construct: share of persons holding a car driving licence (P_FSCHEIN == 1), P_GEW-weighted,
#   per (region, sex, age cohort). Cohorts split at age {edge}: 18_64 and 65plus.
# Universe: P_GEW > 0, HP_ALTER >= {min_age}, P_FSCHEIN in {{1 ja, 2 nein}}, HP_SEX in
#   {{1, 2}}. Excluded: {no_answer_rate:.3f}% of age-eligible persons for a missing
#   P_FSCHEIN, {other_sex_rate:.3f}% for a non-binary HP_SEX.
# Region coverage: {unmatched_rate:.3f}% of universe rows carry an H_ID absent from the
#   household file; they are counted in the 'national' rows (which need no region key)
#   and excluded from every regional row.
# Region column: 'national' = whole MiD sample; 'bland_3' = Niedersachsen;
#   'rs7_<code>' = one RegioStaR7 class. The microdata carries NO Kreis/AGS key, so a
#   ZGB cross is impossible from MiD and these are regional PROXIES, not ZGB values --
#   see the module docstring and ADR-0093 before using any of them as a target.
# Purpose: like-for-like structure reference for issue #322. NOT a control target: the
#   65+ female cell disagrees with the regional SrV survey by ~8pp (SrV 89.7% vs MiD
#   81.8% in Niedersachsen), which is the ADR-0079 identification problem localised to
#   one cell.
# n_unweighted: raw respondents per (region, sex, cohort) cell.
"""


def load_persons_with_region(raw_dir: Path) -> pd.DataFrame:
    """Load the person file joined to the household region keys, universe-filtered."""
    persons_path = raw_dir / PERSONS_FILE
    households_path = raw_dir / HOUSEHOLDS_FILE
    for path in (persons_path, households_path):
        if not path.exists():
            raise SystemExit(
                f"missing raw microdata file {path}; the MiD raw data is local-only and "
                "lives on the run server (see docs/registry/data/ for the expected path)")

    households = pd.read_csv(
        households_path, usecols=["H_ID", "BLAND", "RegioStaR7"], **CSV_READ_KWARGS)
    persons = pd.read_csv(
        persons_path,
        usecols=["H_ID", "P_FSCHEIN", "HP_ALTER", "HP_SEX", "P_GEW"], **CSV_READ_KWARGS)

    merged = persons.merge(households, on="H_ID", how="left", validate="many_to_one")
    # A small number of person rows carry an H_ID absent from the household file: 312
    # rows at the merge in the 2026 delivery, of which 54 (0.023%) survive the universe
    # filter below. They are kept for the 'national' reading, which needs no region key,
    # and excluded from every regional reading, which does. The rate is logged AND
    # written into the committed header rather than absorbed silently.
    merged["has_region"] = merged["BLAND"].notna()

    weighted = merged[merged["P_GEW"] > 0]
    age_eligible = weighted[weighted["HP_ALTER"] >= MIN_AGE]
    with_answer = age_eligible[age_eligible["P_FSCHEIN"].isin([LICENSE_YES, LICENSE_NO])]
    universe = with_answer[with_answer["HP_SEX"].isin(sorted(SEX_LABELS))].copy()

    no_answer_rate = 100.0 * (len(age_eligible) - len(with_answer)) / max(len(age_eligible), 1)
    other_sex_rate = 100.0 * (len(with_answer) - len(universe)) / max(len(with_answer), 1)
    logger.info(
        "[license_sex_cohort] universe: %d persons aged %d+; excluded %.3f%% for a "
        "missing P_FSCHEIN and %.3f%% for a non-binary HP_SEX",
        len(universe), MIN_AGE, no_answer_rate, other_sex_rate)

    unmatched_rate = 100.0 * (~universe["has_region"]).sum() / max(len(universe), 1)
    if unmatched_rate:
        logger.warning(
            "[license_sex_cohort] %d/%d (%.3f%%) universe rows have an H_ID absent from "
            "the household file; they count in the 'national' rows and are excluded from "
            "every regional row",
            int((~universe["has_region"]).sum()), len(universe), unmatched_rate)

    universe.attrs["no_answer_rate"] = no_answer_rate
    universe.attrs["other_sex_rate"] = other_sex_rate
    universe.attrs["unmatched_rate"] = unmatched_rate
    return universe


def build_license_by_sex_cohort_table(universe: pd.DataFrame) -> pd.DataFrame:
    """Weighted licence share per (region, sex, cohort); fails loudly on an empty cell."""
    with_region = universe[universe["has_region"]]
    regions: list[tuple[str, pd.DataFrame]] = [("national", universe)]
    regions.append(("bland_3", with_region[with_region["BLAND"] == NIEDERSACHSEN_BLAND]))
    for code in RS7_CODES:
        regions.append((f"rs7_{code}", with_region[with_region["RegioStaR7"] == code]))

    rows = []
    for region, frame in regions:
        if frame.empty:
            raise RuntimeError(
                f"[license_sex_cohort] region {region}: no respondents at all; a "
                "consumer would read the missing rows as zero")
        is_senior = frame["HP_ALTER"] >= COHORT_EDGE_AGE
        for sex_code, sex_label in sorted(SEX_LABELS.items()):
            for senior in (False, True):
                cell = frame[(frame["HP_SEX"] == sex_code) & (is_senior == senior)]
                cohort = "65plus" if senior else "18_64"
                if cell.empty:
                    raise RuntimeError(
                        f"[license_sex_cohort] region {region}: no respondents in cell "
                        f"({sex_label}, {cohort}); the cell grid must be complete or a "
                        "consumer would silently read a missing cell as zero")
                weight = cell["P_GEW"]
                total = float(weight.sum())
                if total <= 0:
                    raise RuntimeError(
                        f"[license_sex_cohort] region {region} cell ({sex_label}, "
                        f"{cohort}): zero total weight")
                with_license = float(weight[cell["P_FSCHEIN"] == LICENSE_YES].sum())
                rows.append({
                    "region": region,
                    "sex": sex_label,
                    "cohort": cohort,
                    "cohort_lo": COHORT_EDGE_AGE if senior else MIN_AGE,
                    "cohort_hi": 999 if senior else COHORT_EDGE_AGE - 1,
                    "n_unweighted": len(cell),
                    "n_weighted": round(total, 2),
                    "share_with_license": round(with_license / total, 4),
                })
    table = pd.DataFrame(rows)
    thinnest = int(table["n_unweighted"].min())
    logger.info(
        "[license_sex_cohort] %d rows over %d regions; thinnest cell n_unweighted=%d",
        len(table), len(regions), thinnest)
    return table


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--raw-dir", type=Path, default=RAW_DIR_DEFAULT)
    parser.add_argument("--out-dir", type=Path, default=OUT_DIR_DEFAULT)
    args = parser.parse_args(argv)

    universe = load_persons_with_region(args.raw_dir)
    table = build_license_by_sex_cohort_table(universe)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    out_path = args.out_dir / OUT_NAME
    with open(out_path, "w", encoding="utf-8", newline="") as handle:
        handle.write(HEADER_TEMPLATE.format(
            edge=COHORT_EDGE_AGE, min_age=MIN_AGE,
            no_answer_rate=universe.attrs["no_answer_rate"],
            other_sex_rate=universe.attrs["other_sex_rate"],
            unmatched_rate=universe.attrs["unmatched_rate"]))
        table.to_csv(handle, index=False)
    logger.info("[license_sex_cohort] wrote %s (%d rows)", out_path, len(table))
    return 0


if __name__ == "__main__":
    sys.exit(main())
