"""Extract the committed SrV 2023 fine-purpose reference (issue #242, sub-project C).

Reads the LOCAL-ONLY SrV 2023 "Braunschweig und RGB" scientific-use trip microdata (cp1252,
semicolon, decimal comma) and writes one small aggregate table to ``--out-dir`` (default
``eqasim-data/data/braunschweig/srv``):

    srv2023_fine_purpose_reference.csv   (share of each fine V_ZWECK code WITHIN its coarse
                                          purpose, GEWICHT_W_ZENSUS-weighted, plus weighted
                                          GIS-distance percentiles and the median duration)

Role: a MEASUREMENT REFERENCE for the MiD W_ZWD subtype split of
``braunschweig.popsim.purpose_subtype`` / ``braunschweig.popsim.shop_subtype`` -- NOT a
PopulationSim control target and NOT a validated calibration target. No synthesis, location or
distribution stage reads it; ``scripts/compare_purpose_subtypes_srv.py`` is its only consumer.
All definitions -- the measured fine codes, the out-of-scope codes, the missing-value codes, the
universe guards -- live in ``braunschweig.calibration.srv_fine_purpose``; this script owns only
the raw I/O, the CLI and the provenance header. The written file carries the exclusion counts
produced by the builder, so they live IN the committed file and not only in a run log.

Usage (eqasim env, from a worktree; point --raw at the local raw directory):
    python scripts/extract_srv_fine_purpose_reference.py \
        --raw C:/Users/bienzeisler/Documents/GitHub/eqasim-bs/eqasim-data/data/braunschweig/srv/srv2023_raw \
        --out-dir eqasim-data/data/braunschweig/srv --source-commit <sha>
"""
from __future__ import annotations

import argparse
import datetime as dt
import logging
import sys
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from braunschweig.calibration import srv_fine_purpose as F  # noqa: E402

RAW_DEFAULT = REPO / "eqasim-data" / "data" / "braunschweig" / "srv" / "srv2023_raw"
OUT_DEFAULT = REPO / "eqasim-data" / "data" / "braunschweig" / "srv"
CSV_READ_KWARGS = dict(sep=";", decimal=",", encoding="cp1252", low_memory=False)

TRIPS_FILE = "SrV2023_Wege.csv"
CODEBOOK_FILE = "SrV2023_Datenkodierung_SciUse.xlsx"

# Units of the diagnostics keys, written once into the header's "Exclusions:" line: the key names
# alone do not say whether a count is measured over the FULL raw Wege file or over the already
# filtered in-scope subset (same note as scripts/extract_srv_absence.py).
_EXCLUSIONS_UNITS_NOTE = (
    "(n_trips_raw is the raw Wege-file row count; n_trips_out_of_scope is measured on it; "
    "n_trips_measured is the resulting count of trips with a measured fine V_ZWECK; "
    "n_trips_gis_invalid and n_trips_duration_invalid are measured on n_trips_measured)")

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
logger = logging.getLogger("extract_srv_fine_purpose_reference")


def _require_columns(path: Path, required: list) -> None:
    """Fail early with the file name and the missing column(s) rather than a bare KeyError."""
    header = pd.read_csv(path, nrows=0, **CSV_READ_KWARGS)
    missing = [column for column in required if column not in header.columns]
    if missing:
        raise ValueError("%s: missing required column(s) %s" % (path, missing))


def _header(table: pd.DataFrame, diagnostics: dict, source_commit: str) -> list:
    """Provenance header of the fine-purpose reference (source, role, universe, exclusions)."""
    coarse_map = "; ".join(
        "%s: %s" % (coarse, ", ".join(str(code) for code in sorted(
            c for c, name in F.COARSE_BY_FINE.items() if name == coarse)))
        for coarse in F.COARSE_PURPOSES)
    gis_rate = (100.0 * (diagnostics["n_trips_measured"] - diagnostics["n_trips_gis_invalid"])
                / diagnostics["n_trips_measured"]) if diagnostics["n_trips_measured"] else float("nan")
    duration_rate = (100.0 * (diagnostics["n_trips_measured"] - diagnostics["n_trips_duration_invalid"])
                     / diagnostics["n_trips_measured"]) if diagnostics["n_trips_measured"] else float("nan")
    lines = [
        "# Source: SrV 2023 Braunschweig + Regionalverband Grossraum Braunschweig scientific-use",
        "#   microdata (local-only, see srv2023_raw/README.md; file %s), generated by" % TRIPS_FILE,
        "#   scripts/extract_srv_fine_purpose_reference.py on %s." % dt.date.today().isoformat(),
        "# Code state: eqasim-bs %s (the commit that introduced the extraction code), module"
        % source_commit,
        "#   braunschweig/calibration/srv_fine_purpose.py. Header text was updated in the following",
        "#   fix-round commit; the measured data rows are unchanged.",
        "# Table: %s" % F.FINE_PURPOSE_TABLE,
        "# Role: MEASUREMENT REFERENCE for the MiD W_ZWD subtype split of",
        "#   braunschweig.popsim.purpose_subtype / shop_subtype (issue #242, sub-project C). NOT a",
        "#   PopulationSim control target and NOT a validated calibration target: no synthesis,",
        "#   location or distribution stage reads it, and nothing is re-estimated from it. Its only",
        "#   consumer is scripts/compare_purpose_subtypes_srv.py.",
        "# Universe: every delivered SrV trip whose V_ZWECK is a MEASURED fine code (%s)."
        % coarse_map,
        "#   Trips of the other delivered purposes (work 1-2, education 3-7, escort 12, home 19,",
        "#   'Sonstiges' 70, 'Unplausibel' -10) are out of scope and dropped; a V_ZWECK in neither",
        "#   map makes the extraction RAISE, so a new purpose code cannot enter a silent bucket.",
        "# Weights: GEWICHT_W_ZENSUS (trip expansion to Zensus 2022 counts). The stratum-internal",
        "#   GEWICHT_W must not be used across strata (ADR-0055). share_within_coarse is WEIGHTED;",
        "#   n_unweighted is the plain row count -- the two columns answer different questions.",
        "# Value labels: SrV 2023 codebook %s, sheet 'Tabelle1', variable V_ZWECK ('Ziel/Zweck'),"
        % CODEBOOK_FILE,
        "#   value labels in column F, cells F8236-F8256 (the code numbers are the matching E cells);",
        "#   German umlauts transliterated (ae/oe/ue/ss) to keep the module ASCII.",
        "# Universe guards (the extraction raises, it never adapts): every MITTL_WERKTAG == %d"
        % F.AVERAGE_WEEKDAY,
        "#   (average-weekday Tuesday-Thursday delivery) and every trip a positive GEWICHT_W_ZENSUS.",
        "# Coverage: GIS length valid (> 0 km) for %d/%d measured trips (%.2f%%); duration valid for"
        % (diagnostics["n_trips_measured"] - diagnostics["n_trips_gis_invalid"],
           diagnostics["n_trips_measured"], gis_rate),
        "#   %d/%d (%.2f%%). GIS_LAENGE_GUELTIG == %s is the codebook's 'Berechnung nicht moeglich'"
        % (diagnostics["n_trips_measured"] - diagnostics["n_trips_duration_invalid"],
           diagnostics["n_trips_measured"], duration_rate, F.GIS_INVALID_CODE),
        "#   code and E_DAUER in %s are 'Unplausibel'/'Berechnung nicht moeglich'; such a trip is"
        % (list(F.DURATION_INVALID_CODES),),
        "#   EXCLUDED from the percentiles but KEPT in n_unweighted and in share_within_coarse --",
        "#   only its distance/duration is unknown, not the trip.",
        "# Exclusions: " + ", ".join("%s=%s" % (key, value) for key, value in diagnostics.items())
        + " " + _EXCLUSIONS_UNITS_NOTE,
        "# Columns: coarse (%s), fine_code (V_ZWECK), label (codebook), n_unweighted,"
        % ", ".join(F.COARSE_PURPOSES),
        "#   share_within_coarse (GEWICHT_W_ZENSUS-weighted share of the coarse purpose's trips;",
        "#   the shares of one coarse purpose sum to 1), gis_km_p25/p50/p75 (weighted percentiles",
        "#   of GIS_LAENGE_GUELTIG in km, Hazen midpoint-CDF convention -- the same",
        "#   srv_distance_targets.weighted_quantiles the MiD side uses, so the two are comparable),",
        "#   duration_min_p50 (weighted median E_DAUER in minutes). A fine code with no trip is",
        "#   still emitted (n_unweighted=0), never dropped.",
    ]
    lines += ["#   %s %d (%s): n=%d, share=%s, gis_km_p50=%s"
              % (row["coarse"], int(row["fine_code"]), row["label"], int(row["n_unweighted"]),
                 "NaN" if pd.isna(row["share_within_coarse"]) else "%.4f" % row["share_within_coarse"],
                 "NaN" if pd.isna(row["gis_km_p50"]) else "%.3f" % row["gis_km_p50"])
              for _, row in table.iterrows()]
    lines += [
        "# Rows: %d fine purpose codes." % len(table),
        "# Invariants (checked before writing, the extraction raises on a violation): exactly the",
        "#   fine codes %s are present, in coarse-purpose then code order; every share is NaN or"
        % [int(code) for code in table["fine_code"]],
        "#   inside [0, 1] and the shares of each coarse purpose sum to 1; every percentile is NaN",
        "#   or positive; p25 <= p50 <= p75.",
    ]
    return lines


def _write(df: pd.DataFrame, path: Path, header: list) -> None:
    """Write the provenance-headed CSV. ``lineterminator="\\n"`` keeps the data rows LF-only
    regardless of platform; ``float_format="%.10g"`` keeps floats readable while staying lossless
    at the precision the shares carry."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as handle:
        for line in header:
            handle.write(line + "\n")
        df.to_csv(handle, index=False, lineterminator="\n", float_format="%.10g")
    logger.info("wrote %s (%d rows)", path, len(df))


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--raw", type=Path, default=RAW_DEFAULT,
                        help="Directory holding the LOCAL raw SrV 2023 delivery.")
    parser.add_argument("--out-dir", type=Path, default=OUT_DEFAULT,
                        help="Directory to write the committed reference table into.")
    parser.add_argument("--source-commit", required=True,
                        help="Git commit hash of the code state, recorded in the header.")
    args = parser.parse_args(argv)

    trips_path = args.raw / TRIPS_FILE
    if not trips_path.exists():
        raise FileNotFoundError(
            "[extract_srv_fine_purpose_reference] raw SrV trip file not found: %s. Pass --raw "
            "pointing at the directory holding %s (LOCAL raw delivery, never committed)."
            % (trips_path, TRIPS_FILE))
    _require_columns(trips_path, F.TRIP_COLUMNS)
    trips = pd.read_csv(trips_path, usecols=F.TRIP_COLUMNS, **CSV_READ_KWARGS)
    logger.info("read %d trips from %s", len(trips), trips_path)

    table, diagnostics = F.build_fine_purpose_reference(trips)
    F.check_invariants(table)
    logger.info("invariants passed; diagnostics: %s", diagnostics)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    _write(table, args.out_dir / F.FINE_PURPOSE_TABLE,
           _header(table, diagnostics, args.source_commit))
    return 0


if __name__ == "__main__":
    sys.exit(main())
