"""
Rebuild the MiD/infas economic-status construct on the SrV 2023
Braunschweig+RGB households and write a per-Kreis/stratum aggregate.

Construct: weighted household size (1.0 first member 14+, +0.5 per further
14+, +0.3 per <14; from SrV person ages) x monthly net household income class
(SrV V_EINK) looked up in the committed MiD status matrix
(mid2023_economic_status_matrix.csv, Task 1).

ASSUMPTIONS (documented in the output header):
- SrV V_EINK classes 8 (3600-4600), 9 (4600-5600), 10 (5600-6600) each span
  two MiD matrix columns; the household weight is split by bracket width
  (0.4/0.6). Class 11 (>=6600) is split 0.5/0.5 between the 6600-7000 and
  >7000 columns (top-class width unknown).
- Households with income missing (V_EINK in {-10,-9,-5}) are EXCLUDED from
  the distribution (MiD imputes income before the status is built; the SrV
  SciUse file has no imputed income). The excluded share is reported as
  share_income_missing.
- Weighted size above 4.5 uses the 4.5 matrix row (matrix top row).

Weight: GEWICHT_HH_ZENSUS ("fuer stadtuebergreifende Auswertungen", full
expansion to Zensus 2022 counts per municipality). The stratum-internal
standard weight GEWICHT_HH is normalized to mean ~1 WITHIN each ST_CODE
stratum and therefore biases any cross-stratum aggregate (total/kreis rows);
it must not be used here (fixed 2026-07-08, see docs/DECISIONS.md).

Inputs (local-only raw): SrV2023_Haushalte.csv + SrV2023_Personen.csv.
Writes: eqasim-data/data/braunschweig/srv/srv2023_economic_status_by_kreis.csv

Usage:
    python scripts/extract_srv_economic_status_kreis.py [--raw <dir>] [--out <path>]
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import numpy as np
import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
log = logging.getLogger("srv_status")

REPO = Path(__file__).resolve().parents[1]
RAW_DEFAULT = REPO / "eqasim-data" / "data" / "braunschweig" / "srv" / "srv2023_raw"
MATRIX_DEFAULT = (REPO / "eqasim-data" / "data" / "braunschweig" / "mid"
                  / "mid2023_economic_status_matrix.csv")
OUT_DEFAULT = (REPO / "eqasim-data" / "data" / "braunschweig" / "srv"
               / "srv2023_economic_status_by_kreis.csv")

STATUS_COLS = ["very_low", "low", "medium", "high", "very_high"]
KREIS_NAMES = {"03101": "Braunschweig", "03102": "Salzgitter",
               "03151": "Gifhorn", "03153": "Goslar", "03154": "Helmstedt",
               "03157": "Peine", "03158": "Wolfenbuettel"}

# SrV V_EINK class -> [(matrix income_col, weight fraction), ...]
EINK_TO_COLS = {
    1: [(0, 1.0)], 2: [(1, 1.0)], 3: [(2, 1.0)], 4: [(3, 1.0)], 5: [(4, 1.0)],
    6: [(5, 1.0)], 7: [(6, 1.0)],
    8: [(7, 0.4), (8, 0.6)],
    9: [(9, 0.4), (10, 0.6)],
    10: [(11, 0.4), (12, 0.6)],
    11: [(13, 0.5), (14, 0.5)],
}

HEADER = """\
# Source: SrV 2023 Braunschweig+RGB scientific-use microdata (local-only,
#   see srv2023_raw/README.md), status construct rebuilt per the MiD 2023
#   handbook rule via the committed matrix mid2023_economic_status_matrix.csv.
#   Generated by scripts/extract_srv_economic_status_kreis.py.
# Universe: households with valid GEWICHT_HH_ZENSUS (>= 0) AND a substantive
#   income answer (V_EINK 1..11) AND at least one member aged 14+ recorded.
# Weight: GEWICHT_HH_ZENSUS ("fuer stadtuebergreifende Auswertungen", full
#   expansion to Zensus 2022 counts per municipality; the stratum-internal
#   standard weight GEWICHT_HH is mean ~1 per ST_CODE stratum and biases any
#   cross-stratum aggregate, so it is not used -- fixed 2026-07-08). Shares
#   are fractions and sum to 1 per row.
# share_income_missing: weighted share of households (per group) whose
#   V_EINK is -10/-9/-5; these are EXCLUDED from the status shares (MiD
#   imputes income pre-status, the SrV SciUse file does not) -> the status
#   level carries an observed-responders selectivity caveat.
# ASSUMPTION: V_EINK 8/9/10 split 0.4/0.6 over the two spanned matrix
#   columns (bracket width); class 11 split 0.5/0.5. Weighted size > 4.5
#   uses the 4.5 matrix row.
# ASSUMPTION (coverage, not weighting): per-Kreis rows extrapolate a
#   stratified selected-municipality sample to the full Kreis; the ZENSUS
#   weight already expands per municipality, so per-stratum (ST_CODE) rows
#   remain the design-safe aggregation level, not a weighting workaround.
"""


def load_matrix(path: Path):
    m = pd.read_csv(path, comment="#")
    rows_desc = sorted(m["wsize_row"].unique(), reverse=True)
    lookup = m.set_index(["wsize_row", "income_col"])["status"].to_dict()

    def status_of(wsize: float, col: int) -> str:
        capped = min(wsize, 4.5)
        for label in rows_desc:  # descending: first label <= capped
            if capped >= label - 1e-9:
                return lookup[(label, col)]
        return lookup[(rows_desc[-1], col)]

    return status_of


def load_households(raw_dir: Path) -> pd.DataFrame:
    h = pd.read_csv(raw_dir / "SrV2023_Haushalte.csv", sep=";", decimal=",",
                    encoding="cp1252", low_memory=False)
    h["kreis"] = h["AGS"].astype(str).str.zfill(8).str[:5]
    h["gw"] = pd.to_numeric(h["GEWICHT_HH_ZENSUS"], errors="coerce")
    dropped = int((~(h["gw"] >= 0)).sum())
    log.info("households: GEWICHT_HH_ZENSUS weight >= 0 kept %d/%d (dropped %d)",
             len(h) - dropped, len(h), dropped)
    return h[h["gw"] >= 0].copy()


def weighted_sizes(raw_dir: Path) -> pd.Series:
    p = pd.read_csv(raw_dir / "SrV2023_Personen.csv", sep=";", decimal=",",
                    encoding="cp1252", low_memory=False,
                    usecols=["HHNR", "V_ALTER"])
    p["age"] = pd.to_numeric(p["V_ALTER"], errors="coerce")
    p = p[p["age"] >= 0]
    adults = (p["age"] >= 14).groupby(p["HHNR"]).sum()
    kids = (p["age"] < 14).groupby(p["HHNR"]).sum()
    ws = 1.0 + 0.5 * (adults - 1).clip(lower=0) + 0.3 * kids
    ws[adults == 0] = np.nan  # construct undefined without an adult record
    return ws.rename("wsize")


def build_status_records(h: pd.DataFrame, status_of) -> pd.DataFrame:
    h = h.copy()
    h["eink"] = pd.to_numeric(h["V_EINK"], errors="coerce")
    usable = h["eink"].isin(EINK_TO_COLS.keys()) & h["wsize"].notna()
    log.info("status universe: %d/%d households usable (income missing "
             "excluded: %.1f%%)", int(usable.sum()), len(h),
             float((h["eink"].isin([-10, -9, -5])).mean() * 100))
    records = []
    for _, r in h[usable].iterrows():
        for col, frac in EINK_TO_COLS[int(r["eink"])]:
            records.append((r["kreis"], str(r["ST_CODE"]), r["ST_CODE_NAME"],
                            status_of(float(r["wsize"]), col),
                            float(r["gw"]) * frac))
    return pd.DataFrame(records, columns=["kreis", "st_code", "st_name",
                                          "status", "w"])


def aggregate(recs: pd.DataFrame, h: pd.DataFrame) -> pd.DataFrame:
    h = h.copy()
    h["eink"] = pd.to_numeric(h["V_EINK"], errors="coerce")
    h["inc_missing"] = h["eink"].isin([-10, -9, -5])

    def one_group(rec_sel, hh_sel, level, code, name):
        dist = rec_sel.groupby("status")["w"].sum().reindex(STATUS_COLS,
                                                            fill_value=0.0)
        total = dist.sum()
        if total <= 0:
            raise ValueError(f"empty status group {level}/{code}")
        miss = ((hh_sel["gw"] * hh_sel["inc_missing"]).sum()
                / hh_sel["gw"].sum())
        row = {"level": level, "code": code, "name": name,
               "n_unweighted": int(hh_sel[~hh_sel["inc_missing"]].shape[0]),
               "n_weighted": round(float(hh_sel["gw"].sum()), 2),
               "share_income_missing": round(float(miss), 4)}
        row.update({c: round(float(v / total), 4) for c, v in dist.items()})
        return row

    out = [one_group(recs, h, "total", "total", "Gesamt")]
    for kreis, name in KREIS_NAMES.items():
        out.append(one_group(recs[recs["kreis"] == kreis],
                             h[h["kreis"] == kreis], "kreis", kreis, name))
    for st_code, grp in recs.groupby("st_code"):
        out.append(one_group(grp, h[h["ST_CODE"].astype(str) == st_code],
                             "stratum", st_code, grp["st_name"].iloc[0]))
    cols = ["level", "code", "name", "n_unweighted", "n_weighted",
            *STATUS_COLS, "share_income_missing"]
    return pd.DataFrame(out)[cols]


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--raw", type=Path, default=RAW_DEFAULT)
    parser.add_argument("--matrix", type=Path, default=MATRIX_DEFAULT)
    parser.add_argument("--out", type=Path, default=OUT_DEFAULT)
    args = parser.parse_args(argv)
    for path in (args.raw / "SrV2023_Haushalte.csv", args.matrix):
        if not path.exists():
            raise FileNotFoundError(f"required input missing: {path}")
    status_of = load_matrix(args.matrix)
    h = load_households(args.raw)
    h = h.merge(weighted_sizes(args.raw), on="HHNR", how="left")
    table = aggregate(build_status_records(h, status_of), h)
    with open(args.out, "w", encoding="utf-8", newline="") as f:
        f.write(HEADER)
        table.to_csv(f, index=False)
    print(f"wrote {args.out} ({len(table)} rows)")
    print(table[table["level"] == "kreis"].to_string(index=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
