# scripts/extract_mid_ownership_by_rs7_haustyp.py
"""Extract P(count | RegioStaR7 x haustyp) car/bike ownership conditionals from MiD B1.

STANDALONE (pandas only, no braunschweig imports) so it can run on the server where
the raw microdata lives. Universe: households with valid H_GEW (> 0), RegioStaR7 in
71..77, haustyp in {1,2,3,4} (95 'nicht zuzuordnen' excluded, rate logged) and a valid
count value (H_ANZAUTO 0..20 / anzpedrad 0..30; the infas missing code 99 excluded,
rate logged). Weight: H_GEW. anzpedrad = bicycles INCLUDING pedelecs/e-bikes (equals
min(H_ANZRAD + H_ANZPED, 10) on all valid B1 rows, verified 2026-07-08) -- the same
construct as MiD H12.3, the SrV alle-Raeder tables and the seed column
number_of_bicycles. Caps: cars 3+ / bikes 4+, matching the target2026 categories.

Writes (committed): eqasim-data/data/braunschweig/mid/mid2023_{cars,bikes}_by_rs7_haustyp.csv

Usage:
    python scripts/extract_mid_ownership_by_rs7_haustyp.py [--raw <file>] [--out-dir <dir>]
"""
from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(levelname)s [%(name)s] %(message)s")
logger = logging.getLogger("extract_mid_ownership_by_rs7_haustyp")

REPO = Path(__file__).resolve().parents[1]
RAW_DEFAULT = (REPO / "eqasim-data" / "data" / "braunschweig" / "popsim" / "mid2023_raw"
               / "MiD2023_Haushalte.csv")
OUT_DIR_DEFAULT = REPO / "eqasim-data" / "data" / "braunschweig" / "mid"

RS7_CLASSES = tuple(range(71, 78))
HAUSTYP_CLASSES = (1, 2, 3, 4)  # 1 EFH/ZFH, 2 MFH, 3 Geschosswohnungsbau, 4 sonstiges; 95 excluded
CARS_MAX_VALID = 20   # H_ANZAUTO missing code is 99
BIKES_MAX_VALID = 30  # anzpedrad missing code is 99

HEADER_TEMPLATE = """\
# Source: MiD 2023 B1 household microdata (MiD2023_Haushalte.csv, national sample,
#   local-only raw -- never committed). Generated by
#   scripts/extract_mid_ownership_by_rs7_haustyp.py.
# Construct: P({what} | RegioStaR7 x haustyp), H_GEW-weighted shares. haustyp
#   (Gebaeudetyp, Raumbezug Siedlungsblock): 1 Ein-/Zweifamilienhaus, 2 Mehrfamilienhaus,
#   3 Geschosswohnungsbau, 4 sonstiges; code 95 excluded ({ht95_rate:.2f}% of rows).
# Universe: households with H_GEW > 0, RegioStaR7 71..77, haustyp 1..4 and a valid
#   count ({count_col} <= {vmax}; the missing code 99, {invalid_rate:.3f}% of rows, excluded).
# Categories capped at {cap} ({cap_label}), matching the target2026 categories.
# n_unweighted: raw respondent households per (rs7, ht) cell.
# Thinnest cells (lowest n_unweighted): {thin_cells} -- they matter only for rare
#   cell compositions (see the #240 ADR).
"""


def build_ownership_conditional_tables(households: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Aggregate the two RS7 x haustyp ownership conditionals from a B1 household frame.

    Expects columns RegioStaR7, haustyp, H_ANZAUTO, anzpedrad, H_GEW. Returns
    (cars, bikes) with one row per (rs7, ht) and shares summing to 1 per row.
    Raises ValueError if any of the 28 (rs7, ht) cells has no valid household
    (an incomplete conditional would silently break the prior lookup downstream).
    """
    rs7 = pd.to_numeric(households["RegioStaR7"], errors="coerce")
    ht = pd.to_numeric(households["haustyp"], errors="coerce")
    w = pd.to_numeric(households["H_GEW"], errors="coerce")
    base = rs7.isin(RS7_CLASSES) & ht.isin(HAUSTYP_CLASSES) & w.notna() & (w > 0)
    ht95_rate = 100.0 * float((~ht.isin(HAUSTYP_CLASSES)).mean())

    def one(count_col: str, vmax: int, cap: int, prefix: str) -> tuple[pd.DataFrame, float]:
        vals = pd.to_numeric(households[count_col], errors="coerce")
        valid = vals.between(0, vmax)
        invalid_rate = 100.0 * float((~valid & base).sum()) / max(int(base.sum()), 1)
        m = base & valid
        logger.info("[%s] universe: %d households kept; invalid %s rate %.3f%%, haustyp!=1..4 rate %.2f%%",
                    prefix, int(m.sum()), count_col, invalid_rate, ht95_rate)
        g = pd.DataFrame({"rs7": rs7[m].astype(int), "ht": ht[m].astype(int),
                          "v": vals[m].clip(upper=cap).astype(int), "w": w[m]})
        piv = g.pivot_table(index=["rs7", "ht"], columns="v", values="w", aggfunc="sum")
        piv = piv.reindex(columns=range(cap + 1), fill_value=0.0).fillna(0.0)
        missing = [(r, h) for r in RS7_CLASSES for h in HAUSTYP_CLASSES if (r, h) not in piv.index]
        if missing:
            raise ValueError(
                f"build_ownership_conditional_tables[{prefix}]: conditional grid incomplete, "
                f"no valid households for (rs7, ht) cells {missing}; refusing to emit a "
                "partial table (the downstream prior lookup would KeyError or silently skip).")
        shares = piv.div(piv.sum(axis=1), axis=0)
        labels = [str(i) for i in range(cap)] + [f"{cap}plus"]
        shares.columns = [f"{prefix}_{lab}" for lab in labels]
        shares["n_unweighted"] = g.groupby(["rs7", "ht"]).size()
        return shares.reset_index().sort_values(["rs7", "ht"]).reset_index(drop=True), invalid_rate

    cars, cars_invalid = one("H_ANZAUTO", CARS_MAX_VALID, 3, "cars")
    bikes, bikes_invalid = one("anzpedrad", BIKES_MAX_VALID, 4, "bikes")
    cars.attrs["invalid_rate"] = cars_invalid
    bikes.attrs["invalid_rate"] = bikes_invalid
    cars.attrs["ht95_rate"] = ht95_rate
    bikes.attrs["ht95_rate"] = ht95_rate
    return cars, bikes


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--raw", type=Path, default=RAW_DEFAULT)
    parser.add_argument("--out-dir", type=Path, default=OUT_DIR_DEFAULT)
    args = parser.parse_args(argv)
    if not args.raw.exists():
        sys.stderr.write(f"[ownership-conditionals] raw B1 household file not found: {args.raw}\n")
        return 2
    df = pd.read_csv(args.raw, sep=",", encoding="latin-1", low_memory=False,
                     usecols=["RegioStaR7", "haustyp", "H_ANZAUTO", "anzpedrad", "H_GEW"])
    cars, bikes = build_ownership_conditional_tables(df)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    for table, prefix, count_col, vmax, cap, cap_label, what in (
            (cars, "cars", "H_ANZAUTO", CARS_MAX_VALID, 3, "3plus", "number of cars"),
            (bikes, "bikes", "anzpedrad", BIKES_MAX_VALID, 4, "4plus",
             "number of bicycles incl. pedelecs")):
        out = args.out_dir / f"mid2023_{prefix}_by_rs7_haustyp.csv"
        thin = table.nsmallest(2, "n_unweighted")
        thin_cells = "; ".join(
            f"rs7={int(r.rs7)} ht={int(r.ht)} n={int(r.n_unweighted)}" for r in thin.itertuples())
        with open(out, "w", encoding="utf-8", newline="") as handle:
            handle.write(HEADER_TEMPLATE.format(
                what=what, count_col=count_col, vmax=vmax, cap=cap, cap_label=cap_label,
                invalid_rate=table.attrs["invalid_rate"], ht95_rate=table.attrs["ht95_rate"],
                thin_cells=thin_cells))
            table.to_csv(handle, index=False)
        print(f"wrote {out} ({len(table)} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
