"""Extract per-source-Kreis 'direct-ride' PT entry stops for in-commuter home placement.

Reads the cordon MATSim transit schedule and finds, per source Kreis, the stops
that lie on a transit route (rail or bus) which also serves a ZGB stop -- i.e. a
one-seat (no-transfer) ride into the region. PT in-commuters are then placed near
these stops so the transit router yields direct, low-transfer trips. See the
in-commuter mode-reference design spec.

Output: eqasim-data/data/braunschweig/mikrozensus/incommuter_pt_entry_stops.csv
  columns [source_ars5, stop_id, x, y]  (x,y in EPSG:25832, the schedule CRS)
"""
from __future__ import annotations

import argparse, gzip, glob, os, sys
import xml.etree.ElementTree as ET
from pathlib import Path

import geopandas as gpd
from shapely.geometry import Point

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))
from braunschweig.synthesis.incommuters import direct_ride_stops  # noqa: E402
from braunschweig.data.spatial.supply_ring import VG250_REL, VG250_VSI_INNER  # noqa: E402

ZGB = {"03101","03102","03103","03151","03153","03154","03157","03158"}


def parse_schedule(path):
    """Return (stops {id:(x,y)}, routes [(mode,[stop_id,...])])."""
    stops = {}; routes = []
    with gzip.open(path) as fh:
        cur = None; mode = None
        for ev, el in ET.iterparse(fh, events=("start", "end")):
            tag = el.tag.split("}")[-1]
            if ev == "end" and tag == "stopFacility":
                stops[el.get("id")] = (float(el.get("x")), float(el.get("y"))); el.clear()
            elif ev == "start" and tag == "transitRoute":
                cur = []
            elif ev == "end" and tag == "transportMode":
                mode = el.text
            elif ev == "end" and tag == "stop":
                if cur is not None and el.get("refId"):
                    cur.append(el.get("refId"))
            elif ev == "end" and tag == "transitRoute":
                routes.append((mode, cur)); cur = None; mode = None
    return stops, routes


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--schedule", default=None,
                    help="cordon schedule.xml.gz (default: newest under cache_bs supply.processed)")
    ap.add_argument("--data-path", default=str(REPO / "eqasim-data" / "data"))
    ap.add_argument("--out", default=str(REPO / "eqasim-data" / "data" / "braunschweig" /
                                         "mikrozensus" / "incommuter_pt_entry_stops.csv"))
    args = ap.parse_args()
    sched = args.schedule
    if sched is None:
        cands = sorted(glob.glob(str(REPO / "eqasim-data" / "cache_bs" /
                                     "matsim.scenario.supply.processed__*.cache" / "schedule.xml.gz")),
                       key=os.path.getmtime)
        if not cands:
            raise SystemExit("no cordon schedule found; build the cordon supply first or pass --schedule")
        sched = cands[-1]
    print(f"reading schedule: {sched}")
    stops, routes = parse_schedule(sched)
    # map stops to Kreis via VG250
    vsi = "/vsizip/" + os.path.join(args.data_path, VG250_REL) + "/" + VG250_VSI_INNER
    krs = gpd.read_file(vsi, layer="vg250_krs", columns=["ARS", "GF"])
    krs = krs[krs["GF"] == 4].to_crs("EPSG:25832"); krs["ars5"] = krs["ARS"].astype(str).str[:5]
    ids = list(stops)
    pts = gpd.GeoDataFrame(geometry=[Point(stops[i]) for i in ids], crs="EPSG:25832")
    j = gpd.sjoin(pts, krs[["ars5", "geometry"]], predicate="within", how="left")
    stop_kreis = {ids[k]: j.iloc[k]["ars5"] for k in range(len(ids))}
    entry = direct_ride_stops(routes, stop_kreis, ZGB)
    rows = []
    for ars5, sset in sorted(entry.items()):
        for s in sorted(sset):
            x, y = stops[s]; rows.append((ars5, s, x, y))
    import pandas as pd
    df = pd.DataFrame(rows, columns=["source_ars5", "stop_id", "x", "y"])
    header = ("# Per-source-Kreis one-seat-to-ZGB PT entry stops (rail+bus), EPSG:25832. "
              "Generated by scripts/extract_incommuter_pt_entry_stops.py from the cordon transit schedule.\n")
    with open(args.out, "w", encoding="utf-8", newline="") as f:
        f.write(header); df.to_csv(f, index=False)
    print(f"wrote {args.out}: {len(df)} entry stops across {df['source_ars5'].nunique()} source Kreise")


if __name__ == "__main__":
    raise SystemExit(main())
