"""Extract the committed SrV 2023 plan-structure reference table.

Reads the LOCAL-ONLY SrV 2023 "Braunschweig und RGB" scientific-use microdata (persons, trips,
households; cp1252, semicolon, decimal comma) and writes one aggregate table to ``--out-dir``
(default ``eqasim-data/data/braunschweig/srv``):

    srv2023_plan_structure_reference.csv

Definitions live in ``braunschweig.calibration.srv_plan_structure`` (harmonised purposes,
segments, metric set, the two universes). The table is the SrV side of the plan-structure
comparison of issue #369 -- a VALIDATION REFERENCE, not a control target: it describes the
observed daily plan structure (mobility, trip counts, purposes, day closure, timing) per person
segment, against which a synthetic population can be measured with the same metric code. The
file carries a provenance header including an ``# Exclusions:`` line (ruling R9: exclusion
counts must live IN the committed file, produced by the builder, not only in a run log).

Usage (eqasim env, from a worktree; point --raw at the local raw directory):
    python scripts/extract_srv_plan_structure.py \
        --raw C:/Users/bienzeisler/Documents/GitHub/eqasim-bs/eqasim-data/data/braunschweig/srv/srv2023_raw \
        --out-dir eqasim-data/data/braunschweig/srv --source-commit <sha>
"""
from __future__ import annotations

import argparse
import datetime as dt
import logging
import sys
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from braunschweig.calibration import srv_plan_structure as T  # noqa: E402

RAW_DEFAULT = REPO / "eqasim-data" / "data" / "braunschweig" / "srv" / "srv2023_raw"
OUT_DEFAULT = REPO / "eqasim-data" / "data" / "braunschweig" / "srv"
CSV_READ_KWARGS = dict(sep=";", decimal=",", encoding="cp1252", low_memory=False)

# Units of the diagnostics keys (harmonisation_diagnostics), written once into the
# "Exclusions:" header line -- key names alone do not say whether a count is over the FULL raw
# input or over an already-filtered subset.
_EXCLUSIONS_UNITS_NOTE = (
    "(n_persons_raw and n_trips_raw are the raw file row counts; n_persons_negative_weight and "
    "n_trips_negative_weight are measured on those raw rows; n_trips_person_dropped is measured "
    "on the trips surviving the trip-weight filter; every other n_persons_* / n_trips_* count is "
    "measured on the harmonised universe, i.e. on n_persons_universe / n_trips_universe, which "
    "is the at_home_zero universe -- the at_home_only universe excludes exactly the "
    "n_persons_away_from_home persons and their zero trips)"
)

# Headline metrics repeated in the header so the file states its own key numbers (a reader must
# not have to load the table to see whether it is the expected extraction).
_HEADLINE_METRICS = ("mobility_rate", "trips_per_person", "trips_per_mobile_person",
                     "participation_work", "share_trips_followed_by_same_purpose")

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
logger = logging.getLogger("extract_srv_plan_structure")


def _require_columns(path: Path, required: list) -> None:
    """Fail early with the file name and the missing column(s) rather than a bare KeyError."""
    header = pd.read_csv(path, nrows=0, **CSV_READ_KWARGS)
    missing = [c for c in required if c not in header.columns]
    if missing:
        raise ValueError("%s: missing required column(s) %s" % (path, missing))


def _headline(table: pd.DataFrame, universe: str) -> str:
    """One header line with the 'all' segment's key metrics for one universe."""
    rows = table[(table["universe"] == universe) & (table["segment"] == "all")]
    values = rows.set_index("metric")["value"]
    n_unweighted = int(rows["n_unweighted"].iloc[0])
    numbers = ", ".join("%s=%.4f" % (m, values[m]) for m in _HEADLINE_METRICS)
    return "#   %s (n_persons=%d): %s." % (universe, n_unweighted, numbers)


def _header(table: pd.DataFrame, diagnostics: dict, source_commit: str) -> list:
    """Provenance header for the committed plan-structure table."""
    n_segments = table["segment"].nunique()
    n_metrics = table["metric"].nunique()
    purpose_map = ", ".join(
        "%s: %s" % (purpose, "/".join(str(code) for code, p in sorted(T.PURPOSE_BY_V_ZWECK.items())
                                      if p == purpose))
        for purpose in T.PURPOSES)
    lines = [
        "# Source: SrV 2023 Braunschweig + Regionalverband Grossraum Braunschweig scientific-use",
        "#   microdata (local-only, see srv2023_raw/README.md), generated by",
        "#   scripts/extract_srv_plan_structure.py on %s." % dt.date.today().isoformat(),
        "# Code state: eqasim-bs %s, module braunschweig/calibration/srv_plan_structure.py."
        % source_commit,
        "# Table: %s" % T.PLAN_STRUCTURE_TABLE,
        "# Reference for the plan-structure validation of the synthetic population (issue #369):",
        "#   the observed daily plan structure per person segment. VALIDATION REFERENCE, NOT a",
        "#   control target -- no synthesis or location stage reads this file.",
        "# Long format: one row per (universe, segment, metric). 'n_unweighted' repeats the",
        "#   segment's unweighted person count on every one of its rows.",
        "# Universes (both are emitted; at_home_zero is the primary one):",
        "#   at_home_zero  = every delivered person with a valid GEWICHT_P_ZENSUS; the per-person",
        "#     trip count is E_ANZ_WEGE2, which counts a person who was away from home over the",
        "#     whole reporting day (E_ANZ_WEGE == -7) as 0 trips. This matches a synthetic",
        "#     population, in which every person exists and starts the day at home.",
        "#   at_home_only  = sensitivity; only persons with E_ANZ_WEGE >= 0, i.e. away-from-home",
        "#     persons excluded entirely. In this delivery -7 is the only negative E_ANZ_WEGE",
        "#     code, so the two universes differ by exactly the",
        "#     n_persons_away_from_home persons of the Exclusions line.",
        "# Weights: GEWICHT_P_ZENSUS for person-level metrics, GEWICHT_W_ZENSUS for trip-level",
        "#   metrics (expansion to Zensus 2022 counts; the stratum-internal GEWICHT_P/GEWICHT_W",
        "#   must not be used across strata, ADR-0055).",
        "# Universe guards (the extraction raises rather than adapting): every STICHTAG_WTAG in",
        "#   %s (pure Tuesday-Thursday delivery) and GEWICHT_P_WERKTAG == %s everywhere."
        % (list(T.EXPECTED_STICHTAG_WTAG), T.EXPECTED_GEWICHT_P_WERKTAG),
        "#   The reconstructed per-person trip count is checked against the delivered",
        "#   E_ANZ_WEGE2 for every person (a mismatch raises).",
        "# Purpose map (V_ZWECK / E_START_ZWECK -> harmonised purpose): %s." % purpose_map,
        "#   V_ZWECK == -10 (and E_START_ZWECK == -7) -> 'unknown': such trips ARE counted as",
        "#   trips (n_trips, trips_per_person, trip-count distribution) but are EXCLUDED from the",
        "#   denominator of purpose_share_*, so the seven purpose shares sum to 1.0; their weight",
        "#   is reported separately as share_trips_unknown_purpose.",
        "# Segments: all; age_<band> for %s; group_<g> for %s (employment x life phase, defined"
        % (list(T.AGE_LABELS), list(T.GROUPS)),
        "#   so that a synthetic population without a pupil/student flag can express it: employed",
        "#   wins, the non-employed are split by age); sex_male / sex_female (V_GESCHLECHT 3",
        "#   'divers' and 4 'no answer' are in no sex segment); kreis_<ars5> for the 7 surveyed",
        "#   Kreise (Wolfsburg 03103 is NOT surveyed by SrV and has no row here).",
        "# Metric definitions: mobility_rate = weighted share of persons with >= 1 trip;",
        "#   trips_per_person / trips_per_mobile_person = weighted mean trip count (all persons /",
        "#   mobile persons); share_trips_<k> = weighted share of persons with exactly k trips",
        "#   (share_trips_8plus = 8 or more); participation_<p> = weighted share of persons with",
        "#   >= 1 trip to purpose p; trips_per_person_<p> = weighted mean number of such trips;",
        "#   purpose_share_<p> = weighted share of the segment's known-purpose trips;",
        "#   share_trips_home_based = weighted share of trips starting OR ending at home;",
        "#   tours_per_mobile = weighted mean number of home returns of mobile persons;",
        "#   share_mobile_first_from_home / share_mobile_last_to_home = weighted share of mobile",
        "#   persons whose first trip starts at home / whose last trip ends at home;",
        "#   share_mobile_odd_trip_count = weighted share of mobile persons with an odd trip",
        "#   count (a day that cannot consist of closed home tours);",
        "#   share_trips_followed_by_same_purpose = weighted share of ALL trips of the segment",
        "#   whose next trip (same person) has the same harmonised purpose (consecutive",
        "#   activities of one type; a pair of unknown purposes never counts);",
        "#   mean_work_activity_h / share_work_activities_lt_2h = weighted mean duration and",
        "#   weighted share below 2 h of the work activity following a trip TO work (next",
        "#   departure minus arrival), measurable only when a further trip follows and only for",
        "#   durations in [0, %g] h -- n_work_activities_measured gives the surviving count;"
        % T.WORK_ACTIVITY_MAX_H,
        "#   dep_hour_share_<purpose|all>_<h> = weighted share of that purpose's trips with a",
        "#   valid departure time departing in hour h, for h in %d..%d (hours are clipped into"
        % (T.DEPARTURE_HOURS[0], T.DEPARTURE_HOURS[-1]),
        "#   %s, so the 20 reported hours need not sum to 1); n_persons_unweighted /"
        % list(T.HOUR_CLIP),
        "#   n_persons_weighted = the segment's person count and expanded person count.",
        "# An empty segment carries NaN values (never a dropped row), so a consumer never has to",
        "#   guess whether a segment is missing or empty.",
        "# Coverage caveat: stratified PSU design over ~44 selected municipalities; per-Kreis rows",
        "#   represent the covered municipalities (ASSUMPTION-grade for the full Kreis).",
        "# Headline ('all' segment):",
        _headline(table, T.UNIVERSE_AT_HOME_ZERO),
        _headline(table, T.UNIVERSE_AT_HOME_ONLY),
        "# Rows: %d segments x %d metrics x %d universes = %d."
        % (n_segments, n_metrics, len(T.UNIVERSES), len(table)),
        "# Exclusions: " + ", ".join("%s=%s" % (k, v) for k, v in diagnostics.items()) + " "
        + _EXCLUSIONS_UNITS_NOTE,
    ]
    return lines


def _write(df: pd.DataFrame, path: Path, header: list) -> None:
    """Write the provenance-headed CSV. ``lineterminator="\\n"`` keeps the data rows LF-only
    regardless of platform; ``float_format="%.10g"`` keeps floats readable while staying
    lossless at the precision the shares carry."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as fh:
        for line in header:
            fh.write(line + "\n")
        df.to_csv(fh, index=False, lineterminator="\n", float_format="%.10g")
    logger.info("wrote %s (%d rows)", path, len(df))


def _check_invariants(table: pd.DataFrame) -> None:
    """Invariants that would silently corrupt the reference if violated.

    1. Both universes are present with the identical (segment, metric) grid -- Task 10 compares
       by name, so a hole would turn into a missing comparison rather than an error.
    2. The seven purpose shares sum to 1.0 in every segment that has trips (this is what the
       unknown-purpose exclusion from the denominator buys; a segment without trips has NaN).
    3. Every share-like metric is inside [0, 1] where it is not NaN.
    """
    universes = sorted(table["universe"].unique())
    if universes != sorted(T.UNIVERSES):
        raise ValueError("expected universes %s, found %s" % (sorted(T.UNIVERSES), universes))
    grids = {u: set(map(tuple, table[table["universe"] == u][["segment", "metric"]].values))
             for u in universes}
    if grids[universes[0]] != grids[universes[1]]:
        raise ValueError("the two universes do not carry the identical (segment, metric) grid")

    shares = table[table["metric"].isin(["purpose_share_%s" % p for p in T.PURPOSES])]
    totals = shares.groupby(["universe", "segment"])["value"].sum()
    populated = totals[totals.notna() & (totals != 0.0)]
    off = populated[(populated - 1.0).abs() > 1e-9]
    if len(off):
        raise ValueError("purpose shares do not sum to 1.0 for %d segment(s): %s"
                         % (len(off), off.head().to_dict()))

    share_like = table[table["metric"].str.startswith(("share_", "participation_", "purpose_share_",
                                                       "mobility_rate", "dep_hour_share_"))]
    bad = share_like[share_like["value"].notna()
                     & ((share_like["value"] < -1e-9) | (share_like["value"] > 1 + 1e-9))]
    if len(bad):
        raise ValueError("%d share-like value(s) outside [0, 1], e.g. %s"
                         % (len(bad), bad.head().to_dict("records")))


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--raw", default=str(RAW_DEFAULT),
                        help="SrV raw directory (local-only; must contain SrV2023_Personen.csv, "
                             "SrV2023_Wege.csv, SrV2023_Haushalte.csv)")
    parser.add_argument("--out-dir", default=str(OUT_DEFAULT),
                        help="Directory to write the committed table into")
    parser.add_argument("--source-commit", default="unknown",
                        help="git commit hash of this worktree, recorded in the provenance "
                             "header for reproducibility (CLAUDE.md scientific-reproducibility "
                             "rule)")
    args = parser.parse_args(argv)

    raw = Path(args.raw)
    for name in ("SrV2023_Personen.csv", "SrV2023_Wege.csv", "SrV2023_Haushalte.csv"):
        if not (raw / name).exists():
            raise FileNotFoundError("SrV raw file missing: %s" % (raw / name))
    _require_columns(raw / "SrV2023_Personen.csv", T.PERSON_COLUMNS)
    _require_columns(raw / "SrV2023_Wege.csv", T.TRIP_COLUMNS)
    _require_columns(raw / "SrV2023_Haushalte.csv", T.HOUSEHOLD_COLUMNS)

    raw_persons = pd.read_csv(raw / "SrV2023_Personen.csv", usecols=T.PERSON_COLUMNS,
                              **CSV_READ_KWARGS)
    raw_trips = pd.read_csv(raw / "SrV2023_Wege.csv", usecols=T.TRIP_COLUMNS, **CSV_READ_KWARGS)
    households = pd.read_csv(raw / "SrV2023_Haushalte.csv", usecols=T.HOUSEHOLD_COLUMNS,
                             **CSV_READ_KWARGS)
    logger.info("read %d persons, %d trips, %d households", len(raw_persons), len(raw_trips),
                len(households))

    persons, trips = T.harmonise_srv(raw_persons, raw_trips, households)
    diagnostics = T.harmonisation_diagnostics(raw_persons, raw_trips, persons, trips)
    logger.info("harmonisation diagnostics: %s", diagnostics)

    table = pd.concat([T.build_reference(persons, trips, universe=universe)
                       for universe in T.UNIVERSES], ignore_index=True)
    _check_invariants(table)

    for universe in T.UNIVERSES:
        logger.info("%s", _headline(table, universe).lstrip("# "))

    out = Path(args.out_dir)
    _write(table, out / T.PLAN_STRUCTURE_TABLE, _header(table, diagnostics, args.source_commit))
    return 0


if __name__ == "__main__":
    sys.exit(main())
