"""Extract the MiD 2023 reporting-day work-location reference tables (run on the run server).

Raw MiD 2023 microdata (SUF, comma-separated) lives ONLY on the run server under
``eqasim-data/data/braunschweig/popsim/mid2023_raw/``. This script reads the person and trip
files and writes two small aggregates with provenance headers:

    mid2023_workday_location_by_commute_distance.csv   (spec 2026-09-04 Section 2.1)
    mid2023_home_office_donor_pool.csv                  (spec Section 2.2)

Usage (felix, conda env eqasim, from the repository/worktree root):
    python scripts/extract_mid_workday_location.py --raw eqasim-data/data/braunschweig/popsim/mid2023_raw \
        --out-dir eqasim-data/data/braunschweig/mid
"""
from __future__ import annotations

import argparse
import datetime as dt
import logging
import sys
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from braunschweig.calibration import commute_day_state_reference as R  # noqa: E402

PERSON_COLUMNS = ["HP_ID", "H_ID", "P_GEW", "arbwo", "M_HOFF", "P_STARB1", "starb2", "P_ARB_ENTF",
                  "HP_ALTER", "HP_SEX"]
TRIP_COLUMNS = ["HP_ID", "W_ZWECK"]

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
logger = logging.getLogger("extract_mid_workday_location")


def _header(table: str, extra: list[str]) -> list[str]:
    return [
        "# Source: MiD 2023 scientific-use microdata (SUF B1, infas/DLR/IVT/infas 360), server-only raw",
        f"#   files MiD2023_Personen.csv / MiD2023_Wege.csv; generated by scripts/extract_mid_workday_location.py on {dt.date.today().isoformat()}.",
        f"# Table: {table}",
        "# Universe (ruling R4): arbwo == 1 (reporting day is a weekday) AND M_HOFF == 1 (asked the",
        "#   home-office module) AND P_STARB1 in (1, 2, 9) (worked / did not work / no answer). The",
        "#   module/weekday filter alone still keeps ~100k not-applicable, filter-coded persons",
        "#   (P_STARB1 codes such as 202/206/402/404/407 mean 'not employed'/'not asked'); the",
        "#   P_STARB1 filter removes them -- see _mid_universe in commute_day_state_reference.py.",
        "# States (ruling R4): did_not_work = P_STARB1 == 2; missing = P_STARB1 == 9 (no answer) or",
        "#   an unmapped starb2 code (e.g. 99) among P_STARB1 == 1 workers; at_workplace = P_STARB1",
        "#   == 1 & starb2 == 2; at_home = P_STARB1 == 1 & starb2 == 1; other_place = P_STARB1 == 1",
        "#   & starb2 in (3, 4, 5, 96).",
        "# Weight: P_GEW (person weight). Distance: P_ARB_ENTF (ruling R5) cleaned by",
        "#   clean_mid_commute_distance_km in the module -- codes 996, 999 and every value >= 1000",
        "#   (MiD filter/skip codes, e.g. 2202/2206/4402/4404/4407) become missing (counted in",
        "#   n_missing_distance, excluded from class rows); 200.0 is a legitimate top-code, classed",
        "#   100_200.",
        "# Classes (km): lt10 [0,10), 10_25, 25_50, 50_100, 100_200 (incl. the 200 top-code); gt200 cannot occur in MiD.",
        "# Purpose: reference for the commute-day-state model (spec 2026-09-04); NOT a control target.",
    ] + [f"# {line}" for line in extra]


def _write(df: pd.DataFrame, path: Path, header: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as fh:
        for line in header:
            fh.write(line + "\n")
        df.to_csv(fh, index=False, lineterminator="\n", float_format="%.10g")
    logger.info("wrote %s (%d rows)", path, len(df))


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--raw", required=True, help="directory with MiD2023_Personen.csv and MiD2023_Wege.csv")
    parser.add_argument("--out-dir", default=str(REPO / "eqasim-data" / "data" / "braunschweig" / "mid"))
    args = parser.parse_args(argv)
    raw = Path(args.raw)
    for name in ("MiD2023_Personen.csv", "MiD2023_Wege.csv"):
        if not (raw / name).exists():
            raise FileNotFoundError(f"MiD raw file missing: {raw / name}")
    persons = pd.read_csv(raw / "MiD2023_Personen.csv", usecols=PERSON_COLUMNS, low_memory=False)
    trips = pd.read_csv(raw / "MiD2023_Wege.csv", usecols=TRIP_COLUMNS, low_memory=False)
    logger.info("read %d persons, %d trips", len(persons), len(trips))
    out = Path(args.out_dir)
    table = R.build_mid_workday_location_table(persons)
    _write(table, out / R.WORKDAY_LOCATION_TABLE, _header(R.WORKDAY_LOCATION_TABLE,
           ["Columns: distance_class, n_unweighted, n_missing_distance (all row only), share_at_workplace,",
            "share_at_home, share_did_not_work, share_other_place, share_missing (weighted row shares, sum 1)."]))
    pool = R.build_mid_home_office_donor_pool(persons, trips)
    _write(pool, out / R.HOME_OFFICE_DONOR_POOL_TABLE, _header(R.HOME_OFFICE_DONOR_POOL_TABLE,
           ["Pool: weekday module persons who worked (P_STARB1 == 1) at home (starb2 == 1).",
            "has_children = any household member aged <= 13; has_active_escort = any trip with W_ZWECK == 6",
            "(Bringen/Holen); 'all' marks totals. n_mobile = donors with >= 1 trip; mean_trips_mobile over them;",
            "share_female weighted by P_GEW. Purpose: cell-size diagnostics for the home-office plan donor matching."]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
