"""Extract the MiD 2023 commute mode-by-distance joint (national) into committed CSVs.

Source: MiD 2023 "Mobilitaet in Tabellen" (MiT 2023) tool export
(eqasim-data/data/braunschweig/mikrozensus/mid2023_berufliche_wege_mode_by_distance_de.xlsx).
Filter: Auswertung Wege; Zeile = regelmaessiger beruflicher Weg; Spalte =
Hauptverkehrsmittel (fehlende Werte imputiert); Untergliederung = Wegelaenge km
in Gruppen; Zeilen-%. We use the "regelmaessiger beruflicher Weg" (rbW) row;
MIV-Mitfahrer is folded ("-") so car = MIV-Fahrer (see the design spec, D-2).

Writes:
  mid2023_commute_mode_by_distance_de.csv  [distance_band, mode, probability]
  mid2023_commute_distance_de.csv          [distance_band, base_weighted, share]
"""
from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[1]
MZ_DIR = REPO / "eqasim-data" / "data" / "braunschweig" / "mikrozensus"
DEFAULT_XLSX = MZ_DIR / "mid2023_berufliche_wege_mode_by_distance_de.xlsx"

_BAND_LABELS = [
    ("unter 0,5", "<0.5"), ("0,5 bis unter 1", "0.5-1"), ("1 bis unter 2", "1-2"),
    ("2 bis unter 5", "2-5"), ("5 bis unter 10", "5-10"), ("10 bis unter 20", "10-20"),
    ("20 bis unter 50", "20-50"), ("50 bis unter 100", "50-100"), ("100 km und mehr", ">=100"),
]
_MODE_MAP = {
    "zu Fuss": "walk", "zu Fuß": "walk", "Fahrrad": "bicycle",
    "MIV (Mitfahrer/in)": None, "MIV (Fahrer/in)": "car", "OePV": "pt", "ÖPV": "pt",
}


def _band_key(text: str):
    for needle, key in _BAND_LABELS:
        if needle in text:
            return key
    return None


def _pct(cell) -> float:
    s = str(cell).replace("%", "").replace(",", ".").strip()
    if s in ("", "-", "/", "nan"):
        return 0.0
    return float(s)


def _num(cell) -> float:
    s = str(cell).replace(".", "").replace(",", ".").strip()
    return float(s) if s not in ("", "-", "/", "nan") else 0.0


def parse_mit_rbw_sheet(df_raw: pd.DataFrame):
    """Parse the raw MiT sheet (header=None) -> (tidy_modes, distance_distribution).

    Walks the rows: remembers the current band (from the Wegelaenge label line)
    and the current mode-column header, and reads the "regelmaessiger
    beruflicher Weg" data row in each block. Returns:
      tidy_modes: DataFrame[distance_band, mode, probability] (4 modes, per-band sum 1)
      distance:   DataFrame[distance_band, base_weighted, share]
    """
    band = None
    header = None
    mode_rows, dist_rows = [], []
    for _, row in df_raw.iterrows():
        cells = [("" if pd.isna(c) else str(c)) for c in row.tolist()]
        first = cells[0].strip()
        if "Wegelaenge in Gruppen" in first or "Wegelänge in Gruppen" in first:
            band = _band_key(first)
            header = None
            continue
        if len(cells) > 1 and "Basis gewichtet" in cells[1]:
            header = cells
            continue
        if first.startswith("regelmaessiger beruflicher Weg") or first.startswith("regelmäßiger beruflicher Weg"):
            if band is None or header is None:
                continue
            # Skip the section-heading row "regelmäßiger beruflicher Weg (rbW)" which has
            # no numeric data in cells[1]; only the actual data row carries a base count.
            if not cells[1].strip():
                continue
            base_w = _num(cells[1])
            dist_rows.append({"distance_band": band, "base_weighted": base_w})
            acc = {}
            for col in range(3, len(header)):
                mode = _MODE_MAP.get(header[col].strip())
                if mode is None:
                    continue
                acc[mode] = acc.get(mode, 0.0) + _pct(cells[col])
            total = sum(acc.values())
            for mode, v in acc.items():
                mode_rows.append({"distance_band": band, "mode": mode,
                                  "probability": (v / total) if total else 0.0})
    tidy = pd.DataFrame(mode_rows)
    dist = pd.DataFrame(dist_rows)
    dist["share"] = dist["base_weighted"] / dist["base_weighted"].sum()
    return tidy, dist


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--xlsx", type=Path, default=DEFAULT_XLSX)
    ap.add_argument("--out-dir", type=Path, default=MZ_DIR)
    args = ap.parse_args()
    raw = pd.read_excel(args.xlsx, sheet_name=0, header=None)
    tidy, dist = parse_mit_rbw_sheet(raw)
    header = ("# MiD 2023 'Mobilitaet in Tabellen', rbW row, Hauptverkehrsmittel x "
              "wegkm_imp groups. Generated by scripts/extract_mit_commute_mode_by_distance.py\n")
    p1 = args.out_dir / "mid2023_commute_mode_by_distance_de.csv"
    p2 = args.out_dir / "mid2023_commute_distance_de.csv"
    with p1.open("w", encoding="utf-8", newline="") as f:
        f.write(header)
        tidy.to_csv(f, index=False)
    with p2.open("w", encoding="utf-8", newline="") as f:
        f.write(header)
        dist[["distance_band", "base_weighted", "share"]].to_csv(f, index=False)
    print(f"wrote {p1} ({len(tidy)} rows), {p2} ({len(dist)} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
