"""Extract the two committed SrV 2023 full-day absence aggregates (issue #370, sub-project B).

Reads the LOCAL-ONLY SrV 2023 "Braunschweig und RGB" scientific-use microdata (persons,
households; cp1252, semicolon, decimal comma) and writes two small aggregate tables to
``--out-dir`` (default ``eqasim-data/data/braunschweig/srv``):

    srv2023_absence_by_age_band.csv           (share of persons away from home the whole
                                               reporting day, per age band, GEWICHT_P_ZENSUS)
    srv2023_absence_household_by_size.csv     (share of households in which EVERY member is
                                               away, per household size class, GEWICHT_HH_ZENSUS)

Both are a VALIDATION-ANCHORED DRAW REFERENCE for the general-day-absence state draw of
``braunschweig.synthesis.day_absence`` -- NOT a PopulationSim control target: no synthesis or
location stage's demand distribution is controlled to these shares, they only parameterise a
per-person / per-household absence draw. All definitions -- the universe, the age bands, the
household size classes, the guards -- live in ``braunschweig.calibration.srv_absence``; this
script owns only the raw I/O, the CLI and the provenance header. Each written file carries the
diagnostics produced by the builder, so the exclusion counts live IN the committed file and not
only in a run log.

Usage (eqasim env, from a worktree; point --raw at the local raw directory):
    python scripts/extract_srv_absence.py \
        --raw C:/Users/bienzeisler/Documents/GitHub/eqasim-bs/eqasim-data/data/braunschweig/srv/srv2023_raw \
        --out-dir eqasim-data/data/braunschweig/srv --source-commit <sha>
"""
from __future__ import annotations

import argparse
import datetime as dt
import logging
import sys
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from braunschweig.calibration import srv_absence as A  # noqa: E402

RAW_DEFAULT = REPO / "eqasim-data" / "data" / "braunschweig" / "srv" / "srv2023_raw"
OUT_DEFAULT = REPO / "eqasim-data" / "data" / "braunschweig" / "srv"
CSV_READ_KWARGS = dict(sep=";", decimal=",", encoding="cp1252", low_memory=False)

PERSONS_FILE = "SrV2023_Personen.csv"
HOUSEHOLDS_FILE = "SrV2023_Haushalte.csv"

# Units of the diagnostics keys, written once into each header's "Diagnostics:" line: the key
# names alone do not say whether a count is measured over the FULL raw Personen file or over an
# already-filtered subset (same note as scripts/extract_srv_participation_universe.py).
_DIAGNOSTICS_UNITS_NOTE = (
    "(n_persons_raw is the raw Personen-file row count; n_persons_dropped_weight is measured on "
    "it; n_persons_universe is the resulting count with a valid positive GEWICHT_P_ZENSUS; "
    "n_absent and n_persons_missing_age are measured on n_persons_universe)"
)

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
logger = logging.getLogger("extract_srv_absence")


def _require_columns(path: Path, required: list) -> None:
    """Fail early with the file name and the missing column(s) rather than a bare KeyError."""
    header = pd.read_csv(path, nrows=0, **CSV_READ_KWARGS)
    missing = [c for c in required if c not in header.columns]
    if missing:
        raise ValueError("%s: missing required column(s) %s" % (path, missing))


def _common_header(table_name: str, diagnostics: dict, source_commit: str) -> list:
    """Provenance lines shared by both tables (source, role, universe, bands, guards)."""
    band_bounds = ", ".join("%s: %d-%d" % (band, lo, hi)
                            for band, (lo, hi) in A.AGE_BAND_BOUNDS.items())
    return [
        "# Source: SrV 2023 Braunschweig + Regionalverband Grossraum Braunschweig scientific-use",
        "#   microdata (local-only, see srv2023_raw/README.md; files %s, %s), generated by"
        % (PERSONS_FILE, HOUSEHOLDS_FILE),
        "#   scripts/extract_srv_absence.py on %s." % dt.date.today().isoformat(),
        "# Code state: eqasim-bs %s, module braunschweig/calibration/srv_absence.py."
        % source_commit,
        "# Table: %s" % table_name,
        "# Role: VALIDATION-ANCHORED DRAW REFERENCE for braunschweig.synthesis.day_absence; not",
        "#   a PopulationSim control target -- no synthesis or location stage's demand",
        "#   distribution is controlled to these shares, they parameterise the",
        "#   general-day-absence state draw only.",
        "# Universe: every delivered person with a valid positive GEWICHT_P_ZENSUS (the",
        "#   at_home_zero universe of braunschweig.calibration.srv_plan_structure -- absence IS",
        "#   the state being measured here, so away persons are KEPT, unlike the",
        "#   participation-universe tables of issue #368, which exclude them).",
        "# Away from home: E_ANZ_WEGE == %d over the WHOLE reporting day (the only negative"
        % A.AWAY_FROM_HOME_CODE,
        "#   E_ANZ_WEGE code this delivery carries).",
        "# Weights: GEWICHT_P_ZENSUS (persons) / GEWICHT_HH_ZENSUS (households); expansion to",
        "#   Zensus 2022 counts, the stratum-internal GEWICHT_P/GEWICHT_HH must not be used",
        "#   across strata (ADR-0055).",
        "# Age bands (V_ALTER, bounds INCLUSIVE): %s." % band_bounds,
        "# Universe guards (the extraction raises, it never adapts): every MITTL_WERKTAG == %d"
        % A.AVERAGE_WEEKDAY,
        "#   (average-weekday Tuesday-Thursday delivery) and every negative E_ANZ_WEGE == %d."
        % A.AWAY_FROM_HOME_CODE,
        "# Diagnostics: n_persons_raw=%d, n_persons_dropped_weight=%d, n_persons_universe=%d,"
        % (diagnostics["n_persons_raw"], diagnostics["n_persons_dropped_weight"],
           diagnostics["n_persons_universe"]),
        "#   n_absent=%d, n_persons_missing_age=%d. %s"
        % (diagnostics["n_absent"], diagnostics["n_persons_missing_age"],
           _DIAGNOSTICS_UNITS_NOTE),
    ]


def _age_header(table: pd.DataFrame, diagnostics: dict, source_commit: str) -> list:
    """Provenance header for the absence-by-age-band table."""
    lines = _common_header(A.ABSENCE_BY_AGE_TABLE, diagnostics, source_commit)
    all_row = table[table["band"] == A.ALL_BAND].iloc[0]
    lines += [
        "# Columns: band (%s + 'all'), age_min, age_max (INCLUSIVE bounds; the 'all' row spans"
        % list(A.AGE_BAND_LABELS),
        "#   0-200), n_unweighted, n_absent_unweighted, p_absent (weighted share of the band away",
        "#   the whole reporting day). Every band is emitted even if empty (n_unweighted=0,",
        "#   p_absent=NaN), so a consumer never has to guess whether a band is missing or empty.",
        "# 'all' row (n_unweighted=%d): n_absent_unweighted=%d, p_absent=%.4f."
        % (int(all_row["n_unweighted"]), int(all_row["n_absent_unweighted"]), all_row["p_absent"]),
        "# Rows: %d bands + 1 'all' row = %d total." % (len(A.AGE_BAND_LABELS), len(table)),
        "# Invariants (checked before writing, the extraction raises on a violation): exactly the",
        "#   bands %s + 'all' are present, in that order; the band person counts sum to at most"
        % list(A.AGE_BAND_LABELS),
        "#   the 'all' row's n_unweighted; every share is NaN or inside [0, 1].",
    ]
    return lines


def _size_header(table: pd.DataFrame, diagnostics: dict, source_commit: str) -> list:
    """Provenance header for the absence-household-by-size table."""
    lines = _common_header(A.ABSENCE_HOUSEHOLD_TABLE, diagnostics, source_commit)
    lines += [
        "# Household size classes: 1..%d, class %d = '%d or more' members."
        % (A.HOUSEHOLD_SIZE_CLASS_TOP, A.HOUSEHOLD_SIZE_CLASS_TOP, A.HOUSEHOLD_SIZE_CLASS_TOP),
        "# Columns: size_class, n_households_unweighted, n_all_absent_unweighted, p_all_absent",
        "#   (weighted GEWICHT_HH_ZENSUS share of the size class's households in which EVERY",
        "#   member is away the whole reporting day). Because this table is weighted by the",
        "#   HOUSEHOLD weight rather than the person weight of the by-age table, its shares",
        "#   differ slightly from the person-weighted household-composition figures quoted",
        "#   elsewhere for the same universe; the values below are the ones this file commits.",
        "#   A size class with no household is still emitted, with n_households_unweighted=0 and",
        "#   a NaN share (never dropped).",
    ]
    lines += ["#   size %d: n_households_unweighted=%d, p_all_absent=%s"
              % (int(row["size_class"]), int(row["n_households_unweighted"]),
                 "NaN" if pd.isna(row["p_all_absent"]) else "%.4f" % row["p_all_absent"])
              for _, row in table.iterrows()]
    lines += [
        "# Rows: %d size classes." % len(table),
        "# Invariants (checked before writing, the extraction raises on a violation): size",
        "#   classes 1..%d are present, in that order; every share is NaN or inside [0, 1]."
        % A.HOUSEHOLD_SIZE_CLASS_TOP,
    ]
    return lines


def _write(df: pd.DataFrame, path: Path, header: list) -> None:
    """Write the provenance-headed CSV. ``lineterminator="\\n"`` keeps the data rows LF-only
    regardless of platform; ``float_format="%.10g"`` keeps floats readable while staying
    lossless at the precision the shares carry."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as fh:
        for line in header:
            fh.write(line + "\n")
        df.to_csv(fh, index=False, lineterminator="\n", float_format="%.10g")
    logger.info("wrote %s (%d rows)", path, len(df))


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--raw", type=Path, default=RAW_DEFAULT)
    parser.add_argument("--out-dir", type=Path, default=OUT_DEFAULT)
    parser.add_argument("--source-commit", required=True)
    args = parser.parse_args(argv)
    persons_path, households_path = args.raw / "SrV2023_Personen.csv", args.raw / "SrV2023_Haushalte.csv"
    _require_columns(persons_path, A.PERSON_COLUMNS)
    _require_columns(households_path, A.HOUSEHOLD_COLUMNS)
    persons = pd.read_csv(persons_path, usecols=A.PERSON_COLUMNS, **CSV_READ_KWARGS)
    households = pd.read_csv(households_path, usecols=A.HOUSEHOLD_COLUMNS, **CSV_READ_KWARGS)
    logger.info("read %d persons, %d households", len(persons), len(households))
    prepared, diagnostics = A.prepare_absence_persons(persons)
    by_age = A.build_absence_by_age_band(prepared)
    by_size = A.build_absence_household_by_size(prepared, households)
    A.check_invariants(by_age, by_size)
    logger.info("invariants passed; diagnostics: %s", diagnostics)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    _write(by_age, args.out_dir / A.ABSENCE_BY_AGE_TABLE, _age_header(by_age, diagnostics, args.source_commit))
    _write(by_size, args.out_dir / A.ABSENCE_HOUSEHOLD_TABLE, _size_header(by_size, diagnostics, args.source_commit))
    return 0


if __name__ == "__main__":
    sys.exit(main())
