"""
Extract SrV 2023 person trip-class tables (number of reported trips on the
mittlerer Werktag): per Kreis/stratum, and by age band region-wide.

Universe (VERIFIED for this SciUse delivery; the script re-validates and
raises if violated): all person reporting days are Tue-Thu
(STICHTAG_WTAG in {2,3,4}) and GEWICHT_P_WERKTAG is -6 for every row, i.e.
the file as a whole IS the mittlerer-Werktag universe -> weight GEWICHT_P.

Classes {0, 1-2, 3-4, 5+} from E_ANZ_WEGE; E_ANZ_WEGE == -7 ("Berechnung
nicht moeglich", incl. persons away from home on the reporting day) is
excluded from the shares and reported per group as share_trips_invalid.

MiD comparability caveat: MiD trip counts cover ALL days and apply an
immobile-persons adjustment (handbook p.21); do NOT blend these tables with
a MiD P39 extraction until that extraction is restricted to a comparable
workday universe.

Writes:
    eqasim-data/data/braunschweig/srv/srv2023_trip_classes_by_kreis.csv
    eqasim-data/data/braunschweig/srv/srv2023_trip_classes_by_age.csv

Usage:
    python scripts/extract_srv_trip_classes_kreis.py [--raw <dir>] [--out-dir <dir>]
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
log = logging.getLogger("srv_trip_classes")

REPO = Path(__file__).resolve().parents[1]
RAW_DEFAULT = REPO / "eqasim-data" / "data" / "braunschweig" / "srv" / "srv2023_raw"
OUT_DEFAULT = REPO / "eqasim-data" / "data" / "braunschweig" / "srv"

CLS_COLS = ["trips_0", "trips_1_2", "trips_3_4", "trips_5plus"]
CLS_BINS = [-0.5, 0.5, 2.5, 4.5, float("inf")]
AGE_BANDS = [(0, 17), (18, 29), (30, 49), (50, 64), (65, 74), (75, 120)]
KREIS_NAMES = {"03101": "Braunschweig", "03102": "Salzgitter",
               "03151": "Gifhorn", "03153": "Goslar", "03154": "Helmstedt",
               "03157": "Peine", "03158": "Wolfenbuettel"}

HEADER = """\
# Source: SrV 2023 Braunschweig+RGB scientific-use microdata (local-only, see
#   srv2023_raw/README.md), generated by scripts/extract_srv_trip_classes_kreis.py.
# Universe: ALL persons of the delivery = mittlerer-Werktag reporting days
#   (verified: STICHTAG_WTAG only Tue-Thu; GEWICHT_P_WERKTAG undefined (-6)
#   throughout, hence weight = GEWICHT_P >= 0).
# Classes from E_ANZ_WEGE: 0 / 1-2 / 3-4 / 5+ trips on the reporting day;
#   E_ANZ_WEGE = -7 (not computable, incl. persons away from home) excluded
#   from shares, reported as share_trips_invalid.
# CAVEAT: NOT directly comparable to MiD trip rates (MiD: all days + immobile
#   adjustment); SrV-only candidate target until a workday-matched MiD P39
#   extraction exists.
# ASSUMPTION (PSU design): per-Kreis rows aggregate a stratified selected-
#   municipality sample; per-stratum (ST_CODE) rows are the design-safe level.
"""


def load_persons(raw_dir: Path) -> pd.DataFrame:
    h = pd.read_csv(raw_dir / "SrV2023_Haushalte.csv", sep=";", decimal=",",
                    encoding="cp1252", low_memory=False,
                    usecols=["HHNR", "AGS", "ST_CODE", "ST_CODE_NAME"])
    h["kreis"] = h["AGS"].astype(str).str.zfill(8).str[:5]
    p = pd.read_csv(raw_dir / "SrV2023_Personen.csv", sep=";", decimal=",",
                    encoding="cp1252", low_memory=False,
                    usecols=["HHNR", "V_ALTER", "E_ANZ_WEGE", "GEWICHT_P",
                             "GEWICHT_P_WERKTAG", "STICHTAG_WTAG"])
    p = p.merge(h, on="HHNR", how="left")

    # Universe validations (fail fast if a future delivery differs).
    wtag = pd.to_numeric(p["STICHTAG_WTAG"], errors="coerce")
    if not wtag.isin([2, 3, 4]).all():
        raise ValueError("STICHTAG_WTAG outside Tue-Thu found: the delivery is "
                         "no longer a pure mittlerer-Werktag file; revisit the "
                         "weight/universe choice in this script.")
    wgw = pd.to_numeric(p["GEWICHT_P_WERKTAG"], errors="coerce")
    if not (wgw == -6).all():
        raise ValueError("GEWICHT_P_WERKTAG is no longer uniformly -6; use it "
                         "instead of GEWICHT_P and revisit this script.")

    p["gw"] = pd.to_numeric(p["GEWICHT_P"], errors="coerce")
    dropped = int((~(p["gw"] >= 0)).sum())
    log.info("persons: weight >= 0 kept %d/%d (dropped %d)",
             len(p) - dropped, len(p), dropped)
    p = p[p["gw"] >= 0].copy()
    p["trips"] = pd.to_numeric(p["E_ANZ_WEGE"], errors="coerce")
    p["age"] = pd.to_numeric(p["V_ALTER"], errors="coerce")
    return p


def group_row(sub: pd.DataFrame, **ids) -> dict:
    valid = sub[sub["trips"] >= 0]
    if valid["gw"].sum() <= 0:
        raise ValueError(f"empty trip-class group: {ids}")
    cls = pd.cut(valid["trips"], bins=CLS_BINS, labels=CLS_COLS)
    dist = valid.groupby(cls, observed=False)["gw"].sum()
    total = dist.sum()
    invalid = ((sub["gw"] * (sub["trips"] < 0)).sum() / sub["gw"].sum())
    row = {**ids, "n_unweighted": int(len(valid)),
           "n_weighted": round(float(valid["gw"].sum()), 2)}
    row.update({c: round(float(dist[c] / total), 4) for c in CLS_COLS})
    row["share_trips_invalid"] = round(float(invalid), 4)
    return row


def build_by_kreis(p: pd.DataFrame) -> pd.DataFrame:
    rows = [group_row(p, level="total", code="total", name="Gesamt")]
    for kreis, name in KREIS_NAMES.items():
        rows.append(group_row(p[p["kreis"] == kreis], level="kreis",
                              code=kreis, name=name))
    for st_code, grp in p.groupby(p["ST_CODE"].astype(str)):
        rows.append(group_row(grp, level="stratum", code=st_code,
                              name=grp["ST_CODE_NAME"].iloc[0]))
    cols = ["level", "code", "name", "n_unweighted", "n_weighted",
            *CLS_COLS, "share_trips_invalid"]
    return pd.DataFrame(rows)[cols]


def build_by_age(p: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for lo, hi in AGE_BANDS:
        band = p[(p["age"] >= lo) & (p["age"] <= hi)]
        label = f"{lo}-{hi}" if hi < 120 else f"{lo}+"
        row = group_row(band, age_lo=lo, age_hi=hi, label=label)
        row.pop("share_trips_invalid")
        rows.append(row)
    cols = ["age_lo", "age_hi", "label", "n_unweighted", "n_weighted", *CLS_COLS]
    return pd.DataFrame(rows)[cols]


def write(df: pd.DataFrame, path: Path) -> None:
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(HEADER)
        df.to_csv(f, index=False)
    log.info("wrote %s (%d rows)", path, len(df))


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--raw", type=Path, default=RAW_DEFAULT)
    parser.add_argument("--out-dir", type=Path, default=OUT_DEFAULT)
    args = parser.parse_args(argv)
    if not (args.raw / "SrV2023_Personen.csv").exists():
        raise FileNotFoundError(f"SrV raw microdata not found under {args.raw}")
    p = load_persons(args.raw)
    write(build_by_kreis(p), args.out_dir / "srv2023_trip_classes_by_kreis.csv")
    write(build_by_age(p), args.out_dir / "srv2023_trip_classes_by_age.csv")
    return 0


if __name__ == "__main__":
    sys.exit(main())
