"""Measure the absence composition of a pipeline population and compare it to the SrV reference
(issue #426).

Reads a ``synthesis.output`` persons table (``<prefix>persons.csv``, ``;``-separated, must carry
``day_absence_state``), computes the three-way household pattern composition of ABSENT persons per
age band (``braunschweig.analysis.synthesis.absence_composition``) and compares the ``0-17``
children row to the committed reference ``srv2023_absence_composition_by_age_band.csv`` under the
pre-registered Wilson 95 % bound. Writes two provenance-headed CSVs to ``--out-dir``:

    absence_composition_model.csv    (the model table, same columns as the SrV table)
    absence_composition_vs_srv.csv   (one row per band x pattern with the bound and the verdict)

The header names the persons file (path, md5, row count), the run id, the code commit and the
reference, so a number quoted from these files traces to one population and one code state.

Usage (eqasim env):
    python scripts/measure_absence_composition.py --persons <path>/<prefix>persons.csv \
        --out-dir <dir> --run-id <run manifest id> --source-commit <sha>
"""
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import logging
import sys
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from braunschweig.analysis.synthesis import absence_composition as M  # noqa: E402
from braunschweig.calibration import srv_absence as A  # noqa: E402

REFERENCE_DEFAULT = REPO / "eqasim-data" / "data" / "braunschweig" / "srv" / A.ABSENCE_COMPOSITION_TABLE
MODEL_TABLE = "absence_composition_model.csv"
COMPARISON_TABLE = "absence_composition_vs_srv.csv"

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
logger = logging.getLogger("measure_absence_composition")


def _md5(path: Path) -> str:
    digest = hashlib.md5()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _header(table_name: str, args, persons_md5: str, n_persons: int) -> list:
    return [
        "# Source: %s (%d rows, md5 %s), the synthesis.output persons table of run %s."
        % (args.persons, n_persons, persons_md5, args.run_id),
        "# Generated by scripts/measure_absence_composition.py on %s; code state eqasim-bs %s"
        % (dt.date.today().isoformat(), args.source_commit),
        "#   (module braunschweig/analysis/synthesis/absence_composition.py, patterns from",
        "#   braunschweig/calibration/srv_absence.py: whole_household / partial_with_absent_adult /",
        "#   partial_no_absent_adult, child = age <= %d, adult = age >= %d)." % (A.CHILD_MAX_AGE, A.ADULT_MIN_AGE),
        "# Reference: %s" % args.reference,
        "# Table: %s" % table_name,
        "# Bound (pre-registered, issue #426 / ADR-0110 Amendment 3): the '%s' row is the acceptance"
        % A.CHILDREN_ROW,
        "#   row; a model share is accepted when it lies inside the Wilson 95 % interval of the",
        "#   reference row's UNWEIGHTED counts (ASSUMPTION: unknown design effect of the expansion",
        "#   weights). The seven age bands are diagnostic only. Weights on the model side are 1.0.",
    ]


def _write(df: pd.DataFrame, path: Path, header: list) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as handle:
        for line in header:
            handle.write(line + "\n")
        df.to_csv(handle, index=False, lineterminator="\n", float_format="%.10g")
    logger.info("wrote %s (%d rows)", path, len(df))


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--persons", type=Path, required=True)
    parser.add_argument("--reference", type=Path, default=REFERENCE_DEFAULT)
    parser.add_argument("--out-dir", type=Path, required=True)
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--source-commit", required=True)
    parser.add_argument("--sep", default=";")
    args = parser.parse_args(argv)
    for path in (args.persons, args.reference):
        if not path.is_file():
            raise FileNotFoundError(f"input not found: {path}")
    persons = pd.read_csv(args.persons, sep=args.sep, usecols=M.MODEL_PERSON_COLUMNS)
    persons_md5 = _md5(args.persons)
    logger.info("read %d persons from %s (md5 %s)", len(persons), args.persons, persons_md5)
    reference = pd.read_csv(args.reference, comment="#")
    model = M.model_absence_composition_by_band(persons)
    comparison = M.compare_composition(model, reference)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    verdicts = comparison[comparison["evaluated"]]
    summary = ["# Result '%s': " % A.CHILDREN_ROW + "; ".join(
        "%s model %.4f vs SrV [%.4f, %.4f] -> %s" % (r["pattern"], r["p_model"], r["srv_ci_low"], r["srv_ci_high"],
                                                     {True: "INSIDE", False: "OUTSIDE", None: "n/a"}[r["inside_interval"]])
        for _, r in verdicts.iterrows())]
    _write(model, args.out_dir / MODEL_TABLE, _header(MODEL_TABLE, args, persons_md5, len(persons)) + summary)
    _write(comparison, args.out_dir / COMPARISON_TABLE,
           _header(COMPARISON_TABLE, args, persons_md5, len(persons)) + summary)
    return 0


if __name__ == "__main__":
    sys.exit(main())
