"""Render the readiness register as a Markdown table.

The rendered table is generated output, never hand-edited: it is written to
``docs/readiness/README.md`` with a header saying so. Editing the table by hand is
how the STATUS matrix drifted in the first place; here the declarations are the
source of truth and the table is derived from them.
"""
from __future__ import annotations

import logging
import os
from typing import Sequence

from braunschweig.readiness.checks import FAIL, OK, SKIP, WARN, CheckContext, matrix_coverage
from braunschweig.readiness.registry import FeatureDeclaration

logger = logging.getLogger("braunschweig")

RENDER_TARGET = os.path.join("docs", "readiness", "README.md")

_SEVERITY_SYMBOL = {OK: "✅", WARN: "⚠️", FAIL: "❌", SKIP: "—"}

_STATUS_SYMBOL = {
    "on": "🟢 ON",
    "off_by_default": "⚪ OFF",
    "parked": "⏸ PARKED",
    "assumption": "⚠️ ASSUMPTION",
}


def _cell(findings_by_check, check: str) -> str:
    finding = findings_by_check.get(check)
    if finding is None:
        return "—"
    return _SEVERITY_SYMBOL.get(finding.severity, "?")


def render_table(declarations: Sequence[FeatureDeclaration], findings, context: CheckContext) -> str:
    """Return the full Markdown page for the register."""
    by_feature = {}
    for finding in findings:
        by_feature.setdefault(finding.feature, {})[finding.check] = finding

    covered, active = matrix_coverage(declarations, context)

    lines = [
        "# Feature-readiness register (generated)",
        "",
        "**Do not edit this file.** It is rendered from the declarations in "
        "`docs/readiness/*.yml` by `python -m braunschweig.readiness render`.",
        "",
        "Each column reports whether a declared pointer RESOLVES, not whether the feature is "
        "scientifically good: ✅ resolved, ⚠️ unproven or stale, ❌ contradicted by the repository, "
        "— not applicable. A ✅ in *Reference* means the reference file is committed, not that the "
        "model matches it; the realised fit lives in the KPI column and comes from a run.",
        "",
        f"Coverage: {covered}/{active} active rows of the `PROJECT_STATUS.md` feature matrix are declared.",
        "",
        "| Feature | State | Tests | OFF byte-id | Fallback | Reference | KPI / run | Assessment |",
        "|---|---|---|---|---|---|---|---|",
    ]

    for declaration in declarations:
        checks = by_feature.get(declaration.feature, {})
        byte_identity = str(declaration.off_path_byte_identical.get("claimed", "")).lower()
        byte_cell = {"true": "✅ proven", "false": "⚠️ not claimed",
                     "not_applicable": "—"}.get(byte_identity, "?")
        kpi = declaration.kpi
        kpi_cell = ("⚠️ none" if kpi.get("last_value") is None
                    else f"{kpi.get('name')} = {kpi.get('last_value')} ({kpi.get('measured_on')})")
        assessment = declaration.assessment or {}
        if declaration.assessment_is_pending:
            assessment_cell = "⏳ pending"
        elif assessment.get("by"):
            assessment_cell = f"{assessment.get('by')}, {assessment.get('date')}"
        else:
            assessment_cell = "❌ none"
        lines.append(
            f"| [{declaration.title}]({os.path.basename(declaration.source_file)}) "
            f"| {_STATUS_SYMBOL.get(declaration.status, declaration.status)} "
            f"| {_cell(checks, 'C2-tests')} "
            f"| {byte_cell} "
            f"| {_cell(checks, 'C4-fallback')} "
            f"| {_cell(checks, 'C3-reference')} "
            f"| {kpi_cell} "
            f"| {assessment_cell} |")

    lines += ["", "## Open findings", ""]
    open_findings = [f for f in findings if f.severity in (FAIL, WARN)]
    if not open_findings:
        lines.append("None — every declared pointer resolves.")
    else:
        for finding in open_findings:
            lines.append(f"- **{finding.severity}** `{finding.feature}` {finding.check}: {finding.message}")
    lines.append("")
    return "\n".join(lines)


def write_table(text: str, repo_root: str, target: str = RENDER_TARGET) -> str:
    """Write the rendered page and return its absolute path."""
    path = os.path.join(repo_root, target)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    logger.info("[readiness] rendered register to %s", path)
    return path
