import yaml

from braunschweig.runcontrol.configwriter import compose

TEMPLATE = """
run:
  - synthesis.output
config:
  sampling_rate: 0.25
  matsim_last_iteration: 9
"""


def test_compose_merges_overrides_and_names_file():
    fname, text = compose(TEMPLATE, {"matsim_last_iteration": 199},
                          label="prod-100", template_name="config_server_x.yml",
                          git_commit="abc1234", now_iso="2026-07-08T15:30:00")
    assert fname == "config_gui_prod-100_20260708_153000.yml"
    doc = yaml.safe_load(text)
    assert doc["config"]["matsim_last_iteration"] == 199
    assert doc["config"]["sampling_rate"] == 0.25
    assert doc["run"] == ["synthesis.output"]


def test_compose_header_documents_provenance():
    _, text = compose(TEMPLATE, {"matsim_last_iteration": 199},
                      label="prod-100", template_name="config_server_x.yml",
                      git_commit="abc1234", now_iso="2026-07-08T15:30:00")
    head = text.split("run:")[0]
    for needle in ("config_server_x.yml", "abc1234", "matsim_last_iteration: 9 -> 199",
                   "generated by braunschweig.runcontrol"):
        assert needle in head


def test_label_is_sanitized_for_filenames():
    fname, _ = compose(TEMPLATE, {}, label="weird label/x", template_name="t.yml",
                       git_commit="unknown", now_iso="2026-07-08T15:30:00")
    assert fname == "config_gui_weird-label-x_20260708_153000.yml"
